Make profiles being able to load any variable
Profiles changes:
- profiles are now able to load any variable like
  CONF_OVERRIDE_DIR, ...
- moved Profiles::loadProfile from bash-tools-framework
- Profiles::loadProfile
  - make it work with full profile path
  - added unit tests
- Profiles::allDepsRecursive
  - make it fails if recursive call is failing
  - fixed unit tests

Other fixes:
  - Fzf - show fortunes only if active shell is zsh
  - Fortune
    - make it fails if fortune generation fails
    - fortune generation displays number of fortunes
      generated by configuration
    - make it compatible with full installScripts path
    - always generate fortune even if SHOW_FORTUNES=0

diff --git a/bin/fortune b/bin/fortune
--- a/bin/fortune
+++ b/bin/fortune
@@ -584,48 +584,42 @@ Profiles::getProfilePath() {
   return 1
 }
 
-# @description load profile file based on profileDir and profile argument
-# The profile file is ${profileDir}/profile.${profile}.sh
+# @description load profile file based on profileFile argument
+# The profile file is profileDir/profile.profile.sh
 # This file should define the variable CONFIG_LIST with array type
-# @warning warning
-# @arg $1 arg1Name:arg1Type
-# @arg $@ args:String[]
-# @set envVar type description
-# @env envVar type description
-# @exitcode 1 if one of the 2 arguments is not provided
-# @exitcode 2 if profile not found at location ${profileDir}/profile.${profile}.sh
+# @arg $1 profileFile:String full profile path
+# @exitcode 1 if argument is not provided
+# @exitcode 2 if profile not found
 # @exitcode 3 if profile found but CONFIG_LIST variable unset
 # @exitcode 4 if profile found but CONFIG_LIST variable empty
 # @exitcode 5 if error occurs during profile loading
-# @stdout list of unique config items provided by profile's CONFIG_LIST array
 # @stderr diagnostics information is displayed
 # @see Profiles::allDepsRecursive in order to load all the dependencies recursively based on this list
+# @set CONFIG_LIST
 Profiles::loadProfile() {
-  local profileDir="$1"
-  local profile="$2"
-  local -a CONFIG_LIST=()
+  local profileFile="$1"
 
-  if [[ -z "${profile}" || -z "${profileDir}" ]]; then
-    Log::displayError "This method needs exactly 2 parameters"
+  if [[ -z "${profileFile}" ]]; then
+    Log::displayError "This method needs exactly 1 parameter"
     return 1
   fi
 
   # load the profile
-  Log::displayInfo "Loading profile '${profileDir}/profile.${profile}.sh'"
-  if [[ ! -f "${profileDir}/profile.${profile}.sh" ]]; then
-    Log::displayError "profile profile.${profile}.sh not found in '${profileDir}'"
+  Log::displayInfo "Loading profile '${profileFile}'"
+  if [[ ! -f "${profileFile}" ]]; then
+    Log::displayError "profile ${profileFile} not found"
     return 2
   fi
 
   # shellcheck source=src/Profiles/testsData/profile.test1.sh
-  source "${profileDir}/profile.${profile}.sh" || return 5
+  source "${profileFile}" || return 5
 
   if [[ ! -v CONFIG_LIST ]]; then
-    Log::displayError "Profile ${profileDir}/profile.${profile}.sh missing variable CONFIG_LIST"
+    Log::displayError "Profile ${profileFile} missing variable CONFIG_LIST"
     return 3
   fi
   if [[ ${#CONFIG_LIST[@]} -eq 0 ]]; then
-    Log::displayError "Profile ${profileDir}/profile.${profile}.sh variable CONFIG_LIST cannot be empty"
+    Log::displayError "Profile ${profileFile} variable CONFIG_LIST cannot be empty"
     return 4
   fi
 
@@ -633,7 +627,6 @@ Profiles::loadProfile() {
   mapfile -t CONFIG_LIST < <(
     IFS=$'\n' printf '%s\n' "${CONFIG_LIST[@]}" | Filters::uniqUnsorted
   )
-  printf '%s\n' "${CONFIG_LIST[@]}"
 }
 
 declare -Ag allDepsResultSeen=()
@@ -700,7 +693,7 @@ Profiles::allDepsRecursive() {
     )
     if ((${#newDeps} > 0)); then
       Log::displayInfo "${i} depends on ${newDeps[*]}"
-      Profiles::allDepsRecursive "${scriptsDir}" "${i}" "${newDeps[@]}"
+      Profiles::allDepsRecursive "${scriptsDir}" "${i}" "${newDeps[@]}" || return $?
     fi
     if [[ "${addDep}" = "1" ]]; then
       Log::displayInfo "${i} is a dependency of ${parent}"
@@ -1790,7 +1783,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
@@ -2146,10 +2139,7 @@ commandCallback() {
     local profilePath
     profilePath="$(Profiles::getProfilePath "${PROFILE}")" # should succeed as it was tested by option
     # load selected profile
-    mapfile -t CONFIG_LIST < <(
-      IFS=$'\n' Profiles::loadProfile \
-        "$(dirname "${profilePath}")" "${PROFILE}"
-    )
+    Profiles::loadProfile "${profilePath}"
   fi
   if [[ "${SKIP_DEPENDENCIES:-0}" = "0" ]]; then
     CONFIG_LIST=("${CONFIG_LIST[@]}")
@@ -2612,22 +2602,23 @@ fortuneCommand parse "${BASH_FRAMEWORK_ARGV[@]}"
 
 generateFortunes() {
   echo >/etc/fortune-help-commands
-  if [[ "${SHOW_FORTUNES}" = "1" ]]; then
-    (
-      for configName in "${CONFIG_LIST[@]}"; do
-        (
-          local fortunes
-          fortunes="$("${INSTALL_SCRIPTS_ROOT_DIR}/${configName}" fortunes | Filters::trimEmptyLines)"
-          if [[ -n "${fortunes}" ]]; then
-            echo "${fortunes}"
-          fi
-        ) >>/etc/fortune-help-commands || {
-          Log::displayWarning "Script ${configName} - fortunes failed to be loaded"
-        }
-      done
-    ) 2>&1 | tee >(sed -r 's/\x1b\[[0-9;]*m//g' >>"${LOGS_DIR}/automatic-fortune") || return 1
-    Log::displayInfo "$(grep -cE '^%$' /etc/fortune-help-commands) fortunes generated"
-  fi
+  (
+    for configName in "${CONFIG_LIST[@]}"; do
+      (
+        local fortunes
+        fortunes="$("${BASH_DEV_ENV_ROOT_DIR}/${configName}" fortunes | Filters::trimEmptyLines)"
+        if [[ -n "${fortunes}" ]]; then
+          echo "${fortunes}"
+          Log::displayInfo "${configName} - $(grep -cE '^%$'<<<"${fortunes}") fortunes generated"
+        else
+          Log::displayInfo "${configName} - no fortune generated"
+        fi
+      ) >>/etc/fortune-help-commands || {
+        Log::displayWarning "Script ${configName} - fortunes failed to be loaded"
+      }
+    done
+  ) 2>&1 | tee >(sed -r 's/\x1b\[[0-9;]*m//g' >>"${LOGS_DIR}/automatic-fortune") || return 1
+  Log::displayInfo "$(grep -cE '^%$' /etc/fortune-help-commands) fortunes generated"
 }
 
 generateFortunesDat() {
@@ -2640,7 +2631,7 @@ generateFortunesDat() {
 run() {
   LOGS_DIR="${LOGS_DIR:-${PERSISTENT_TMPDIR}}"
 
-  Profiles::checkScriptsExistence "${INSTALL_SCRIPTS_DIR}" "" "${CONFIG_LIST[@]}"
+  Profiles::checkScriptsExistence "${INSTALL_SCRIPTS_ROOT_DIR}" "" "${CONFIG_LIST[@]}"
   Log::displayInfo "Will Install ${CONFIG_LIST[*]}"
 
   # Start install process
diff --git a/installScripts/BashTools b/installScripts/BashTools
--- a/installScripts/BashTools
+++ b/installScripts/BashTools
@@ -1495,8 +1495,14 @@ Git::cloneOrPullIfNoChanges() {
   shift || true
 
   if [[ -d "${dir}/.git" ]]; then
-    if ! Git::pullIfNoChanges "${dir}"; then
-      return 1
+    local exitCode=0
+    Git::pullIfNoChanges "${dir}" || exitCode=$?
+    if Array::contains "${exitCode}" "2" "4"; then
+      # changes detected
+      return 0
+    fi
+    if [[ "${exitCode}" != "0" ]]; then
+      return "${exitCode}"
     fi
     # shellcheck disable=SC2086
     if [[ "$(type -t ${pullCallback})" = "function" ]]; then
@@ -2412,7 +2418,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
diff --git a/installScripts/Font b/installScripts/Font
--- a/installScripts/Font
+++ b/installScripts/Font
@@ -884,8 +884,14 @@ Git::cloneOrPullIfNoChanges() {
   shift || true
 
   if [[ -d "${dir}/.git" ]]; then
-    if ! Git::pullIfNoChanges "${dir}"; then
-      return 1
+    local exitCode=0
+    Git::pullIfNoChanges "${dir}" || exitCode=$?
+    if Array::contains "${exitCode}" "2" "4"; then
+      # changes detected
+      return 0
+    fi
+    if [[ "${exitCode}" != "0" ]]; then
+      return "${exitCode}"
     fi
     # shellcheck disable=SC2086
     if [[ "$(type -t ${pullCallback})" = "function" ]]; then
@@ -1572,6 +1578,22 @@ Git::pullIfNoChanges() {
   )
 }
 
+# @description check if an element is contained in an array
+#
+# @arg $1 needle:String
+# @arg $@ array:String[]
+# @exitcode 0 if found
+# @exitcode 1 otherwise
+# @example
+#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
+Array::contains() {
+  local element
+  for element in "${@:2}"; do
+    [[ "${element}" = "$1" ]] && return 0
+  done
+  return 1
+}
+
 # @description Compute a cache from wslpath options
 # @arg $@ args:String[] arguments passed to wslpath
 # @stderr diagnostics information is displayed
@@ -1729,22 +1751,6 @@ Assert::varExistsAndNotEmpty() {
     Log::displayError "${varName} - please provide a value"
     return 2
   fi
-}
-
-# @description check if an element is contained in an array
-#
-# @arg $1 needle:String
-# @arg $@ array:String[]
-# @exitcode 0 if found
-# @exitcode 1 otherwise
-# @example
-#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
-Array::contains() {
-  local element
-  for element in "${@:2}"; do
-    [[ "${element}" = "$1" ]] && return 0
-  done
-  return 1
 }
 
 # @description check if argument respects ldap login naming convention
@@ -2044,7 +2050,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
diff --git a/installScripts/Fortune b/installScripts/Fortune
--- a/installScripts/Fortune
+++ b/installScripts/Fortune
@@ -2224,7 +2224,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
@@ -3238,7 +3238,10 @@ configure() {
       "${cmd[@]}"
 
     # generate /etc/fortune-help-commands and /etc/fortune-help-commands.dat
-    SKIP_REQUIRES=1 "${cmd[@]}"
+    SKIP_REQUIRES=1 "${cmd[@]}" || {
+      Log::displayError "fortunes generation failure"
+      return 1
+    }
   fi
 
   # shellcheck disable=SC2154
diff --git a/installScripts/Fzf b/installScripts/Fzf
--- a/installScripts/Fzf
+++ b/installScripts/Fzf
@@ -893,8 +893,14 @@ Git::cloneOrPullIfNoChanges() {
   shift || true
 
   if [[ -d "${dir}/.git" ]]; then
-    if ! Git::pullIfNoChanges "${dir}"; then
-      return 1
+    local exitCode=0
+    Git::pullIfNoChanges "${dir}" || exitCode=$?
+    if Array::contains "${exitCode}" "2" "4"; then
+      # changes detected
+      return 0
+    fi
+    if [[ "${exitCode}" != "0" ]]; then
+      return "${exitCode}"
     fi
     # shellcheck disable=SC2086
     if [[ "$(type -t ${pullCallback})" = "function" ]]; then
@@ -1638,6 +1644,22 @@ Git::pullIfNoChanges() {
   )
 }
 
+# @description check if an element is contained in an array
+#
+# @arg $1 needle:String
+# @arg $@ array:String[]
+# @exitcode 0 if found
+# @exitcode 1 otherwise
+# @example
+#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
+Array::contains() {
+  local element
+  for element in "${@:2}"; do
+    [[ "${element}" = "$1" ]] && return 0
+  done
+  return 1
+}
+
 # @description filter to keep only version number from a string
 # @arg $@ files:String[] the files to filter
 # @exitcode * if one of the filter command fails
@@ -1908,22 +1930,6 @@ Assert::varExistsAndNotEmpty() {
     Log::displayError "${varName} - please provide a value"
     return 2
   fi
-}
-
-# @description check if an element is contained in an array
-#
-# @arg $1 needle:String
-# @arg $@ array:String[]
-# @exitcode 0 if found
-# @exitcode 1 otherwise
-# @example
-#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
-Array::contains() {
-  local element
-  for element in "${@:2}"; do
-    [[ "${element}" = "$1" ]] && return 0
-  done
-  return 1
 }
 
 # @description check if argument respects ldap login naming convention
@@ -2347,7 +2353,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
@@ -3330,7 +3336,7 @@ breakOnTestFailure() { :; }
 # jscpd:ignore-end
 
 fortunes() {
-  if [[ -f "${HOME}/.fzf/shell/key-bindings.zsh" ]]; then
+  if [[ "${USER_SHELL}" = "/usr/bin/zsh" && -f "${HOME}/.fzf/shell/key-bindings.zsh" ]]; then
     echo "$(scriptName) - Fzf - CTRL-T - Paste the selected file path(s) into the command line"
     echo "%"
     echo "$(scriptName) - Fzf - ALT-C - cd into the selected directory"
