renmaed USER_HOME env variable to HOME

diff --git a/bin/installBashTools b/bin/installBashTools
--- a/bin/installBashTools
+++ b/bin/installBashTools
@@ -166,7 +166,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -199,7 +199,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -312,7 +312,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -322,12 +322,12 @@ Tools::installBashTools() {
   # shellcheck disable=SC2317
   function installBashTools() {
     (
-      cd "${USER_HOME}/fchastanet/bash-tools" || return 1
+      cd "${HOME}/fchastanet/bash-tools" || return 1
       ./install
     )
   }
   Git::cloneOrPullIfNoChanges \
-    "${USER_HOME}/fchastanet/bash-tools" \
+    "${HOME}/fchastanet/bash-tools" \
     "https://github.com/fchastanet/bash-tools.git" \
     installBashTools
 }
@@ -436,12 +436,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -450,17 +450,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -557,7 +557,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
diff --git a/installScripts/AwsDefaultConfig b/installScripts/AwsDefaultConfig
--- a/installScripts/AwsDefaultConfig
+++ b/installScripts/AwsDefaultConfig
@@ -217,7 +217,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -250,7 +250,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -363,7 +363,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -1003,16 +1003,16 @@ Install::file() {
 # @arg $1 embedDir:String the path embedded
 # @arg $2 overrideDir:String the path overridden
 # @arg $3 subDir:String the sub-directory to copy from embedDir and/or overrideDir
-# @arg $4 targetDir:String the target directory (default: ${USER_HOME}/${subDir})
+# @arg $4 targetDir:String the target directory (default: ${HOME}/${subDir})
 # @env SUDO String allows to use custom sudo prefix command
-# @env USER_HOME used for default value of targetDir arg
+# @env HOME used for default value of targetDir arg
 # @env OVERWRITE_CONFIG_FILES indicates if target directory should be overwritten if it exists
 # @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
 Conf::copyStructure() {
   local embedDir="$1"
   local overrideDir="$2"
   local subDir="$3"
-  local targetDir="${4:-${USER_HOME}/${subDir}}"
+  local targetDir="${4:-${HOME}/${subDir}}"
 
   local configDir
   # shellcheck disable=SC2154
@@ -1242,12 +1242,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1256,17 +1256,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1363,7 +1363,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -3154,7 +3154,7 @@ dependencies() {
 }
 
 listVariables() {
-  echo "USER_HOME"
+  echo "HOME"
   echo "USERNAME"
   echo "USERGROUP"
   echo "CAN_TALK_DURING_INSTALLATION"
@@ -3186,11 +3186,11 @@ configure() {
   configureAwsConfig() {
     sed -i -E \
       -e "s#azure_default_username=.+\$#azure_default_username=${AWS_USER_MAIL}#" \
-      "${USER_HOME}/.aws/config"
+      "${HOME}/.aws/config"
     Install::setUserRightsCallback "$@"
   }
   OVERWRITE_CONFIG_FILES=0 Install::file \
-    "${configDir}/.aws/config" "${USER_HOME}/.aws/config" \
+    "${configDir}/.aws/config" "${HOME}/.aws/config" \
     "${USERNAME}" "${USERGROUP}" configureAwsConfig
   # shellcheck disable=SC2154
   Conf::copyStructure \
@@ -3218,26 +3218,26 @@ configure() {
 testConfigure() {
   local -i failures=0
 
-  Assert::fileExists "${USER_HOME}/.aws/config" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/awsCli.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/saml2aws.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.aws/config" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/awsCli.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/saml2aws.sh" || ((++failures))
 
-  if grep -q -E -e "azure_default_username=.+$" "${USER_HOME}/.aws/config"; then
+  if grep -q -E -e "azure_default_username=.+$" "${HOME}/.aws/config"; then
     # case where .aws/config has been overridden in conf_override folder
     local azureUserName
-    azureUserName="$(sed -nr 's/azure_default_username=(.*)$/\1/p' "${USER_HOME}/.aws/config")"
+    azureUserName="$(sed -nr 's/azure_default_username=(.*)$/\1/p' "${HOME}/.aws/config")"
     if [[ -z "${azureUserName}" ]]; then
       ((++failures))
-      Log::displayError "empty azure_default_username in '${USER_HOME}/.aws/config'"
+      Log::displayError "empty azure_default_username in '${HOME}/.aws/config'"
     elif [[ "${azureUserName}" != "${AWS_USER_MAIL}" ]]; then
       Log::displayWarning "azureUserName is not the same as AWS_USER_MAIL in ${BASH_DEV_ENV_ROOT_DIR}/.env"
     fi
-  elif ! grep -q -E -e "^\[default\]$" "${USER_HOME}/.aws/config"; then
+  elif ! grep -q -E -e "^\[default\]$" "${HOME}/.aws/config"; then
     ((++failures))
-    Log::displayError "default configuration not found in '${USER_HOME}/.aws/config'"
+    Log::displayError "default configuration not found in '${HOME}/.aws/config'"
   fi
 
-  Assert::fileExists "${USER_HOME}/.saml2aws" || ((++failures))
+  Assert::fileExists "${HOME}/.saml2aws" || ((++failures))
 
   if [[ "${INSTALL_INTERACTIVE}" = "0" ]]; then
     Log::displaySkipped "saml2aws configuration skipped as INSTALL_INTERACTIVE is set to 0"
diff --git a/installScripts/KubeDefaultConfig b/installScripts/KubeDefaultConfig
--- a/installScripts/KubeDefaultConfig
+++ b/installScripts/KubeDefaultConfig
@@ -188,7 +188,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -221,7 +221,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -334,7 +334,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -1096,16 +1096,16 @@ Assert::fileExists() {
 # @arg $1 embedDir:String the path embedded
 # @arg $2 overrideDir:String the path overridden
 # @arg $3 subDir:String the sub-directory to copy from embedDir and/or overrideDir
-# @arg $4 targetDir:String the target directory (default: ${USER_HOME}/${subDir})
+# @arg $4 targetDir:String the target directory (default: ${HOME}/${subDir})
 # @env SUDO String allows to use custom sudo prefix command
-# @env USER_HOME used for default value of targetDir arg
+# @env HOME used for default value of targetDir arg
 # @env OVERWRITE_CONFIG_FILES indicates if target directory should be overwritten if it exists
 # @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
 Conf::copyStructure() {
   local embedDir="$1"
   local overrideDir="$2"
   local subDir="$3"
-  local targetDir="${4:-${USER_HOME}/${subDir}}"
+  local targetDir="${4:-${HOME}/${subDir}}"
 
   local configDir
   # shellcheck disable=SC2154
@@ -1240,12 +1240,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1254,17 +1254,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1361,7 +1361,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -3618,13 +3618,13 @@ isKubeConfigGenerationAvailable() {
 }
 
 configure() {
-  mkdir -p "${USER_HOME}/.bash_completion.d" || true
-  chown "${USERNAME}":"${USERGROUP}" "${USER_HOME}/.bash_completion.d"
+  mkdir -p "${HOME}/.bash_completion.d" || true
+  chown "${USERNAME}":"${USERGROUP}" "${HOME}/.bash_completion.d"
 
-  ln -sf /opt/kubectx/completion/kubens.bash "${USER_HOME}/.bash_completion.d/kubens"
-  chown -h "${USERNAME}":"${USERGROUP}" "${USER_HOME}/.bash_completion.d/kubens"
-  ln -sf /opt/kubectx/completion/kubectx.bash "${USER_HOME}/.bash_completion.d/kubectx"
-  chown -h "${USERNAME}":"${USERGROUP}" "${USER_HOME}/.bash_completion.d/kubectx"
+  ln -sf /opt/kubectx/completion/kubens.bash "${HOME}/.bash_completion.d/kubens"
+  chown -h "${USERNAME}":"${USERGROUP}" "${HOME}/.bash_completion.d/kubens"
+  ln -sf /opt/kubectx/completion/kubectx.bash "${HOME}/.bash_completion.d/kubectx"
+  chown -h "${USERNAME}":"${USERGROUP}" "${HOME}/.bash_completion.d/kubectx"
 
   # shellcheck disable=SC2154
   Conf::copyStructure \
@@ -3637,7 +3637,7 @@ configure() {
     "${CONF_OVERRIDE_DIR}/$(scriptName)" \
     ".kube" || true # ignore if conf override does not define .kube/config
 
-  if [[ ! -f "${USER_HOME}/.kube/config" ]] && isKubeConfigGenerationAvailable "generation"; then
+  if [[ ! -f "${HOME}/.kube/config" ]] && isKubeConfigGenerationAvailable "generation"; then
     aws eks update-kubeconfig \
       --region "${KUBE_CONFIG_REGION_CODE}" \
       --name "${KUBE_CONFIG_CLUSTER_ARN}" || return 1
@@ -3646,12 +3646,12 @@ configure() {
 
 testConfigure() {
   local -i failures=0
-  Assert::dirExists "${USER_HOME}/.bash_completion.d" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash_completion.d/kubens" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash_completion.d/kubectx" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/interactive.d/kube-ps1.sh" || ((++failures))
+  Assert::dirExists "${HOME}/.bash_completion.d" || ((++failures))
+  Assert::fileExists "${HOME}/.bash_completion.d/kubens" || ((++failures))
+  Assert::fileExists "${HOME}/.bash_completion.d/kubectx" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/interactive.d/kube-ps1.sh" || ((++failures))
   if isKubeConfigGenerationAvailable "test"; then
-    Assert::fileExists "${USER_HOME}/.kube/config" || ((++failures))
+    Assert::fileExists "${HOME}/.kube/config" || ((++failures))
   fi
 
   return "${failures}"
diff --git a/installScripts/NodeDependencies b/installScripts/NodeDependencies
--- a/installScripts/NodeDependencies
+++ b/installScripts/NodeDependencies
@@ -165,7 +165,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -198,7 +198,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -311,7 +311,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -953,12 +953,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -967,17 +967,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1074,7 +1074,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -2812,12 +2812,12 @@ breakOnTestFailure() { :; }
 # jscpd:ignore-end
 
 install() {
-  if [[ ! -d "${USER_HOME}/n" ]]; then
+  if [[ ! -d "${HOME}/n" ]]; then
     Log::displaySkipped "node dependencies skipped as node not installed"
     return 0
   fi
   # shellcheck source=src/_binaries/NodeNpm/conf/.bash-dev-env/profile.d/n_path.sh
-  HOME="${USER_HOME}" source "${USER_HOME}/.bash-dev-env/profile.d/n_path.sh"
+  HOME="${HOME}" source "${HOME}/.bash-dev-env/profile.d/n_path.sh"
 
   # npm install
   npmInstall() {
@@ -2844,7 +2844,7 @@ install() {
 testInstall() {
   local -i failures=0
   # shellcheck source=src/_binaries/NodeNpm/conf/.bash-dev-env/profile.d/n_path.sh
-  HOME="${USER_HOME}" source "${USER_HOME}/.bash-dev-env/profile.d/n_path.sh"
+  HOME="${HOME}" source "${HOME}/.bash-dev-env/profile.d/n_path.sh"
   Version::checkMinimal "npm-check-updates" "--version" "11.5.13" || ((++failures))
   Version::checkMinimal "prettier" "--version" "2.3.0" || ((++failures))
   Version::checkMinimal "sass-lint" "--version" "1.13.1" || ((++failures))
diff --git a/installScripts/Python b/installScripts/Python
--- a/installScripts/Python
+++ b/installScripts/Python
@@ -188,7 +188,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -221,7 +221,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -334,7 +334,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -887,16 +887,16 @@ Linux::Apt::installIfNecessary() {
 # @arg $1 embedDir:String the path embedded
 # @arg $2 overrideDir:String the path overridden
 # @arg $3 subDir:String the sub-directory to copy from embedDir and/or overrideDir
-# @arg $4 targetDir:String the target directory (default: ${USER_HOME}/${subDir})
+# @arg $4 targetDir:String the target directory (default: ${HOME}/${subDir})
 # @env SUDO String allows to use custom sudo prefix command
-# @env USER_HOME used for default value of targetDir arg
+# @env HOME used for default value of targetDir arg
 # @env OVERWRITE_CONFIG_FILES indicates if target directory should be overwritten if it exists
 # @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
 Conf::copyStructure() {
   local embedDir="$1"
   local overrideDir="$2"
   local subDir="$3"
-  local targetDir="${4:-${USER_HOME}/${subDir}}"
+  local targetDir="${4:-${HOME}/${subDir}}"
 
   local configDir
   # shellcheck disable=SC2154
@@ -1074,12 +1074,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1088,17 +1088,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1195,7 +1195,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -3257,8 +3257,8 @@ install() {
   Linux::Apt::installIfNecessary --no-install-recommends "${packages[@]}"
 
   mkdir -p \
-    "${USER_HOME}/.local/bin" \
-    "${USER_HOME}/.local/lib"
+    "${HOME}/.local/bin" \
+    "${HOME}/.local/lib"
 
   # Installing virtualenv
   PIP_REQUIRE_VIRTUALENV=false python -m pip install virtualenv
@@ -3283,20 +3283,20 @@ testInstall() {
   # since virtualenv is not loaded python 3.9 is not yet available
   Version::checkMinimal "python" "--version" "3.8.10" || ((++failures))
   Version::checkMinimal "virtualenv" "--version" "20.25.1" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/profile.d/python_path.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/profile.d/python_path.sh" || ((++failures))
   return "${failures}"
 }
 
 configure() {
   # create home directory that will receive virtualenv configs
-  mkdir -p "${USER_HOME}/.virtualenvs" || true
-  mkdir -p "${USER_HOME}/.pip/cache" || true
+  mkdir -p "${HOME}/.virtualenvs" || true
+  mkdir -p "${HOME}/.pip/cache" || true
 
   # create python3.9 virtual env
   # virtualenv (for Python 3) and venv (for Python 2)
   # allows you to manage separate package installations
   # for different projects.
-  virtualenv --system-site-packages --python=/usr/bin/python3.9 "${USER_HOME}/.virtualenvs/python3.9"
+  virtualenv --system-site-packages --python=/usr/bin/python3.9 "${HOME}/.virtualenvs/python3.9"
   upgradePipPackages
 }
 
@@ -3304,10 +3304,10 @@ upgradePipPackages() {
   if [[ "${PIP_PACKAGES_UPGRADED:-0}" = "1" ]]; then
     return 0
   fi
-  if [[ -f "${USER_HOME}/.virtualenvs/python3.9/bin/activate" ]]; then
+  if [[ -f "${HOME}/.virtualenvs/python3.9/bin/activate" ]]; then
     # load this virtualenv
     # shellcheck source=/dev/null
-    source "${USER_HOME}/.virtualenvs/python3.9/bin/activate"
+    source "${HOME}/.virtualenvs/python3.9/bin/activate"
 
     # remove duplicate pip packages with ~ prefix that breaks pip packages upgrade otherwise
     find "${VIRTUAL_ENV}/lib/python3.9/site-packages" -name '~*' -exec rm -Rf {} ';' || true
@@ -3321,10 +3321,10 @@ upgradePipPackages() {
 testConfigure() {
   local -i failures=0
   # shellcheck source=/dev/null
-  source "${USER_HOME}/.virtualenvs/python3.9/bin/activate" || ((++failures))
+  source "${HOME}/.virtualenvs/python3.9/bin/activate" || ((++failures))
   Version::checkMinimal "python" "--version" "3.9.18" || ((++failures))
   Version::checkMinimal "pip" "--version" "24.0" || ((++failures))
-  [[ "${VIRTUAL_ENV}" = "${USER_HOME}/.virtualenvs/python3.9" ]] || {
+  [[ "${VIRTUAL_ENV}" = "${HOME}/.virtualenvs/python3.9" ]] || {
     Log::displayError "Virtualenv has not been loaded correctly"
     ((++failures))
   }
diff --git a/installScripts/ShellBash b/installScripts/ShellBash
--- a/installScripts/ShellBash
+++ b/installScripts/ShellBash
@@ -188,7 +188,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -221,7 +221,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -334,7 +334,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -921,16 +921,16 @@ Retry::default() {
 # @arg $1 embedDir:String the path embedded
 # @arg $2 overrideDir:String the path overridden
 # @arg $3 subDir:String the sub-directory to copy from embedDir and/or overrideDir
-# @arg $4 targetDir:String the target directory (default: ${USER_HOME}/${subDir})
+# @arg $4 targetDir:String the target directory (default: ${HOME}/${subDir})
 # @env SUDO String allows to use custom sudo prefix command
-# @env USER_HOME used for default value of targetDir arg
+# @env HOME used for default value of targetDir arg
 # @env OVERWRITE_CONFIG_FILES indicates if target directory should be overwritten if it exists
 # @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
 Conf::copyStructure() {
   local embedDir="$1"
   local overrideDir="$2"
   local subDir="$3"
-  local targetDir="${4:-${USER_HOME}/${subDir}}"
+  local targetDir="${4:-${HOME}/${subDir}}"
 
   local configDir
   # shellcheck disable=SC2154
@@ -1179,12 +1179,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1193,17 +1193,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1300,7 +1300,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -3158,8 +3158,8 @@ configure() {
     fi
   fi
 
-  mkdir -p "${USER_HOME}/.bash-dev-env/interactive.d" || return 1
-  Retry::default curl -o "${USER_HOME}/.bash-dev-env/interactive.d/git-prompt.sh" \
+  mkdir -p "${HOME}/.bash-dev-env/interactive.d" || return 1
+  Retry::default curl -o "${HOME}/.bash-dev-env/interactive.d/git-prompt.sh" \
     https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh || return 1
 
   # shellcheck disable=SC2154
@@ -3177,7 +3177,7 @@ configure() {
     "${embed_dir_conf_dir}" \
     "${CONF_OVERRIDE_DIR}/$(scriptName)" \
     "home" \
-    "${USER_HOME}"
+    "${HOME}"
 
   local configDir
   # shellcheck disable=SC2154
@@ -3195,37 +3195,37 @@ configure() {
 
 testConfigure() {
   local -i failures=0
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/interactive.d/git-prompt.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/interactive.d/git-prompt.sh" || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.bash_logout" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bashrc" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.dir_colors" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.inputrc" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.profile" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.vimrc" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.Xresources" || ((++failures))
+  Assert::fileExists "${HOME}/.bash_logout" || ((++failures))
+  Assert::fileExists "${HOME}/.bashrc" || ((++failures))
+  Assert::fileExists "${HOME}/.dir_colors" || ((++failures))
+  Assert::fileExists "${HOME}/.inputrc" || ((++failures))
+  Assert::fileExists "${HOME}/.profile" || ((++failures))
+  Assert::fileExists "${HOME}/.vimrc" || ((++failures))
+  Assert::fileExists "${HOME}/.Xresources" || ((++failures))
 
   SUDO=sudo Assert::fileExists /root/.vimrc root root || ((++failures))
   SUDO=sudo Assert::fileExists /root/.inputrc root root || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/colors.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/filesDirectory.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/miscellaneous.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/ssh.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/xserver.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/aliases.d/DISCLAIMER.md" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/colors.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/filesDirectory.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/miscellaneous.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/ssh.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/xserver.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/aliases.d/DISCLAIMER.md" || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/completions.d/makeTargets.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/completions.d/DISCLAIMER.md" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/completions.d/makeTargets.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/completions.d/DISCLAIMER.md" || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/interactive.d/zzz_bash_prompt.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/interactive.d/bash_navigation.sh" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/interactive.d/DISCLAIMER.md" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/interactive.d/zzz_bash_prompt.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/interactive.d/bash_navigation.sh" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/interactive.d/DISCLAIMER.md" || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/profile.d/DISCLAIMER.md" || ((++failures))
+  Assert::fileExists "${HOME}/.bash-dev-env/profile.d/DISCLAIMER.md" || ((++failures))
 
-  Assert::fileExists "${USER_HOME}/.vscode/argv.json" || ((++failures))
-  Assert::fileExists "${USER_HOME}/.vscode/settings.json" || ((++failures))
+  Assert::fileExists "${HOME}/.vscode/argv.json" || ((++failures))
+  Assert::fileExists "${HOME}/.vscode/settings.json" || ((++failures))
 
   # check font in windows terminal configuration
   local terminalConfFile
