New install scripts based on github
Changes:
- Log::headLine - displays duration if enabled
- moved scripts that install binary from github
  in src/_binaries/installScripts/githubReleaseScripts directory
- New install scripts based on github:
  - Oq,
  - Hadolint,
  - Fd(Fzf dependency),
  - Bat(Fzf dependency),
  - DockerCompose(now dependency of Docker)

Bug fixes:
- SKIP_REQUIRES=1 when calling dependencies

diff --git a/bin/installRequirements b/bin/installRequirements
--- a/bin/installRequirements
+++ b/bin/installRequirements
@@ -370,7 +370,7 @@ EOF
 # @description load .env file
 # @arg $1 envFile:String the file to load
 Engine::Config::loadConfig() {
-  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-}" = "1" ]]; then
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
     return 0
   fi
   local envFile="${BASH_DEV_ENV_ROOT_DIR}/.env"
@@ -523,7 +523,8 @@ export __VERBOSE_LEVEL_TRACE=3
 # @arg $1 message:String the message to display
 Log::displayDebug() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_DEBUG)); then
-    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logDebug "$1"
 }
@@ -532,14 +533,11 @@ Log::displayDebug() {
 # @arg $1 message:String the message to display
 Log::displayError() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_ERROR)); then
-    echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__ERROR_COLOR}ERROR   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logError "$1"
 }
-
-FIRST_LOG_DATE="$(date '+%s%3N')"
-LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
-LOG_LAST_LOG_DATE_INIT=1
 
 # @description Display message using info color (bg light blue/fg white)
 # @arg $1 message:String the message to display
@@ -547,21 +545,8 @@ LOG_LAST_LOG_DATE_INIT=1
 Log::displayInfo() {
   local type="${2:-INFO}"
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    local durationMsg=""
-    if ((DISPLAY_DURATION == 1)); then
-      local duration
-      local -i currentLogDate
-      currentLogDate="$(date '+%s%3N')"
-      if ((LOG_LAST_LOG_DATE_INIT == 1)); then
-        LOG_LAST_LOG_DATE_INIT=0
-        duration="Ref"
-      else
-        duration="$(((currentLogDate - FIRST_LOG_DATE) / 1000))s/+$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))s"
-      fi
-      LOG_LAST_LOG_DATE="${currentLogDate}"
-      durationMsg="$(date '+%H:%M:%S.%3N')(${duration}) - "
-    fi
-    echo -e "${__INFO_COLOR}${type}    - ${durationMsg}${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__INFO_COLOR}${type}    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logInfo "$1" "${type}"
 }
@@ -570,7 +555,8 @@ Log::displayInfo() {
 # @arg $1 message:String the message to display
 Log::displayWarning() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
-    echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__WARNING_COLOR}WARN    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logWarning "$1"
 }
@@ -578,7 +564,8 @@ Log::displayWarning() {
 # @description Display message using error color (red) and exit immediately with error status 1
 # @arg $1 message:String the message to display
 Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::computeDuration
+  echo -e "${__ERROR_COLOR}FATAL   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
 }
@@ -1082,6 +1069,38 @@ Git::pullIfNoChanges() {
   )
 }
 
+declare -g FIRST_LOG_DATE LOG_LAST_LOG_DATE LOG_LAST_LOG_DATE_INIT LOG_LAST_DURATION_STR
+FIRST_LOG_DATE="$(date '+%s%3N')"
+LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
+LOG_LAST_LOG_DATE_INIT=1
+LOG_LAST_DURATION_STR=""
+
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+Log::computeDuration() {
+  if ((DISPLAY_DURATION == 1)); then
+    local -i duration=0
+    local -i delta=0
+    local -i currentLogDate
+    currentLogDate="$(date '+%s%3N')"
+    if ((LOG_LAST_LOG_DATE_INIT == 1)); then
+      LOG_LAST_LOG_DATE_INIT=0
+      LOG_LAST_DURATION_STR="Ref"
+    else
+      duration=$(((currentLogDate - FIRST_LOG_DATE) / 1000))
+      delta=$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))
+      LOG_LAST_DURATION_STR="${duration}s/+${delta}s"
+    fi
+    LOG_LAST_LOG_DATE="${currentLogDate}"
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR="$(date '+%H:%M:%S.%3N')(${LOG_LAST_DURATION_STR}) - "
+  else
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR=""
+  fi
+}
+
 # @description log message to file
 # @arg $1 message:String the message to display
 Log::logDebug() {
@@ -1415,7 +1434,8 @@ Linux::Wsl::cachedWslvar() {
 # @arg $1 message:String the message to display
 Log::displaySkipped() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
 }
@@ -1585,7 +1605,8 @@ Linux::Wsl::originalWslvar() {
 # @arg $1 message:String the message to display
 Log::displaySuccess() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSuccess "$1"
 }
@@ -1770,6 +1791,7 @@ FRAMEWORK_VENDOR_BIN_DIR="${FRAMEWORK_ROOT_DIR}/vendor/bin"
 if [[ -f "${HOME}/.bash-tools/.env" ]]; then
   export BASH_FRAMEWORK_ENV_FILES=("${HOME}/.bash-tools/.env")
 fi
+
 # REQUIRES
 Env::requireLoad
 UI::requireTheme
diff --git a/install b/install
--- a/install
+++ b/install
@@ -404,7 +404,7 @@ EOF
 # @description load .env file
 # @arg $1 envFile:String the file to load
 Engine::Config::loadConfig() {
-  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-}" = "1" ]]; then
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
     return 0
   fi
   local envFile="${BASH_DEV_ENV_ROOT_DIR}/.env"
@@ -515,7 +515,8 @@ export __VERBOSE_LEVEL_TRACE=3
 # @arg $1 message:String the message to display
 Log::displayDebug() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_DEBUG)); then
-    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logDebug "$1"
 }
@@ -524,14 +525,11 @@ Log::displayDebug() {
 # @arg $1 message:String the message to display
 Log::displayError() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_ERROR)); then
-    echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__ERROR_COLOR}ERROR   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logError "$1"
 }
-
-FIRST_LOG_DATE="$(date '+%s%3N')"
-LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
-LOG_LAST_LOG_DATE_INIT=1
 
 # @description Display message using info color (bg light blue/fg white)
 # @arg $1 message:String the message to display
@@ -539,21 +537,8 @@ LOG_LAST_LOG_DATE_INIT=1
 Log::displayInfo() {
   local type="${2:-INFO}"
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    local durationMsg=""
-    if ((DISPLAY_DURATION == 1)); then
-      local duration
-      local -i currentLogDate
-      currentLogDate="$(date '+%s%3N')"
-      if ((LOG_LAST_LOG_DATE_INIT == 1)); then
-        LOG_LAST_LOG_DATE_INIT=0
-        duration="Ref"
-      else
-        duration="$(((currentLogDate - FIRST_LOG_DATE) / 1000))s/+$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))s"
-      fi
-      LOG_LAST_LOG_DATE="${currentLogDate}"
-      durationMsg="$(date '+%H:%M:%S.%3N')(${duration}) - "
-    fi
-    echo -e "${__INFO_COLOR}${type}    - ${durationMsg}${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__INFO_COLOR}${type}    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logInfo "$1" "${type}"
 }
@@ -562,7 +547,8 @@ Log::displayInfo() {
 # @arg $1 message:String the message to display
 Log::displaySuccess() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSuccess "$1"
 }
@@ -571,7 +557,8 @@ Log::displaySuccess() {
 # @arg $1 message:String the message to display
 Log::displayWarning() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
-    echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__WARNING_COLOR}WARN    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logWarning "$1"
 }
@@ -579,7 +566,8 @@ Log::displayWarning() {
 # @description Display message using error color (red) and exit immediately with error status 1
 # @arg $1 message:String the message to display
 Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::computeDuration
+  echo -e "${__ERROR_COLOR}FATAL   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
 }
@@ -587,10 +575,16 @@ Log::fatal() {
 # @description Display given text on full line with TEST_COLOR style
 # @arg $1 text:String text to display
 Log::headLine() {
-  local text="$1"
-  local message
-  message="$(UI::textLine "${text}" " ")"
-  echo -e "${__TEST_COLOR}${message}${__RESET_COLOR}"
+  local type="$1"
+  local text="$2"
+  local message="${type}   - ${text}"
+  if [[ -z "${type}" ]]; then
+    message="${text}"
+  else
+    Log::computeDuration
+    message="$(printf '%-7s - %s%s' "${type}" "${LOG_LAST_DURATION_STR}" "${text}")"
+  fi
+  echo -e "${__TEST_COLOR}$(UI::textLine "${message}" " ")${__RESET_COLOR}" >&2
 }
 
 # @description activate or not Log::display* and Log::log* functions
@@ -709,7 +703,7 @@ Profiles::allDepsRecursive() {
       return 1
     fi
 
-    if ! readarray -t newDeps < <("${scriptsDir}/${i}" dependencies); then
+    if ! readarray -t newDeps < <(SKIP_REQUIRES=1 "${scriptsDir}/${i}" dependencies); then
       Log::displayError "Dependency ${i} - ${scriptsDir}/${i} dependencies failure"
       return 3
     fi
@@ -1407,11 +1401,44 @@ Env::pathPrepend() {
   done
 }
 
+declare -g FIRST_LOG_DATE LOG_LAST_LOG_DATE LOG_LAST_LOG_DATE_INIT LOG_LAST_DURATION_STR
+FIRST_LOG_DATE="$(date '+%s%3N')"
+LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
+LOG_LAST_LOG_DATE_INIT=1
+LOG_LAST_DURATION_STR=""
+
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+Log::computeDuration() {
+  if ((DISPLAY_DURATION == 1)); then
+    local -i duration=0
+    local -i delta=0
+    local -i currentLogDate
+    currentLogDate="$(date '+%s%3N')"
+    if ((LOG_LAST_LOG_DATE_INIT == 1)); then
+      LOG_LAST_LOG_DATE_INIT=0
+      LOG_LAST_DURATION_STR="Ref"
+    else
+      duration=$(((currentLogDate - FIRST_LOG_DATE) / 1000))
+      delta=$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))
+      LOG_LAST_DURATION_STR="${duration}s/+${delta}s"
+    fi
+    LOG_LAST_LOG_DATE="${currentLogDate}"
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR="$(date '+%H:%M:%S.%3N')(${LOG_LAST_DURATION_STR}) - "
+  else
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR=""
+  fi
+}
+
 # @description Display message using skip color (yellow)
 # @arg $1 message:String the message to display
 Log::displaySkipped() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
 }
@@ -2032,6 +2059,7 @@ Retry::parameterized() {
 # FUNCTIONS
 
 facade_main_installsh() {
+
 # REQUIRES
 Env::requireLoad
 UI::requireTheme
@@ -3788,11 +3816,11 @@ summary() {
     return 0
   fi
   UI::drawLine '-'
-  Log::headLine "Important messages recapitulative"
+  Log::headLine "" "Important messages recapitulative"
   Stats::logRecapitulative "${LOGS_DIR}/automatic-upgrade"
 
   UI::drawLine '-'
-  Log::headLine "Summary"
+  Log::headLine "" "Summary"
   if [[ "${SKIP_INSTALL}" = "0" ]]; then
     Stats::aggregateStatsSummary "installation(s)" "${LOGS_DIR:-#}/install.stat"
   fi
diff --git a/installScripts/BashTools b/installScripts/BashTools
--- a/installScripts/BashTools
+++ b/installScripts/BashTools
@@ -474,7 +474,7 @@ EOF
 # @description load .env file
 # @arg $1 envFile:String the file to load
 Engine::Config::loadConfig() {
-  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-}" = "1" ]]; then
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
     return 0
   fi
   local envFile="${BASH_DEV_ENV_ROOT_DIR}/.env"
@@ -649,7 +649,7 @@ InstallScripts::command() {
   }
   local hook
   if [[ "${SKIP_INSTALL}" = "0" ]] && ! InstallScripts::scriptFunctionEmpty install; then
-    Log::headLine "INSTALL - Installing ${scriptName}"
+    Log::headLine "INSTALL" "Installing ${scriptName}"
     logFile="${logsDir}/${scriptName}-install.log"
     statsFile="${logsDir}/${scriptName}-install.stat"
 
@@ -669,7 +669,7 @@ InstallScripts::command() {
   local testInstallStatus="0"
   if [[ "${SKIP_TEST}" = "0" && "${installStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty testInstall; then
-    Log::headLine "TEST    - Testing ${scriptName} installation"
+    Log::headLine "TEST" "Testing ${scriptName} installation"
     logFile="${logsDir}/${scriptName}-test-install.log"
     statsFile="${logsDir}/${scriptName}-test-install.stat"
     (
@@ -691,7 +691,7 @@ InstallScripts::command() {
   local configStatus="0"
   if [[ "${SKIP_CONFIGURE}" = "0" && "${installStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty configure; then
-    Log::headLine "CONFIG  - Configuring ${scriptName}"
+    Log::headLine "CONFIG" "Configuring ${scriptName}"
     logFile="${logsDir}/${scriptName}-config.log"
     statsFile="${logsDir}/${scriptName}-config.stat"
     (
@@ -714,7 +714,7 @@ InstallScripts::command() {
   local testConfigStatus="0"
   if [[ "${SKIP_TEST}" = "0" && "${installStatus}" = "0" && "${configStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty configure; then
-    Log::headLine "TEST    - Testing ${scriptName} configuration"
+    Log::headLine "TEST" "Testing ${scriptName} configuration"
     logFile="${logsDir}/${scriptName}-test-configuration.log"
     statsFile="${logsDir}/${scriptName}-test-configuration.stat"
     (
@@ -768,7 +768,8 @@ export __VERBOSE_LEVEL_TRACE=3
 # @arg $1 message:String the message to display
 Log::displayDebug() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_DEBUG)); then
-    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logDebug "$1"
 }
@@ -777,14 +778,11 @@ Log::displayDebug() {
 # @arg $1 message:String the message to display
 Log::displayError() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_ERROR)); then
-    echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__ERROR_COLOR}ERROR   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logError "$1"
 }
-
-FIRST_LOG_DATE="$(date '+%s%3N')"
-LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
-LOG_LAST_LOG_DATE_INIT=1
 
 # @description Display message using info color (bg light blue/fg white)
 # @arg $1 message:String the message to display
@@ -792,21 +790,8 @@ LOG_LAST_LOG_DATE_INIT=1
 Log::displayInfo() {
   local type="${2:-INFO}"
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    local durationMsg=""
-    if ((DISPLAY_DURATION == 1)); then
-      local duration
-      local -i currentLogDate
-      currentLogDate="$(date '+%s%3N')"
-      if ((LOG_LAST_LOG_DATE_INIT == 1)); then
-        LOG_LAST_LOG_DATE_INIT=0
-        duration="Ref"
-      else
-        duration="$(((currentLogDate - FIRST_LOG_DATE) / 1000))s/+$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))s"
-      fi
-      LOG_LAST_LOG_DATE="${currentLogDate}"
-      durationMsg="$(date '+%H:%M:%S.%3N')(${duration}) - "
-    fi
-    echo -e "${__INFO_COLOR}${type}    - ${durationMsg}${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__INFO_COLOR}${type}    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logInfo "$1" "${type}"
 }
@@ -815,7 +800,8 @@ Log::displayInfo() {
 # @arg $1 message:String the message to display
 Log::displayWarning() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
-    echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__WARNING_COLOR}WARN    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logWarning "$1"
 }
@@ -823,7 +809,8 @@ Log::displayWarning() {
 # @description Display message using error color (red) and exit immediately with error status 1
 # @arg $1 message:String the message to display
 Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::computeDuration
+  echo -e "${__ERROR_COLOR}FATAL   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
 }
@@ -1422,11 +1409,44 @@ InstallScripts::scriptFunctionEmpty() {
   [[ "$(declare -f "$1" | sed '3q;d')" =~ ${pattern} && "$(declare -f "$1" | sed '4q;d')" = "}" ]]
 }
 
+declare -g FIRST_LOG_DATE LOG_LAST_LOG_DATE LOG_LAST_LOG_DATE_INIT LOG_LAST_DURATION_STR
+FIRST_LOG_DATE="$(date '+%s%3N')"
+LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
+LOG_LAST_LOG_DATE_INIT=1
+LOG_LAST_DURATION_STR=""
+
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+Log::computeDuration() {
+  if ((DISPLAY_DURATION == 1)); then
+    local -i duration=0
+    local -i delta=0
+    local -i currentLogDate
+    currentLogDate="$(date '+%s%3N')"
+    if ((LOG_LAST_LOG_DATE_INIT == 1)); then
+      LOG_LAST_LOG_DATE_INIT=0
+      LOG_LAST_DURATION_STR="Ref"
+    else
+      duration=$(((currentLogDate - FIRST_LOG_DATE) / 1000))
+      delta=$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))
+      LOG_LAST_DURATION_STR="${duration}s/+${delta}s"
+    fi
+    LOG_LAST_LOG_DATE="${currentLogDate}"
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR="$(date '+%H:%M:%S.%3N')(${LOG_LAST_DURATION_STR}) - "
+  else
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR=""
+  fi
+}
+
 # @description Display message using success color (bg green/fg white)
 # @arg $1 message:String the message to display
 Log::displaySuccess() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSuccess "$1"
 }
@@ -1434,10 +1454,16 @@ Log::displaySuccess() {
 # @description Display given text on full line with TEST_COLOR style
 # @arg $1 text:String text to display
 Log::headLine() {
-  local text="$1"
-  local message
-  message="$(UI::textLine "${text}" " ")"
-  echo -e "${__TEST_COLOR}${message}${__RESET_COLOR}"
+  local type="$1"
+  local text="$2"
+  local message="${type}   - ${text}"
+  if [[ -z "${type}" ]]; then
+    message="${text}"
+  else
+    Log::computeDuration
+    message="$(printf '%-7s - %s%s' "${type}" "${LOG_LAST_DURATION_STR}" "${text}")"
+  fi
+  echo -e "${__TEST_COLOR}$(UI::textLine "${message}" " ")${__RESET_COLOR}" >&2
 }
 
 # @description log message to file
@@ -1824,7 +1850,8 @@ Linux::Wsl::cachedWslvar() {
 # @arg $1 message:String the message to display
 Log::displaySkipped() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
 }
@@ -1902,7 +1929,7 @@ Stats::statusLine() {
   if [[ ! -f "${statFile}" ]]; then
     return 0
   fi
-
+  Log::computeDuration
   (
     # shellcheck source=src/Stats/logStats.example
     source "${statFile}" || exit 1
@@ -1912,15 +1939,15 @@ Stats::statusLine() {
     if [[ "${status}" = "0" ]]; then
       if [[ "${skipped}" = "0" ]]; then
         color="${__SUCCESS_COLOR}"
-        statusMsg="SUCCESS - ${msg} successful"
+        statusMsg="SUCCESS - ${LOG_LAST_DURATION_STR}${msg} successful"
       else
         color="${__SKIPPED_COLOR}"
-        statusMsg="SKIPPED - ${msg} skipped"
+        statusMsg="SKIPPED - ${LOG_LAST_DURATION_STR}${msg} skipped"
       fi
     elif [[ "${status}" = "-1" ]]; then
-      statusMsg="ABORTED - ${msg} not executed"
+      statusMsg="ABORTED - ${LOG_LAST_DURATION_STR}${msg} not executed"
     else
-      statusMsg="ERROR   - ${msg} in error"
+      statusMsg="ERROR   - ${LOG_LAST_DURATION_STR}${msg} in error"
     fi
     # overwrite final TEST line
     echo -e "${color}${statusMsg}${__RESET_COLOR}"
@@ -2234,11 +2261,12 @@ Retry::parameterized() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/bash_tools_conf" "H4sIAAAAAAAAA+1cbXPaSBL2Z35Fr+xL8G4ACYHYIkXqsCGJ67DxAU5qK5WihDSALkIiGsmO1/F/v+6RBBjbcZyANtmdJ5WyNC89r0+rp2eGYmln61ARtWqV/mq1qrr6N8WOVjFUtWpomqZjeK2iVnaguv2q7exEPDQDgJ0L7n4x3UPxPymKJXt0OGXWh34YRFbItzEdHj3+WlnXanL8s8Ct8S9OnPADY/MNlkEDbFQqjxh/vaYbO6BusA73Qo7/6L8RCxy2FeoLPJ7/ml6W/M8Eq+O/BeoLPJ7/5VpF8j8TrI6/bYbmyOSs7/zJivzjxtr70Pjr1dra+Fcq1Yoc/yzQbw/g3/YIGpDvtzvtwwG0moPmQbPfzu/vP8/lkkBK0uyD0kqmiPIsBzEOu81Ou3/Yzve6ZyetfP/sOE/zaOgybxJO4TdwPJt9Sl73oQSaWq4kf55Bef8ZqPtCNM06yB8f7K/KPjsZ5H/dB5ODMjBHLuNw6EdeqORe9rrHKHrsBzMzdHxvyK0pm5lFrDtWJ/f2dbvXhpCyJDENbMLz3F/d3T8cVvk/D/w5c4+dyRsWcOzTTemAB/V/TV/jf1WX/M8GCb/vIP8zOI+nAQiuxZNjOHMmgSCc5NLfAsT/o9ncD8LTwB877jaWAY+x/6vlCtl/Rs2Q9n8WuGP8fc+97HpoAU43VMaD469XxfhrZV0tl8tk/xkVXer/LLD7S2nkeCW06aY5Zk19UHyPDYXhpEgN//fHHfw3XXdz3Cc8zH/tlv+vpkn+ZwHkf8QDoQOYdw5CD+QsM5Tc/2fgDv7bbGxGbpjd91/Xl+s/cvzQ998oS/5ngTv5vwuoASBg84Bx5oUcwimDi6nvMnAdHoI/jl0rnDQFfM4BTDAxFM7h6RC7M+RP1wJdf7IeNEVBfnAZB++C6V6YlxzGjufwKYwuwRR1CH0YMeBRwEQdLH82Mz0bbJ9x8HyqYxgFHrBPToiRNoNfGqCiQKnBvhJ38N/zN2n87zzMf83Q1+1/zZDf/0xwD/8jzsaRC84YLv0ILkxPUNGOZnOg5aEgoz0CLjaNkZ2P0Rl/dZMlVlAsWa6zPdePwGP8PxWtSvu/hiHP/2SCm+M/u+Qf3WLAZn6Yof/HqFXX9/8Moyr1fxa4R//zKXNdi84Fge1w0tuN/mFZ1Sv3xmnVSg6tN9M99L3QdDwWNINJQ7E+uLwgptXvyncKPuOJzL2rKH6sx5Kvv1fyYWxWkvA8SrcWr9fKfi6HH8F376DwJ6xFwfv3z+kr56G96fqm3eIeKOniKeaQglG3SigtPG5QsEARTYDCdO/qdbc/OGket6+hEO1dnfXbPXya712dNvv9t91eC99O8a3bG1C9xs4mvqR38X+jzp+dr+A/KvuU/zql0/SKKu2/TLBt/osZ9VMwf43d38h717dM98en/QI3+b9x14/AQ/yvqbVk/VdRdc0g/hvy/Fc2uIf/83hGpG4ZmubMJrdMMkMwSbI2nJrnDGZ+vMIz3TkyH6xUBTyjR+7YLABranoTx5uIIkjSoqBzjE/lLrOC4+GKkjPw/NVAnuawN6ml9q5uBdYLnm+z71YwC9VF0jZqpyz1CWqFbx7/m/wPGBab+fe/Ulme/0MNQPwnl7DkfwbY9vdfzKhtfP+F4O1Z/kkBBWTH9ffw60fHmv3vexM/c/5X9aX/R0/5L8//ZYKt2/80o7bCf98PN0p/UVM0NVyXWXTAEa1xcoMHGhrj8cPc5BwKBTMi4z90LHEOMj0RDRScvvw8CuMm/8lI2Tj9H+Y/GvsL/tdqxH/NkPzPBNvm/ybM3rvovzTOL5B6AUOG0uKiVKJ9KrrERHvFc2ToyHGd8BIunHAKyoXj2f4Fh4kTiqYqW7Meltb5j20+FEs297Z8B/wx+z81sf5Xy+T/k/s/20c8/sJrVUQFsJUyhI/3C/c/NGP9/leZpoTU/xkgdT42tHKtqOI/LZf6HRtkYuXI79jQdfX3HHkm4zDSjHNmOWPHAn9OVhAHOwpIATviLEmudTA8Oqasw+7p4Kh70m8UCqgQzeCyMEPN/QMrxH8Y6PxP3wqc+XZ++kHgMfq/ahji/jcml/o/A6yOP/sUBqYV0iImy/NfZd1Yv/9X0apS/2eC+85/eWhp22AzyyXjutU/QetbU27HvGn3Drr9NsaWlVwa6EfhPApbToDB+h2Z0Nhw8WMRJ6gs8x00+6+HL3v4OcLvz3+Gb9onrW5veNocvMZ01WU6e4TvxvqygvtRYLFGyWbnJS9y3VwcQNt39wu+Lg1TAnQ9lq7fi7Q0+KL9v7o5yEX2UzMwZyxkAX+nvr+5S9jxJ/X6GGW7oHyMWHBJB+foa+kHILZZ6Chruq+h0BYfli3YCPOFVCD3A3ZiOA38aDKFtNpN102rzRc9JEpp3Fe3m8lOMKqhWEgEf0ZXgS/X4l9iDUmUeMHMq4H5l5EnvCW8Xp+wsDnivhuFDNeAY0oByuJ2sQKpCIrA/lFoYxjKLxbjBZ8/Q3wFSdlX0g721rOtdOtK7ffy1H4Pn2+k/1fx12sSBosOydMpxZsi99MetwJmhgxcfyJGZdELGBA3N60V5u90Xw1fdnvHzQHWqQEKprlRt1t5964WrLgu7V3Zo+thUgtqwXWRBGA+9olZYLx4ooH2AvMk2bGMXSCHdMCsECePjbJooZtEi/qnk6Be5x+c+SGOw8wj0WiajY481HIeckFdSRbPxJXI5RjTI9ZQoSEJg4h9nXAt9/X9Q82hA+AsaU3adO3FE4PaXxBt+qIsePIkZhZSc+6al0feGOcOiqV9RPPcdFwiLO0jPl125FN5q+0Glue/W9Fsvh0b8DH2X7L+w3hp/2WB9fHfxm8APbT+vz3+uqFJ/28mKJa25vZZ4CH7v1opr42/Wlbl/n8mWL3//UVf+O4u/Qf8FkOHnTNXvM0cz5lFM3ApRFzxmDJAq4CbE0Y3QNDWunDQshsJQ2iC1qvjodkiPuhHnfZCqlqHky4FizetDu1er9sTL+U6vG32To5O4ji9DkcnL7viuVKHVvvgTETk1kx8KqLTftPuNNTcopjWUf+00/zj2xqQWBnYBt8DNKsZ2jHbq39S1aQN+rINaPGQ5ScM1DQMl1PCal1UPK1zajLSssFfGLap847OUGHucOpw4GQ6z81wusgrVmyOOL0FdOcOjTTxnHTS4kzWfb1PA9yg043H7etSkSZYIfR9l5ewGlxMOLJ5ye42k1UDxJX10SpNpNMayR4lTkWgA5N0BYmvuBdbZ8en2Fm9O0u68WmjkiZmMMIOSnd5RceJnU8Y41LsYupYU5j5Njk2xeYunTebiFVBQJPBAzapg66CTYfi8r/p6j4t1EzMFToz6ia6ichDqrboaMwuunEk7GxRl0WlxO9Z5XZFZ4rENwoW8mhcmDD0Pf9ipdGvmr2D5qv28LDboV/tGbaaf/QbWJuv6czE2bNSrzuWkf3D3tHpoI9Wd6fVvrtvUeh46Tu6p2S6vrnIQivc/2FEPFkG3W7nVgFJinh6xLlIcuFbgPmab/uwXPp+s6C+PqTfRBqe9ToNrtdLJetDARethXHATXrAeVlin2hMeSk3aOOETJpVCmdzudyQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkMgA/wdi0kg3AHgAAA=="
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/bash_tools_conf" "H4sIAAAAAAAAA+1c/3PauBLPz/wVe05eS+4K2BjMGzp0jgTaZh4JeUDauel0GGML8KuxqWUnzaX539+ubAMhSdO04Gvv9Ol0YkvW6utntVpJFEs7W4eKqFWr9FerVdXVvyl2tIqhqlVD0zQdw2sVtbID1e0XbWcn4qEZAOxccPeL3z0U/5OiWLJHh1NmfeiHQWSFfBvD4dH9r5V1rSb7Pwvc6v/ixAk/MDbfYB7UwUal8oj+12u6sQPqBstwL2T/j/4bscBhW6G+wOP5r+llyf9MsNr/W6C+wOP5X65VJP8zwWr/22ZojkzO+s6frMg/bqy+D/W/Xq2t9X+lUq3I/s8C/fYAfrdH0IB8v91pHw6g1Rw0D5r9dn5//3kulwTSJ80+KK1kiCjPchDjsNvstPuH7Xyve3bSyvfPjvM0joYu8ybhFH4Dx7PZp+R1H0qgqeVK8ucZlPefgbovRNOog/zxwf6q7LOTQf7XfTA5KANz5DIOh37khUruZa97jKLHfjAzQ8f3htyasplZxLJjcXJvX7d7bQgpSRLTwCo8z/3Vzf3DYZX/88CfM/fYmbxhAcc23ZQOeFD/1/Q1/ld1yf9skPD7DvI/g/N4GIDgWjw4hjNnEgjCSS79LUD8P5rN/SA8Dfyx425jGfAY+79arpD9Z9QMaf9ngTv63/fcy66HFuB0Q3k82P96VfS/VtbVcrlM9p9R0aX+zwK7v5RGjldCm26aY9bUB8X32FAYTorU8H9/3MF/03U3x33Cw/zXbvn/aprkfxZA/kc8EDqAeecg9EDOMkPJ/X8G7uC/zcZm5IbZzf+6vlz/keOH5n+jLPmfBe7k/y6gBoCAzQPGmRdyCKcMLqa+y8B1eAj+OHatcNIU8DkHMMGPoXAOT4fYnCF/uhbo+pP1oCkK8oPLOHgXTPfCvOQwdjyHT2F0CaYoQ+jDiAGPAibKYPmzmenZYPuMg+dTGcMo8IB9ckKMtBn80gAVBUoN9pW4g/+ev0njf+dh/muGvm7/a4ac/zPBPfyPOBtHLjhjuPQjuDA9QUU7ms2BloeCjPYIuNg0RnY+Rmf81VWWWEGxZLnO9lw/Ao/x/1S0Ku3/GoY8/5MJbvb/7JJ/dIsBm/lhhv4fw6gl+t/Q0RiM7b+a1P9Z4B79z6fMdS06FwS2w0lvN/qHZVWv3BunVSs5tN5M99D3QtPxWNAMJg1FjCjlO0We8UTa3lUUP9YLQvD190o+jA1KEp5H6dbi9VrZz+Vw+nv3Dgp/wloUvH//nOY3Dy1N1zftFvdASZdNMXsUjLqVQ2nha4OCBXHbQGG6d/W62x+cNI/b11CI9q7O+u0ePs33rk6b/f7bbq+Fb6f41u0NqFxjZ3Nz6F3836jzZ+dr+F9Z6H+dvtP0iirtv0wg+Z+yc43j38h+17dM92ch/846/zfu+hF4iP81NZ3/K6quGcR/Q57/ygb38H8ej4jULUPDnNnklklGCH6SrA2n5jmDmR+v8Ex3jswHK1UBz+iROzYLwJqa3sTxJiILkrTI6BzjU7nLpOB4uKLkDDx/NZCnKexNaqm9q1uB9YLn2+y7FcxCdZG0jVorS32CWuGb+/8m/wOG2WY+/1cqy/N/qAGI/+QSlvzPANue/8WI2sb8LwRvz/5PMiggO66/h18/Otbsf9+b+Jnzv6ov/T96yn95/i8TbN3+pxG1Ff77frhR+ouSoqnhusyiA45ojZMbPNDQGI8f5ibnUCiYERn/oWOJc5DpiWig4PTl51EYN/lPRsrG6f8w/9HYX/C/ViP+a4bkfybYNv83YfbeRf+lcX6B1AsYMpQWF6US7VPRJSbaK54jQ0eO64SXcOGEU1AuHM/2LzhMnFBUVdma9bC0zn9s86FYsrm35Tvgj9n/qYn1v1om/5/c/9k+4v4XXqsiKoCt5CF8vF+4/6EZ6/e/yjQkpP7PAKnzsaGVa0UV/2m51O/YIBMrR37Hhq6r/86RZzIOI804Z5Yzdizw52QFcbCjgBSwI86S5FoHw6NjSjrsng6Ouif9RqGACtEMLgsz1Nw/sEL8h4HO//StwJlv56cfBB6j/6uGIe5/4+dS/2eA1f5nn8LAtEJaxGR5/qusG+v3/ypaVer/THDf+S8PLW0bbGa5ZFy3+idofWvK7Zg37d5Bt9/G2LKSSwP9KJxHYcsJMFi/IxEaGy5OFvEHlWW6g2b/9fBlD6cjnH/+M3zTPml1e8PT5uA1flddfmeP8N1YX1ZwPwos1ijZ7LzkRa6biwNo++5+wdelYUqArsfS9XuRlgZftP9XNwe5SH5qBuaMhSzg79T3N3cJO/6kXh+jbBeUjxELLungHM2WfgBim4WOsqb7Ggpt8WHego0wX0gFcj9gI4bTwI8mU0iL3XTdtNh80UIil8Z9Zbv52QlGNRQLieDP6Crw5Vr8SywhiRIvmHg1MP8y8oS3hNfrExY2R9x3o5DhGnBMX4CyuF2sQCqCIrB9FNoYhvKLRX/B588QX0FS9pW0gb31ZCvNulL6vTzV38PnG9//q/jrNQmDRYPk6ZTiTZH7aYtbATNDBq4/Eb2yaAUMiKublgrTd7qvhi+7vePmAMvUAAW/uVG2W2n3rhasuC7tXdmj62FSCqrBdZEEYDr2iVlgvHiigfYC0yTJMY9dIId0wKwQB4+Nsmihm0SL8qeDoF7nH5z5IfbDzCPRaJqNjjzUch5yQV35LB6JK5HLPqZHLKFCXRIGEfs64Vru69uHqkMHwFlSm7Tq2osnBtW/IOr0RVnw5EnMLKTm3DUvj7wxjh0US/uI5rnpuERY2kd8umzIp/JW2w0sz3+3otl8OzbgY+y/ZP2H8dL+ywLr/b+N3wB6aP1/u/91Q5P+30xQLG3N7bPAQ/Z/tVJe63+1rMr9/0ywev/7i77w3V36DzgXQ4edM1e8zRzPmUUzcClEXPGYMkCrgJsTRjdA0Na6cNCyGwlDaILWq+Oh2SIm9KNOeyFVrcNJl4LFm1aHdq/X7YmXch3eNnsnRydxnF6Ho5OXXfFcqUOrfXAmInJrJj5l0Wm/aXcaam6RTeuof9pp/vFtFUisDKyD7wGa1QztmO2VPylqUgd9WQe0eMjyEwZqGobLKWG1Lgqeljk1GWnZ4C8M29R5R2eoMHU4dThwMp3nZjhdpBUrNkec3gK6c4dGmnhOGmlxJuu+1qcObtDpxuP2dalIA6wQ+r7LS1gMLgYc2bxkd5vJqgHiwvpolSbSaY1kjxKnItCBSbqCxFfci62z41NsrN6dOd2Y2iiniRmMsIHSXV7RcGLnE8a4FLuYOtYUZr5Njk2xuUvnzSZiVRDQYPCATeqgq2DTobj8b7q6Tws1E1OFzoyaiW4i8pCKLRoak4tmHAk7W5RlUSjxe1a5XdGY4uMbGQt51C9MGPqef7FS6VfN3kHzVXt42O3Qr/YMW80/+g0szdc0ZuLsWSnXHcvI/mHv6HTQR6u702rf3bYodLz0Hd2TM13fXCShFe7/MCIeLINut3Mrg+SLeHjEqUhy4VuA6Zpv+7Bc+n6zoL4+pN9EGp71Og2u10sl60MBF62FccBNesBxWWKfqE95KTdo44BMqlUKZ3O53JCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQyAD/BzUTXlgAeAAA"
 
 declare -gx embed_dir_bash_tools_conf="${TMPDIR:-/tmp}/bash_tools_conf"
 
 facade_main_BashToolssh() {
+
 # REQUIRES
 Linux::requireTarCommand
 Env::requireLoad
diff --git a/installScripts/Docker b/installScripts/Docker
--- a/installScripts/Docker
+++ b/installScripts/Docker
@@ -368,7 +368,7 @@ EOF
 # @description load .env file
 # @arg $1 envFile:String the file to load
 Engine::Config::loadConfig() {
-  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-}" = "1" ]]; then
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
     return 0
   fi
   local envFile="${BASH_DEV_ENV_ROOT_DIR}/.env"
@@ -445,61 +445,6 @@ Framework::createTempFile() {
   mktemp -p "${TMPDIR:-/tmp}" -t "${1:-}.XXXXXXXXXXXX"
 }
 
-# @description upgrade given binary to latest github release using retry
-#
-# releaseUrl argument : the placeholder @latestVersion@ will be replaced by the latest release version
-# @arg $1 targetFile:String target binary file (eg: /usr/local/bin/kind)
-# @arg $2 releaseUrl:String github release url (eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64)
-# @arg $3 argVersion:String parameter to add to existing command to compute current version
-# @arg $4 versionCallback:Function function called to get software version (default: Version::getCommandVersionFromPlainText will call software with argument --version)
-# @arg $5 installCallback:Function function called to install the file retrieved on github (default copy as is and set execution bit)
-# @arg $6 parseVersionCallback:Function function to call to filter the version retrieved (Eg: Version::parse)
-# @stdout log messages about retry, install, upgrade
-Github::upgradeRelease() {
-  local targetFile="$1"
-  local releaseUrl="$2"
-  local argVersion="${3:---version}"
-  local versionCallback="${4:-Version::getCommandVersionFromPlainText}"
-  # shellcheck disable=SC2034
-  local installCallback="${5:-}"
-  local parseVersionCallback="${6:-}"
-  local latestVersion
-  local repo
-
-  repo="$(Github::extractRepoFromGithubUrl "${releaseUrl}")"
-  Github::getLatestRelease "${repo}" latestVersion ||
-    Log::fatal "Repo ${repo} latest version not found"
-  if [[ "$(type -t "${parseVersionCallback}")" = "function" ]]; then
-    latestVersion="$(${parseVersionCallback} <<<"${latestVersion}")"
-  fi
-  Log::displayInfo "Repo ${repo} latest version found is ${latestVersion}"
-
-  local currentVersion="not existing"
-  if [[ -f "${targetFile}" ]]; then
-    currentVersion="$(${versionCallback} "${targetFile}" "${argVersion}" 2>&1 || true)"
-  fi
-  if [[ "${currentVersion}" = "${latestVersion}" ]]; then
-    Log::displayInfo "${targetFile} version ${latestVersion} already installed"
-  else
-    if [[ -z "${currentVersion}" ]]; then
-      Log::displayInfo "Installing ${targetFile} with version ${latestVersion}"
-    else
-      Log::displayInfo "Upgrading ${targetFile} from version ${currentVersion} to ${latestVersion}"
-    fi
-    local url
-    url="$(echo "${releaseUrl}" | sed -E "s/@latestVersion@/${latestVersion}/g")"
-    Log::displayInfo "Using url ${url}"
-    newSoftware=$(mktemp -p "${TMPDIR:-/tmp}" -t github.newSoftware.XXXX)
-    Retry::default curl \
-      -L \
-      -o "${newSoftware}" \
-      --fail \
-      "${url}"
-
-    Github::defaultInstall "${newSoftware}" "${targetFile}" "${latestVersion}" "${installCallback}"
-  fi
-}
-
 # @description the command launch different actions(install, configure, test)
 # depending on the options selected
 # @see src/_includes/install.skip.options.tpl
@@ -532,7 +477,7 @@ InstallScripts::command() {
   }
   local hook
   if [[ "${SKIP_INSTALL}" = "0" ]] && ! InstallScripts::scriptFunctionEmpty install; then
-    Log::headLine "INSTALL - Installing ${scriptName}"
+    Log::headLine "INSTALL" "Installing ${scriptName}"
     logFile="${logsDir}/${scriptName}-install.log"
     statsFile="${logsDir}/${scriptName}-install.stat"
 
@@ -552,7 +497,7 @@ InstallScripts::command() {
   local testInstallStatus="0"
   if [[ "${SKIP_TEST}" = "0" && "${installStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty testInstall; then
-    Log::headLine "TEST    - Testing ${scriptName} installation"
+    Log::headLine "TEST" "Testing ${scriptName} installation"
     logFile="${logsDir}/${scriptName}-test-install.log"
     statsFile="${logsDir}/${scriptName}-test-install.stat"
     (
@@ -574,7 +519,7 @@ InstallScripts::command() {
   local configStatus="0"
   if [[ "${SKIP_CONFIGURE}" = "0" && "${installStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty configure; then
-    Log::headLine "CONFIG  - Configuring ${scriptName}"
+    Log::headLine "CONFIG" "Configuring ${scriptName}"
     logFile="${logsDir}/${scriptName}-config.log"
     statsFile="${logsDir}/${scriptName}-config.stat"
     (
@@ -597,7 +542,7 @@ InstallScripts::command() {
   local testConfigStatus="0"
   if [[ "${SKIP_TEST}" = "0" && "${installStatus}" = "0" && "${configStatus}" = "0" ]] &&
     ! InstallScripts::scriptFunctionEmpty configure; then
-    Log::headLine "TEST    - Testing ${scriptName} configuration"
+    Log::headLine "TEST" "Testing ${scriptName} configuration"
     logFile="${logsDir}/${scriptName}-test-configuration.log"
     statsFile="${logsDir}/${scriptName}-test-configuration.stat"
     (
@@ -685,7 +630,8 @@ export __VERBOSE_LEVEL_TRACE=3
 # @arg $1 message:String the message to display
 Log::displayDebug() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_DEBUG)); then
-    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logDebug "$1"
 }
@@ -694,14 +640,11 @@ Log::displayDebug() {
 # @arg $1 message:String the message to display
 Log::displayError() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_ERROR)); then
-    echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__ERROR_COLOR}ERROR   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logError "$1"
 }
-
-FIRST_LOG_DATE="$(date '+%s%3N')"
-LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
-LOG_LAST_LOG_DATE_INIT=1
 
 # @description Display message using info color (bg light blue/fg white)
 # @arg $1 message:String the message to display
@@ -709,21 +652,8 @@ LOG_LAST_LOG_DATE_INIT=1
 Log::displayInfo() {
   local type="${2:-INFO}"
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    local durationMsg=""
-    if ((DISPLAY_DURATION == 1)); then
-      local duration
-      local -i currentLogDate
-      currentLogDate="$(date '+%s%3N')"
-      if ((LOG_LAST_LOG_DATE_INIT == 1)); then
-        LOG_LAST_LOG_DATE_INIT=0
-        duration="Ref"
-      else
-        duration="$(((currentLogDate - FIRST_LOG_DATE) / 1000))s/+$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))s"
-      fi
-      LOG_LAST_LOG_DATE="${currentLogDate}"
-      durationMsg="$(date '+%H:%M:%S.%3N')(${duration}) - "
-    fi
-    echo -e "${__INFO_COLOR}${type}    - ${durationMsg}${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__INFO_COLOR}${type}    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logInfo "$1" "${type}"
 }
@@ -732,7 +662,8 @@ Log::displayInfo() {
 # @arg $1 message:String the message to display
 Log::displaySuccess() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSuccess "$1"
 }
@@ -741,7 +672,8 @@ Log::displaySuccess() {
 # @arg $1 message:String the message to display
 Log::displayWarning() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
-    echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__WARNING_COLOR}WARN    - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logWarning "$1"
 }
@@ -749,7 +681,8 @@ Log::displayWarning() {
 # @description Display message using error color (red) and exit immediately with error status 1
 # @arg $1 message:String the message to display
 Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::computeDuration
+  echo -e "${__ERROR_COLOR}FATAL   - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   Log::logFatal "$1"
   exit 1
 }
@@ -934,16 +867,6 @@ Version::checkMinimal() {
     return 0
   }
 
-}
-
-# @description extract software version number
-# @arg $1 command:String the command that will be called with --version parameter
-# @arg $2 argVersion:String  allows to override default --version parameter
-Version::getCommandVersionFromPlainText() {
-  local command="$1"
-  local argVersion="${2:---version}"
-  "${command}" "${argVersion}" 2>&1 |
-    Version::parse # keep only version numbers
 }
 
 # @description ensure COMMAND_BIN_DIR env var is set
@@ -1352,84 +1275,6 @@ Env::pathPrepend() {
   done
 }
 
-# @description intermediate callback that is used by Github::upgradeRelease
-# or Github::installRelease
-# if installCallback is not set, it allows to:
-#   - copy the downloaded file to the right target file
-#   - and set the execution bit
-# else
-#   installCallback is called with newSoftware, targetFile, version arguments
-# fi
-# @warning do not use this function as callback for Github::upgradeRelease or Github::installRelease, as it would result to an infinite loop
-# @arg $1 newSoftware:String the downloaded software file
-# @arg $2 targetFile:String where we want to copy the file
-# @arg $3 version:String the version that has been downloaded
-# @arg $4 installCallback:Function (optional) the callback to call with 3 first arguments
-# @env SUDO String allows to use custom sudo prefix command
-# @exitcode * on failure
-# @see Github::upgradeRelease
-# @see Github::installRelease
-# @internal
-Github::defaultInstall() {
-  local newSoftware="$1"
-  local targetFile="$2"
-  local version="$3"
-  local installCallback=$4
-  # shellcheck disable=SC2086
-  ${SUDO:-} mkdir -p "$(dirname "${targetFile}")"
-  if [[ "$(type -t "${installCallback}")" = "function" ]]; then
-    ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
-  else
-    ${SUDO:-} mv "${newSoftware}" "${targetFile}"
-    ${SUDO:-} chmod +x "${targetFile}"
-    hash -r
-    ${SUDO:-} rm -f "${newSoftware}" || true
-  fi
-}
-
-# @description github repository eg: kubernetes-sigs/kind
-# @arg $1 githubUrl:String eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64
-# @exitcode 1 if no matching repo found in provided url, 0 otherwise
-# @stdout the repo in the form owner/repo
-Github::extractRepoFromGithubUrl() {
-  local githubUrl="$1"
-  local result
-  result="$(sed -n -E 's#^https://github.com/([^/]+/[^/]+)/.*$#\1#p' <<<"${githubUrl}")"
-  if [[ -z "${result}" ]]; then
-    return 1
-  fi
-  echo "${result}"
-}
-
-# @description Retrieve the latest version number of a github release using Github API using retry
-# repo arg with fchastanet/bash-tools value would match https://github.com/fchastanet/bash-tools
-# @arg $1 repo:String repository in the format fchastanet/bash-tools
-# @arg $2 resultRef:&String reference to a variable that will contain the result of the command
-# @stdout log messages about retry
-Github::getLatestRelease() {
-  local repo="$1"
-  # we need to pass the result through a reference instead of output directly
-  # because retry can output too
-  local -n resultRef=$2
-  resultRef=""
-  local resultFile
-  resultFile="$(mktemp -p "${TMPDIR:-/tmp}" -t githubLatestRelease.XXXX)"
-  # Get latest release from GitHub api
-  if Retry::default curl \
-    -L \
-    -o "${resultFile}" \
-    --fail \
-    --silent \
-    "https://api.github.com/repos/${repo}/releases/latest"; then
-    # shellcheck disable=SC2034
-    resultRef="$(Version::githubApiExtractVersion <"${resultFile}")"
-    return 0
-  fi
-  # display curl result in case of failure
-  cat >&2 "${resultFile}"
-  rm -f "${resultFile}"
-}
-
 # @description check if function is empty
 # @arg $1 function:Function
 # @exitcode 0 if function is considered empty (body with : or true)
@@ -1438,13 +1283,51 @@ InstallScripts::scriptFunctionEmpty() {
   [[ "$(declare -f "$1" | sed '3q;d')" =~ ${pattern} && "$(declare -f "$1" | sed '4q;d')" = "}" ]]
 }
 
+declare -g FIRST_LOG_DATE LOG_LAST_LOG_DATE LOG_LAST_LOG_DATE_INIT LOG_LAST_DURATION_STR
+FIRST_LOG_DATE="$(date '+%s%3N')"
+LOG_LAST_LOG_DATE="${FIRST_LOG_DATE}"
+LOG_LAST_LOG_DATE_INIT=1
+LOG_LAST_DURATION_STR=""
+
+# @description Display message using info color (bg light blue/fg white)
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+Log::computeDuration() {
+  if ((DISPLAY_DURATION == 1)); then
+    local -i duration=0
+    local -i delta=0
+    local -i currentLogDate
+    currentLogDate="$(date '+%s%3N')"
+    if ((LOG_LAST_LOG_DATE_INIT == 1)); then
+      LOG_LAST_LOG_DATE_INIT=0
+      LOG_LAST_DURATION_STR="Ref"
+    else
+      duration=$(((currentLogDate - FIRST_LOG_DATE) / 1000))
+      delta=$(((currentLogDate - LOG_LAST_LOG_DATE) / 1000))
+      LOG_LAST_DURATION_STR="${duration}s/+${delta}s"
+    fi
+    LOG_LAST_LOG_DATE="${currentLogDate}"
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR="$(date '+%H:%M:%S.%3N')(${LOG_LAST_DURATION_STR}) - "
+  else
+    # shellcheck disable=SC2034
+    LOG_LAST_DURATION_STR=""
+  fi
+}
+
 # @description Display given text on full line with TEST_COLOR style
 # @arg $1 text:String text to display
 Log::headLine() {
-  local text="$1"
-  local message
-  message="$(UI::textLine "${text}" " ")"
-  echo -e "${__TEST_COLOR}${message}${__RESET_COLOR}"
+  local type="$1"
+  local text="$2"
+  local message="${type}   - ${text}"
+  if [[ -z "${type}" ]]; then
+    message="${text}"
+  else
+    Log::computeDuration
+    message="$(printf '%-7s - %s%s' "${type}" "${LOG_LAST_DURATION_STR}" "${text}")"
+  fi
+  echo -e "${__TEST_COLOR}$(UI::textLine "${message}" " ")${__RESET_COLOR}" >&2
 }
 
 # @description log message to file
@@ -1854,7 +1737,8 @@ Linux::getDistributorId() {
 # @arg $1 message:String the message to display
 Log::displaySkipped() {
   if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${1}${__RESET_COLOR}" >&2
+    Log::computeDuration
+    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
 }
@@ -1924,7 +1808,7 @@ Stats::statusLine() {
   if [[ ! -f "${statFile}" ]]; then
     return 0
   fi
-
+  Log::computeDuration
   (
     # shellcheck source=src/Stats/logStats.example
     source "${statFile}" || exit 1
@@ -1934,15 +1818,15 @@ Stats::statusLine() {
     if [[ "${status}" = "0" ]]; then
       if [[ "${skipped}" = "0" ]]; then
         color="${__SUCCESS_COLOR}"
-        statusMsg="SUCCESS - ${msg} successful"
+        statusMsg="SUCCESS - ${LOG_LAST_DURATION_STR}${msg} successful"
       else
         color="${__SKIPPED_COLOR}"
-        statusMsg="SKIPPED - ${msg} skipped"
+        statusMsg="SKIPPED - ${LOG_LAST_DURATION_STR}${msg} skipped"
       fi
     elif [[ "${status}" = "-1" ]]; then
-      statusMsg="ABORTED - ${msg} not executed"
+      statusMsg="ABORTED - ${LOG_LAST_DURATION_STR}${msg} not executed"
     else
-      statusMsg="ERROR   - ${msg} in error"
+      statusMsg="ERROR   - ${LOG_LAST_DURATION_STR}${msg} in error"
     fi
     # overwrite final TEST line
     echo -e "${color}${statusMsg}${__RESET_COLOR}"
@@ -1960,16 +1844,6 @@ UI::textLine() {
   ((remainingWidth = $((fullWith - textSize))))
   echo -n "${text}"
   printf '%*s\n' "${remainingWidth}" '' | tr ' ' "${character}"
-}
-
-# @description extract version number from github api
-# @noargs
-# @stdin json result of github API
-# @exitcode 1 if jq or Version::parse fails
-# @stdout the version parsed
-# @require Linux::requireJqCommand
-Version::githubApiExtractVersion() {
-  jq -r ".tag_name"
 }
 
 # @description check if argument respects this framework variable naming convention
@@ -2126,13 +2000,6 @@ Linux::Wsl::requireWsl() {
   fi
 }
 
-# @description ensure command jq is available
-# @exitcode 1 if jq command not available
-# @stderr diagnostics information is displayed
-Linux::requireJqCommand() {
-  Assert::commandExists jq
-}
-
 # @description delete files older than n days in given path
 # @warning use this function with caution as it will delete all files in given path without any prompt
 # @arg $1 path:String the directory in which files will be deleted or the file to delete
@@ -2206,13 +2073,13 @@ Linux::Wsl::originalWslpath() {
 # FUNCTIONS
 
 facade_main_Dockersh() {
+
 # REQUIRES
 Linux::requireUbuntu
 Env::requireLoad
 UI::requireTheme
 Log::requireLoad
 Linux::Wsl::requireWsl
-Linux::requireJqCommand
 Compiler::Facade::requireCommandBinDir
 
 if Assert::functionExists initFacade; then
@@ -2992,6 +2859,7 @@ helpDescription() {
 dependencies() {
   echo "MandatorySoftwares"
   echo "WslConfig"
+  echo "DockerCompose"
 }
 
 # jscpd:ignore-start
@@ -3035,22 +2903,6 @@ install() {
     containerd.io \
     docker-ce \
     docker-ce-cli
-
-  Log::displayInfo "Installing docker-compose"
-  # shellcheck disable=SC2317
-  dockerComposeVersionCallback() {
-    echo "v$(Version::getCommandVersionFromPlainText "$@")"
-  }
-  export -f dockerComposeVersionCallback
-  # shellcheck disable=SC2154
-  SUDO=sudo Github::upgradeRelease \
-    /usr/local/bin/docker-compose \
-    "https://github.com/docker/compose/releases/download/@latestVersion@/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" \
-    "--version" \
-    dockerComposeVersionCallback
-
-  sudo rm -f /usr/bin/docker-compose || true
-  sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
 }
 
 testInstall() {
@@ -3065,7 +2917,6 @@ testInstall() {
   fi
 
   Version::checkMinimal "docker" --version "25.0.3" || ((++failures))
-  Version::checkMinimal "docker-compose" --version "2.23.1" || ((++failures))
 
   Log::displayInfo "docker executable path $(command -v docker || true)"
   Log::displayInfo "docker version $(docker --version || true)"
