stabilized

diff --git a/distro b/distro
--- a/distro
+++ b/distro
@@ -293,8 +293,8 @@ UPGRADE_UBUNTU_VERSION=0
 AWS_AUTHENTICATOR="Saml2Aws"
 
 # Choose your preferred shell
-# possible choices: BashProfile (Legacy experience), ZshProfile (Recommended experience)
-PREFERRED_SHELL="BashProfile"
+# possible choices: ShellBash (Legacy experience), ShellZsh (Recommended experience)
+PREFERRED_SHELL="ShellBash"
 
 # Display Fortune tooltip at bash/zsh session open
 SHOW_FORTUNES=1
@@ -439,19 +439,6 @@ Env::requireLoad() {
 # @arg $1 templateName:String template name to use(optional)
 Framework::createTempFile() {
   mktemp -p "${TMPDIR:-/tmp}" -t "${1:-}.XXXXXXXXXXXX"
-}
-
-# @description checks if Systemd is running
-# @noargs
-# @exitcode 1 if systemd is not running
-# @stdout diagnostics information
-Linux::isSystemdRunning() {
-  if [[ "$(readlink -f /sbin/init)" = "/usr/lib/systemd/systemd" ]]; then
-    Log::displayInfo "SystemD is running"
-    return 0
-  fi
-  Log::displayInfo "SystemD is not running"
-  return 1
 }
 
 # @description Log namespace provides 2 kind of functions
@@ -643,7 +630,7 @@ Retry::parameterized() {
 # @arg $1 character:String character to use as separator (default value #)
 UI::drawLine() {
   local character="${1:-#}"
-  printf '%*s\n' "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo)}" '' | tr ' ' "${character}"
+  printf -- "${character}%.0s" $(seq "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo)}")
 }
 
 # @description load colors theme constants
@@ -849,7 +836,7 @@ Engine::Config::checkEnv() {
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues AWS_AUTHENTICATOR Saml2Aws Awsume
-  checkValidValues PREFERRED_SHELL BashProfile ZshProfile
+  checkValidValues PREFERRED_SHELL ShellBash ShellZsh
 
   checkValidValues SHOW_FORTUNES 0 1
   checkValidValues SHOW_MOTD 0 1
@@ -1292,6 +1279,7 @@ Conf::dynamicConfFile() {
 # @arg $@ callbacksParams:String[] additional parameters passed to callbacks
 # @exitcode 1 if fromFile is not readable
 # @exitcode 2 if backup file failure
+# @exitcode 3 if copy failure
 # @exitcode 0 on success or if OVERWRITE_CONFIG_FILES=0
 # @exitcode 0 on success or if CHANGE_WINDOWS_FILES=0 and target file is a windows file
 # @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing directory
@@ -1341,10 +1329,12 @@ Install::file() {
   Backup::file "${targetFile}" || return 2
 
   if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
-    ${successCallback} "${fromFile}" "${targetFile}" "$@"
     Log::displaySuccess "Installed file '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
+    ${successCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
   else
-    ${failureCallback} "${fromDir}" "${fromFilename}" "${targetFile}" "$@"
+    Log::displayError "unable to copy file from '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
+    ${failureCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
+    return 3
   fi
 }
 
@@ -2494,6 +2484,11 @@ exportDistro() {
   gzip -9 "/tmp/${DISTRO_NAME}.tar"
 }
 
+isDistroSystemdRunning() {
+  [[ "$(runWslCmd readlink -f /sbin/init)" = "/usr/lib/systemd/systemd" ]] || return 1
+  runWslCmd systemctl status --no-pager &>/dev/null || return 1
+}
+
 # @require Linux::requireExecutedAsUser
 run() {
   if [[ ! -f "${BASH_DEV_ENV_ROOT_DIR}/.env.distro" ]]; then
@@ -2551,7 +2546,7 @@ run() {
     tee -a "/mnt/wsl/${DISTRO_NAME}/home/wsl/.bashrc" >/dev/null
 
   Log::displayInfo "Delete folder ${DISTRO_BASH_DEV_ENV_TARGET_DIR} in distro ${DISTRO_NAME}"
-  runWslCmd rm -Rf "${DISTRO_BASH_DEV_ENV_TARGET_DIR}" 2>/dev/null || true
+  runWslCmd rm -Rf "${DISTRO_BASH_DEV_ENV_TARGET_DIR}/"{*,.*} 2>/dev/null || true
 
   Log::displayInfo "Prepare archive of current dir ${DISTRO_BASH_DEV_ENV_TARGET_DIR}"
   (cd "${BASH_DEV_ENV_ROOT_DIR}" && tar czf /tmp/bashDevEnv.tgz .)
@@ -2569,7 +2564,7 @@ run() {
   cp -v "${BASH_DEV_ENV_ROOT_DIR}/.env.distro" "/mnt/wsl/${DISTRO_NAME}${DISTRO_BASH_DEV_ENV_TARGET_DIR}/.env"
 
   local systemdActivated=0
-  if Linux::isSystemdRunning; then
+  if isDistroSystemdRunning; then
     systemdActivated=1
   fi
   Log::displayInfo 'pre-configure /etc/wsl.conf in order to activate systemd'
@@ -2588,7 +2583,7 @@ run() {
     }
     Retry::parameterized 20 1 "Waiting for distro ${DISTRO_NAME} to terminate" checkDistroTerminated
     Log::displayInfo "Check if systemd has been enabled successfully"
-    if ! Linux::isSystemdRunning; then
+    if ! isDistroSystemdRunning; then
       Log::fatal "Systemd is not running"
     fi
   fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -328,8 +328,8 @@ UPGRADE_UBUNTU_VERSION=0
 AWS_AUTHENTICATOR="Saml2Aws"
 
 # Choose your preferred shell
-# possible choices: BashProfile (Legacy experience), ZshProfile (Recommended experience)
-PREFERRED_SHELL="BashProfile"
+# possible choices: ShellBash (Legacy experience), ShellZsh (Recommended experience)
+PREFERRED_SHELL="ShellBash"
 
 # Display Fortune tooltip at bash/zsh session open
 SHOW_FORTUNES=1
@@ -936,7 +936,46 @@ EOF
 # @arg $1 character:String character to use as separator (default value #)
 UI::drawLine() {
   local character="${1:-#}"
-  printf '%*s\n' "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo)}" '' | tr ' ' "${character}"
+  printf -- "${character}%.0s" $(seq "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo)}")
+}
+
+# @description draw a line with the character passed in parameter repeated depending on terminal width
+# including message in the middle of the screen
+# @arg $2 msg:String msg to display on the middle
+# @arg $1 character:String character to use as separator (default value #)
+# @env COLUMNS number of columns, if not provided compute the screen width
+UI::drawLineWithMsg() {
+  local msg="${1:-}"
+  local character="${2:-#}"
+  if ((${#msg} == 0)); then
+    UI::drawLine "${character}"
+    return 0
+  fi
+
+  # compute screen width
+  local -i width=${COLUMNS:-}
+  if (( width == 0 )); then
+    if [[ -t 0 ]]; then
+      width=$(tput cols)
+    fi
+  fi
+  if (( width == 0 )); then
+    width=80
+  fi
+
+  # compute msg
+  if (( ${#msg} + 4 > width )); then
+    msg="${msg:0:$((width - 4))}"
+  fi
+
+  # compute left/right line
+  local -i leftWidth=$(( (width - ${#msg} - 2) / 2 ))
+  local -i rightWidth=$(( width - ${#msg} - 2 - leftWidth ))
+
+  # display line
+  printf -- "${character}%.0s" $(seq "${leftWidth}")
+  echo -n " ${msg} "
+  printf -- "${character}%.0s" $(seq "${rightWidth}")
 }
 
 # @description load colors theme constants
@@ -1142,7 +1181,7 @@ Engine::Config::checkEnv() {
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues AWS_AUTHENTICATOR Saml2Aws Awsume
-  checkValidValues PREFERRED_SHELL BashProfile ZshProfile
+  checkValidValues PREFERRED_SHELL ShellBash ShellZsh
 
   checkValidValues SHOW_FORTUNES 0 1
   checkValidValues SHOW_MOTD 0 1
@@ -1585,6 +1624,7 @@ Conf::dynamicConfFile() {
 # @arg $@ callbacksParams:String[] additional parameters passed to callbacks
 # @exitcode 1 if fromFile is not readable
 # @exitcode 2 if backup file failure
+# @exitcode 3 if copy failure
 # @exitcode 0 on success or if OVERWRITE_CONFIG_FILES=0
 # @exitcode 0 on success or if CHANGE_WINDOWS_FILES=0 and target file is a windows file
 # @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing directory
@@ -1634,10 +1674,12 @@ Install::file() {
   Backup::file "${targetFile}" || return 2
 
   if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
-    ${successCallback} "${fromFile}" "${targetFile}" "$@"
     Log::displaySuccess "Installed file '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
+    ${successCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
   else
-    ${failureCallback} "${fromDir}" "${fromFilename}" "${targetFile}" "$@"
+    Log::displayError "unable to copy file from '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
+    ${failureCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
+    return 3
   fi
 }
 
@@ -3803,6 +3845,8 @@ executeScripts() {
         ${SUDO:-sudo} tee "${sudoerFile}" >/dev/null
       ${SUDO:-sudo} chmod 0440 "${sudoerFile}"
     fi
+    local -i configIndex=1
+    local -i configCount=${#CONFIG_LIST[@]}
     # shellcheck disable=SC2317
     for configName in "${CONFIG_LIST[@]}"; do
       installStatus="0"
@@ -3825,12 +3869,14 @@ executeScripts() {
           "${LOGS_DIR:-#}/${configName}"-{install,config,test-install,test-configuration}.stat \
           &>/dev/null || true
 
+        UI::drawLineWithMsg "Installing ${configName} (${configIndex}/${configCount})" '#'
         executeScript "${configName}"
       ) || installStatus="$?"
       if [[ "${installStatus}" != "0" ]]; then
         Log::displayError "Aborted after ${configName} failure"
         exit "${installStatus}"
       fi
+      ((++configIndex))
     done
   ) 2>&1 | tee >(sed -r 's/\x1b\[[0-9;]*m//g' >>"${LOGS_DIR}/automatic-upgrade")
 }
