distro clean coding + clarify distro target dir

diff --git a/distro b/distro
--- a/distro
+++ b/distro
@@ -88,12 +88,14 @@ export TMPDIR
 # temp dir cleaning
 # shellcheck disable=SC2317
 cleanOnExit() {
+  local rc=$?
   if [[ "${KEEP_TEMP_FILES:-0}" = "1" ]]; then
     Log::displayInfo "KEEP_TEMP_FILES=1 temp files kept here '${TMPDIR}'"
   elif [[ -n "${TMPDIR+xxx}" ]]; then
     Log::displayDebug "KEEP_TEMP_FILES=0 removing temp files '${TMPDIR}'"
     rm -Rf "${TMPDIR:-/tmp/fake}" >/dev/null 2>&1
   fi
+  exit "${rc}"
 }
 trap cleanOnExit EXIT HUP QUIT ABRT TERM
 
@@ -1474,9 +1476,11 @@ if [[ -f "${sudoerFile}" ]]; then
   true
 else
   cleanSudoer() {
+    local rc=$?
     if [[ -f "${sudoerFile}" ]]; then
       ${SUDO:-sudo} rm -f "${sudoerFile}" || true
     fi
+    exit "${rc}"
   }
   trap cleanSudoer EXIT HUP QUIT ABRT TERM
 
@@ -2213,34 +2217,38 @@ downloadDistro() {
     sudo apt-get update
     sudo apt-get install -y aria2
   fi
+  local distroImageDir
+  distroImageDir="$(getDistroImageDir)"
+  local distroImageTargetZip="${TMPDIR:-/tmp}/${distroImageDir}.zip"
 
-  if [[ ! -f "${DISTRO_IMAGE_TARGET_DIR}/AppxBlockMap.xml" ]]; then
+  if [[ ! -f "${distroImageDir}/AppxBlockMap.xml" ]]; then
+    Log::displayInfo "File ${distroImageDir}/AppxBlockMap.xml does not exist"
     Log::displayInfo "Downloading official ubuntu image from ${DISTRO_URL} ..."
     # https://github.com/aria2/aria2/issues/684
     (
       cd /
-      aria2c -c --max-connection-per-server=8 --min-split-size=1M -o "${DISTRO_IMAGE_TARGET_ZIP}" "${DISTRO_URL}"
+      aria2c -c --max-connection-per-server=8 --min-split-size=1M -o "${distroImageTargetZip}" "${DISTRO_URL}"
     )
     Log::displayInfo "Unzipping ubuntu image ..."
-    unzip "${DISTRO_IMAGE_TARGET_ZIP}" -d "${DISTRO_IMAGE_TARGET_DIR}"
+    unzip "${distroImageTargetZip}" -d "${distroImageDir}"
   fi
 
-  if [[ ! -f "${DISTRO_IMAGE_TARGET_DIR}/install.tar" ]]; then
+  if [[ ! -f "${distroImageDir}/install.tar" ]]; then
     Log::displayInfo "Extracting install.tar from ubuntu image ..."
     (
-      cd "${DISTRO_IMAGE_TARGET_DIR}" || exit 1
+      cd "${distroImageDir}" || exit 1
       rm -f Ubuntu_*ARM64.appx
       mv Ubuntu_*_x64.appx Ubuntu.zip
       unzip -p Ubuntu.zip install.tar.gz | gunzip >install.tar
     )
 
     Log::displayInfo "Cleaning"
-    rm -f "${DISTRO_IMAGE_TARGET_DIR}"/Ubuntu.zip
-    rm -f "${DISTRO_IMAGE_TARGET_ZIP}"
+    rm -f "${distroImageDir}"/Ubuntu.zip
+    rm -f "${distroImageTargetZip}"
   fi
 
-  if [[ ! -f "${DISTRO_IMAGE_TARGET_DIR}/install.tar" ]]; then
-    Log::displayError "File '${DISTRO_IMAGE_TARGET_DIR}/install.tar' not found"
+  if [[ ! -f "${distroImageDir}/install.tar" ]]; then
+    Log::displayError "File '${distroImageDir}/install.tar' not found"
     exit 1
   fi
 }
@@ -2248,15 +2256,17 @@ downloadDistro() {
 runWslCmd() {
   local user="${REMOTE_USER:-root}"
   local pwd="${REMOTE_PWD:-/root}"
-  wsl.exe -d "${DISTRO_NAME}" -u "${user}" --cd "${pwd}" -- "$@"
+  wsl.exe -d "${DISTRO_NAME}" -u "${user}" --cd "${pwd}" -- "$@" || return 1
 }
 
 installDistro() {
   Log::displayInfo 'Import Base ubuntu image in Wsl'
   local destDistroPath installTarPath
   mkdir -p "${BASE_MNT_C}/Programs"
+  local distroImageDir
+  distroImageDir="$(distroImageDir)"
   destDistroPath="$(wslpath -w "${BASE_MNT_C}/Programs/${DISTRO_NAME}")"
-  installTarPath="$(wslpath -w "${DISTRO_IMAGE_TARGET_DIR}/install.tar")"
+  installTarPath="$(wslpath -w "${distroImageDir}/install.tar")"
   powershell.exe -ExecutionPolicy Bypass -NoProfile \
     -Command "wsl.exe --import \"${DISTRO_NAME}\" \"${destDistroPath}\" \"${installTarPath}\" --version 2"
 
@@ -2274,13 +2284,25 @@ mountDistroFolder() {
   runWslCmd chown -R "${USERNAME}:${USERGROUP}" /home/wsl/fchastanet
 }
 
-exportDistro() {
-  Log::displayInfo "Exporting wsl distribution"
-  wsl.exe --terminate "${DISTRO_NAME}"
-  wsl.exe --export "${DISTRO_NAME}" "${DISTRO_IMAGE_TARGET_DIR:-/tmp}/${DISTRO_NAME}.tar"
+getDistroImageName() {
+  echo "${DISTRO_URL##*/}"
+}
 
-  Log::displayInfo "Compressing wsl distribution to ${DISTRO_FILE}"
-  gzip -9 "${DISTRO_IMAGE_TARGET_DIR:-/tmp}/${DISTRO_NAME}.tar"
+getDistroImageDir() {
+  echo "${DISTRO_IMAGE_TARGET_DIR}/$(getDistroImageName)"
+}
+
+getDistroFile() {
+  echo "$(getDistroImageDir)-${DISTRO_NAME}-export.tar.gz"
+}
+
+exportDistro() {
+  local distroFile
+  distroFile="$(getDistroFile)"
+  Log::displayInfo "Terminating wsl distribution ${DISTRO_NAME}"
+  wsl.exe --terminate "${DISTRO_NAME}"
+  Log::displayInfo "Exporting wsl distribution to ${distroFile}"
+  wsl.exe --export "${DISTRO_NAME}" - | gzip -9 >"${distroFile}"
 }
 
 isDistroSystemdRunning() {
@@ -2310,10 +2332,6 @@ run() {
   fi
   # The path where bash-dev-env project will be copied into target distro
   DISTRO_BASH_DEV_ENV_TARGET_DIR="${BASH_DEV_ENV_ROOT_DIR}"
-  DISTRO_FILE="${DISTRO_IMAGE_TARGET_DIR:-/tmp}/${DISTRO_NAME}.tar.gz"
-  DISTRO_IMAGE_NAME="${DISTRO_URL##*/}"
-  DISTRO_IMAGE_TARGET_DIR="${DISTRO_IMAGE_TARGET_DIR:-/tmp}/${DISTRO_IMAGE_NAME}"
-  DISTRO_IMAGE_TARGET_ZIP="${DISTRO_IMAGE_TARGET_DIR:-/tmp}/${DISTRO_IMAGE_NAME}.zip"
   # shellcheck disable=SC1003
   BASE_MNT_C="$(mount | grep 'path=C:\\' | awk -F ' ' '{print $3}')"
 
@@ -2386,10 +2404,16 @@ run() {
       Log::fatal "Systemd is not running"
     fi
   fi
+  local installCmd=(
+    ./install -p "${DISTRO_INSTALL_PROFILE}" "${DISTRO_INSTALL_OPTIONS[@]}"
+  )
+  if [[ "${optionExport}" = "1" ]]; then
+    installCmd+=(--prepare-export)
+  fi
 
   if [[ "${optionSkipInstall}" = "1" ]]; then
     Log::displayInfo "Install manually using :"
-    echo "wsl.exe -d '${DISTRO_NAME}' -u wsl --cd '${DISTRO_BASH_DEV_ENV_TARGET_DIR}' -- ./install -p '${DISTRO_INSTALL_PROFILE}'"
+    echo "wsl.exe -d '${DISTRO_NAME}' -u wsl --cd '${DISTRO_BASH_DEV_ENV_TARGET_DIR}' -- ${installCmd[*]}"
   else
     (
       # shellcheck disable=SC2034
@@ -2406,9 +2430,11 @@ run() {
         true
       else
         cleanSudoer() {
+          local rc=$?
           if [[ -f "${sudoerFile}" ]]; then
             ${SUDO:-sudo} rm -f "${sudoerFile}" || true
           fi
+          exit "${rc}"
         }
         trap cleanSudoer EXIT HUP QUIT ABRT TERM
 
@@ -2418,9 +2444,10 @@ run() {
         ${SUDO:-sudo} chmod 0440 "${sudoerFile}"
       fi
 
-      Log::displayInfo "Installing ..."
-      REMOTE_USER=${USERNAME} REMOTE_PWD="${DISTRO_BASH_DEV_ENV_TARGET_DIR}" runWslCmd ./install -p "${DISTRO_INSTALL_PROFILE}" "${DISTRO_INSTALL_OPTIONS[@]}"
-    )
+      Log::displayInfo "Installing ... using ${installCmd[*]}"
+      REMOTE_USER=${USERNAME} REMOTE_PWD="${DISTRO_BASH_DEV_ENV_TARGET_DIR}" \
+        runWslCmd "${installCmd[@]}" || exit 1
+    ) || exit 1
   fi
 
   if [[ "${optionExport}" = "1" ]]; then
@@ -2428,8 +2455,10 @@ run() {
   fi
 
   if [[ "${optionUpload}" = "1" ]]; then
-    if [[ ! -f "${DISTRO_FILE}" ]]; then
-      Log::fatal "missing ${DISTRO_FILE}, have you forgot --export option ?"
+    local distroFile
+    distroFile="$(getDistroFile)"
+    if [[ ! -f "" ]]; then
+      Log::fatal "missing ${distroFile}, have you forgot --export option ?"
     fi
     Log::displaySkipped "Not implemented yet"
   else
