align bash-tools + bash-tools-framework v4.0.0
## github workflow

- overall config alignment with bash-dev-env and
  bash-tools-framework 4.0.0- make megalinter lint
  all codebase
- cancel previous build if several pushes
- cspell - remove global dictionaries config key
  and adapt cspell rules accordingly
- bin/doc
  - removed Docker::runBuildContainer dependency

diff --git a/install b/install
--- a/install
+++ b/install
@@ -488,7 +488,15 @@ UI::theme() {
 # @arg $1 character:String character to use as separator (default value #)
 UI::drawLine() {
   local character="${1:-#}"
-  printf -- "${character}%.0s" $(seq "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo '80')}")
+  local -i width=${COLUMNS:-0}
+  if ((width == 0)) && [[ -t 1 ]]; then
+    width=$(tput cols)
+  fi
+  if ((width == 0)); then
+    width=80
+  fi
+  printf -- "${character}%.0s" $(seq "${COLUMNS:-$([[ -t 1 ]] && tput cols || echo '80')}")
+  echo
 }
 
 # @description Display message using error color (red) and exit immediately with error status 1
@@ -1160,10 +1168,8 @@ UI::drawLineWithMsg() {
 
   # compute screen width
   local -i width=${COLUMNS:-0}
-  if ((width == 0)); then
-    if [[ -t 0 ]]; then
-      width=$(tput cols)
-    fi
+  if ((width == 0)) && [[ -t 1 ]]; then
+    width=$(tput cols)
   fi
   if ((width == 0)); then
     width=80
@@ -1183,6 +1189,7 @@ UI::drawLineWithMsg() {
   printf -- "${character}%.0s" $(seq "${leftWidth}")
   echo -n " ${msg} "
   printf -- "${character}%.0s" $(seq "${rightWidth}")
+  echo
 }
 
 # @description check if dependencies exist
@@ -2156,8 +2163,10 @@ Linux::Wsl::requireWsl() {
 # @arg $@ command:String[] the command to run
 # @exitcode 0 on success
 # @exitcode 1 if max retries count reached
+# @env RETRY_MAX_RETRY int max retries
+# @env RETRY_DELAY_BETWEEN_RETRIES int delay between attempts
 Retry::default() {
-  Retry::parameterized 5 15 "" "$@"
+  Retry::parameterized "${RETRY_MAX_RETRY:-5}" "${RETRY_DELAY_BETWEEN_RETRIES:-15}" "" "$@"
 }
 
 # @description call simply original wslpath command
