added Saml2Aws

diff --git a/installScripts/AwsCli b/installScripts/AwsCli
--- a/installScripts/AwsCli
+++ b/installScripts/AwsCli
@@ -327,6 +327,12 @@ GIT_USERNAME=""
 GIT_USER_MAIL=""
 # email used to connect to aws
 AWS_USER_MAIL="fchastanet@gmail.com"
+# app id to connect to aws account
+AWS_APP_ID=""
+AWS_PROFILE=""
+AWS_TEST_REGION=""
+AWS_TEST_SECRET_ID=""
+AWS_TEST_DOCKER_REGISTRY_ID=""
 
 # hostname of the distro
 DISTRO_HOSTNAME="wslHost"
@@ -395,9 +401,9 @@ CHANGE_WINDOWS_FILES=1
 # Indicate that install script can warn you using speaker when your input is needed
 CAN_TALK_DURING_INSTALLATION=1
 
-# if 1 install script will skip all interactive activity (saml2aws, ...),
+# if 0 install script will skip all interactive activity (saml2aws, ...),
 # so dependent installation will be skipped as well
-INSTALL_NON_INTERACTIVE=0
+INSTALL_INTERACTIVE=0
 
 # display elapsed time since last log
 DISPLAY_DURATION=1
@@ -1165,7 +1171,7 @@ Engine::Config::checkEnv() {
   checkValidValues OVERWRITE_CONFIG_FILES 0 1
   checkValidValues CHANGE_WINDOWS_FILES 0 1
   checkValidValues CAN_TALK_DURING_INSTALLATION 0 1
-  checkValidValues INSTALL_NON_INTERACTIVE 0 1
+  checkValidValues INSTALL_INTERACTIVE 0 1
 
   checkNotEmpty WSLCONFIG_MAX_MEMORY
   checkValidValues WSLCONFIG_SWAP 0 1
@@ -2896,8 +2902,8 @@ install() {
 configure() {
   # shellcheck disable=SC2317
   configureAwsConfig() {
-    sed -i \
-      -e "s#azure_default_username=#azure_default_username=${AWS_USER_MAIL}#" \
+    sed -i -E \
+      -e "s#azure_default_username=.+\$#azure_default_username=${AWS_USER_MAIL}#" \
       "${USER_HOME}/.aws/config"
     Install::setUserRightsCallback "$@"
   }
@@ -2908,11 +2914,29 @@ configure() {
 }
 
 testInstall() {
-  Version::checkMinimal "docker" --version "2.13.35" || ((++failures))
+  Version::checkMinimal "aws" --version "2.13.32" || ((++failures))
 }
 
 testConfigure() {
   Assert::fileExists "${USER_HOME}/.aws/config" "${USERNAME}" "${USERGROUP}" || return 1
+
+  if grep -q -E -e "azure_default_username=.+$" "${USER_HOME}/.aws/config"; then
+    # case where .aws/config has been overridden in conf_override folder
+    local azureUserName
+    azureUserName="$(sed -nr 's/azure_default_username=(.*)$/\1/p' "${USER_HOME}/.aws/config")"
+    if [[ -z "${azureUserName}" ]]; then
+      ((++failures))
+      Log::displayError "empty azure_default_username in '${USER_HOME}/.aws/config'"
+    elif [[ "${azureUserName}" != "${AWS_USER_MAIL}" ]]; then
+      Log::displayWarning "azureUserName is not the same as AWS_USER_MAIL in ${BASH_DEV_ENV_ROOT_DIR}/.env"
+    fi
+  elif ! grep -q -E -e "^\[default\]$" "${USER_HOME}/.aws/config"; then
+    ((++failures))
+    Log::displayError "default configuration not found in '${USER_HOME}/.aws/config'"
+  fi
+
+return "${failures}"
+
 }
 
 local action=$1
