AwsDefaultConfig - extracted authentication logic to Auth::authenticate function

diff --git a/installScripts/AwsDefaultConfig b/installScripts/AwsDefaultConfig
--- a/installScripts/AwsDefaultConfig
+++ b/installScripts/AwsDefaultConfig
@@ -464,6 +464,34 @@ Assert::wsl() {
 }
 
 
+# @description Authenticate the user
+# @noargs
+# @exitcode 0 If successful
+# @exitcode 1 If failed
+Auth::authenticate() {
+Linux::requireTarCommand
+Compiler::Embed::extractFileFromBase64 \
+  "${PERSISTENT_TMPDIR:-/tmp}/a41b13eb5802e6ccd86d22816a7a8fb4c3675f9887a1b6a716b090ee8b458bf3/talkScript" \
+  "cGFyYW0oCiAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSwgUG9zaXRpb249MCldCiAgICBbc3RyaW5nXQogICAgJG1zZyA9ICcnCikKCkFkZC1UeXBlIC1Bc3NlbWJseU5hbWUgU3lzdGVtLnNwZWVjaAokc3BlYWsgPSBOZXctT2JqZWN0IFN5c3RlbS5TcGVlY2guU3ludGhlc2lzLlNwZWVjaFN5bnRoZXNpemVyCiRzcGVhay5TcGVhaygkbXNnKQo=" \
+  "644"
+
+declare -gx embed_file_talkScript="${PERSISTENT_TMPDIR:-/tmp}/a41b13eb5802e6ccd86d22816a7a8fb4c3675f9887a1b6a716b090ee8b458bf3/talkScript"
+
+  # shellcheck disable=SC2154
+  cp "${embed_file_talkScript}" "${embed_file_talkScript}.ps1"
+  UI::talkToUser "Please on Bash Dev env installation, your input may be required" \
+    "${embed_file_talkScript}.ps1"
+  # try to login
+  if ! Retry::parameterized 3 0 \
+    "AWS Authentication, please provide your credentials ..." \
+    saml2aws login -p "${AWS_PROFILE}" --disable-keychain; then
+    Log::displayError "Failed to connect to aws"
+    return 1
+  fi
+  Log::displaySuccess "Aws connection succeeds"
+}
+
+
 # @description Backup given file in the same directory or in BACKUP_DIR directory
 # backup file name is composed by following fields separated by -:
 #   - if BACKUP_DIR is not empty then escaped dir name separated by @
@@ -3300,14 +3328,6 @@ commandOptionParseFinished() {
 
 
 Linux::requireTarCommand
-Compiler::Embed::extractFileFromBase64 \
-  "${PERSISTENT_TMPDIR:-/tmp}/a41b13eb5802e6ccd86d22816a7a8fb4c3675f9887a1b6a716b090ee8b458bf3/talkScript" \
-  "cGFyYW0oCiAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSwgUG9zaXRpb249MCldCiAgICBbc3RyaW5nXQogICAgJG1zZyA9ICcnCikKCkFkZC1UeXBlIC1Bc3NlbWJseU5hbWUgU3lzdGVtLnNwZWVjaAokc3BlYWsgPSBOZXctT2JqZWN0IFN5c3RlbS5TcGVlY2guU3ludGhlc2lzLlNwZWVjaFN5bnRoZXNpemVyCiRzcGVhay5TcGVhaygkbXNnKQo=" \
-  "644"
-
-declare -gx embed_file_talkScript="${PERSISTENT_TMPDIR:-/tmp}/a41b13eb5802e6ccd86d22816a7a8fb4c3675f9887a1b6a716b090ee8b458bf3/talkScript"
-
-Linux::requireTarCommand
 Compiler::Embed::extractDirFromBase64 \
   "${PERSISTENT_TMPDIR:-/tmp}/3b891c7e8b0f59344b7551414e0df78203dcec3c0ff91ebaa9303a7cae1b2fb7/conf_dir" \
   "H4sIAAAAAAAA/+yXQW/aMBSAe86veCvTepmJoQlIm5iUknSNVpGKBFXTNCFDDFgNNrKdZNXGf59CgZVIVQ8Dpol8FxtjPz9L/l6SOsmVORZ8wqZnhwJjjFuWtWoxxuUW40v7T78YbzSa1uUZ4INl9IxUaSLP8F/vVT7cf8K3mE5ImujvhqRTJjh0gKYop0qjhvGvk6s4OPURUTMU0wxRnpkkYURRVY9Nkqtuwupqtoc9Ch/atv2i/+1W2X+70W5V/h+D2hszVdIcMW5SnkFxG4zafjFq4AbQCyLwXD96D9GNH8K1f+tB1+nBlQeDO9eJPBfu/egmGETFVL/r7T0NowaMg5AxlaAFJGJa/NYCSK6AjiUgWEiWEU0hFuMHKqEoiUrLR4NNYCzmc8JjQNlq/rtPZkwzk6dJ8hH0jHIDYGVP8S96Wo8SMWW8c7GJP6X6aQgtiFK5kDEgtC67529/Ovfh0PWuncFtNOx7n/2gtzyHX5tcVgsBoVRRycmcgnMfAtpGQkrHjMNuFDfofvH6q2Bh1P869N3lhTFhz+v6S/4rMk+aJFf7qACv+d/CVtl/q21X/h+DU/J/1+LNDX9F5bXD29lrDxcbY+/6QXGWD2j9IrU8B4QUVYoJjuJUEs0E71iXTYwBoZgpMkooeqCP4xlhvKzj0dn1fyHFhCX0yP5bzVbZf7tRPf+Pwin5T38shNTgXg3CYeiFoR/0hkXfcd2+F4adbRmoPnwqKipOgN8BAAD//z0sMTUAFAAA"
@@ -3432,20 +3452,11 @@ testConfigure() {
   if [[ "${INSTALL_INTERACTIVE}" = "0" ]]; then
     Log::displaySkipped "saml2aws configuration skipped as INSTALL_INTERACTIVE is set to 0"
   elif [[ -n "${AWS_APP_ID}" && -n "${AWS_PROFILE}" && -n "${AWS_USER_MAIL}" ]]; then
-    # try to login
-    # shellcheck disable=SC2154
-    cp "${embed_file_talkScript}" "${embed_file_talkScript}.ps1"
-    UI::talkToUser "Please on Bash Dev env installation, your input may be required" \
-      "${embed_file_talkScript}.ps1"
-    if ! Retry::parameterized 3 0 \
-      "AWS Authentication, please provide your credentials ..." \
-      saml2aws login -p "${AWS_PROFILE}" --disable-keychain; then
+    Auth::authenticate || {
+      Log::displayError "Failed to authenticate"
       ((++failures))
-      Log::displayError "Failed to connect to aws"
       return "${failures}"
-    fi
-    Log::displaySuccess "Aws connection succeeds"
-
+    }
     # try to get secret
     Log::displayInfo "Trying to get secrets from aws"
     if ! aws secretsmanager \
