PreCommitConfig with all dependencies

diff --git a/installScripts/BashTools b/installScripts/BashTools
--- a/installScripts/BashTools
+++ b/installScripts/BashTools
@@ -507,6 +507,8 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
+  export PATH="${PATH}:${USER_HOME}/.local/bin"
+
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
 
@@ -576,7 +578,8 @@ Install::dir() {
   local userGroup="${5:-${USERGROUP:-root}}"
 
   if [[ ! -d "${fromDir}/${dirName}" || ! -r "${fromDir}/${dirName}" ]]; then
-    Log::fatal "cannot read source directory '${fromDir}/${dirName}'"
+    Log::displayError "cannot read source directory '${fromDir}/${dirName}'"
+    return 1
   fi
 
   # skip if OVERWRITE_CONFIG_FILES=0 and target dir exists
@@ -655,10 +658,12 @@ InstallScripts::command() {
       startDate="$(date +%s)"
       trap 'Stats::computeStatsTrap "Installation ${scriptName}" "${logFile}" "${statsFile}" "${startDate}"' EXIT INT TERM ABRT
 
-      sourceHook preInstall
-      install 2>&1 | tee "${logFile}"
-      sourceHook postInstall
-    )
+      local -i failures=0
+      sourceHook preInstall || ((++failures))
+      install || ((++failures))
+      sourceHook postInstall || ((++failures))
+      exit "${failures}"
+    ) 2>&1 | tee "${logFile}"
   fi
 
   local testInstallStatus="0"
@@ -669,10 +674,13 @@ InstallScripts::command() {
     (
       startDate="$(date +%s)"
       trap 'Stats::computeStatsTrap "Test ${scriptName}" "${logFile}" "${statsFile}" "${startDate}"' EXIT INT TERM ABRT
-      sourceHook preTestInstall
-      testInstall 2>&1 | tee "${logFile}"
-      sourceHook postTestInstall
-    ) || testInstallStatus="$?" || true
+
+      local -i failures=0
+      sourceHook preTestInstall || ((++failures))
+      testInstall || ((++failures))
+      sourceHook postTestInstall || ((++failures))
+      exit "${failures}"
+    ) 2>&1 | tee "${logFile}" || testInstallStatus="$?" || true
     if [[ "${testInstallStatus}" != "0" ]] && breakOnTestFailure; then
       # break if test script error
       exit "${testInstallStatus}"
@@ -688,10 +696,12 @@ InstallScripts::command() {
       startDate="$(date +%s)"
       trap 'Stats::computeStatsTrap "Configuration ${scriptName}" "${logFile}" "${statsFile}" "${startDate}"' EXIT INT TERM ABRT
 
-      sourceHook preConfigure
-      configure 2>&1 | tee "${logFile}"
-      sourceHook postConfigure
-    ) || configStatus="$?" || true
+      local -i failures=0
+      sourceHook preConfigure || ((++failures))
+      configure || ((++failures))
+      sourceHook postConfigure || ((++failures))
+      exit "${failures}"
+    ) 2>&1 | tee "${logFile}" || configStatus="$?" || true
 
     if [[ "${configStatus}" != "0" ]] && breakOnConfigFailure; then
       # break if config script error
@@ -708,10 +718,12 @@ InstallScripts::command() {
       startDate="$(date +%s)"
       trap 'Stats::computeStatsTrap "Test ${scriptName}" "${logFile}" "${statsFile}" "${startDate}"' EXIT INT TERM ABRT
 
-      sourceHook preTestConfigure
-      testConfigure 2>&1 | tee "${logFile}"
-      sourceHook postTestConfigure
-    ) || testConfigStatus="$?" || true
+      local -i failures=0
+      sourceHook preTestConfigure || ((++failures))
+      testConfigure || ((++failures))
+      sourceHook postTestConfigure || ((++failures))
+      exit "${failures}"
+    ) 2>&1 | tee "${logFile}" || testConfigStatus="$?" || true
     if [[ "${testConfigStatus}" != "0" ]] && breakOnTestFailure; then
       # break if test script error
       exit "${testConfigStatus}"
@@ -1269,6 +1281,7 @@ Engine::Config::loadWslVariables() {
   fi
   # shellcheck disable=SC1003
   BASE_MNT_C="$(mount | grep 'path=C:\\' | awk -F ' ' '{print $3}')"
+  export BASE_MNT_C
 
   WINDOWS_DIR="$(Linux::Wsl::cachedWslpathFromWslVar SystemRoot)"
   WINDOWS_DIR="${WINDOWS_DIR:-${BASE_MNT_C}/Windows}"
@@ -3010,7 +3023,10 @@ fortunes() {
   fi
 }
 
-dependencies() { :; }
+dependencies() {
+  echo "PreCommitConfig"
+}
+
 helpVariables() { :; }
 listVariables() { :; }
 defaultVariables() { :; }
