Zsh optimizations
## Improvements
- fixWslDate - launched a bash/zsh init now uses a sudoer file to avoid to ask root
  password
- loadConfigFiles - only load files that are executable, allowing to disable some
  loading by setting files to not load to non executable
- ShellZsh - optimizations
  - optimized all zinit loading to defer some loading to make zsh startup faster
  - better way to remove unneeded aliases
  - git replaced OMZP::git by OMZP::gitfast
  - load theme near start of zshrc
  - removed aliases added by
    - OMZP::docker
    - OMZP::docker-compose
    - OMZP::kubectl
    - OMZP::kubectx
- ShellZsh changes
  - better update of all zinit packages
  - added zsh-users/zsh-completions
- FD - added zsh completions
- GitConfig - experimental - added diff.algorithm=histogram
- Go - improved install - now using Web::upgradeRelease to avoid unneeded download
- MandatorySoftwares - added subversion - needed by some zinit packages

# Bug fixes
- PlantUml - missing sdkmanager init
- SdkManager - java install is returning non-zero exit code if java already installed
- SdkManagerDependencies - missing sdkmanager init
- ShellZsh
  - theme powerlevel10k - fixed intialization issue
  - theme starship - fixed intialization issue
  - added LC_ALL and LANG env variables initialization needed by some zinit
    packages
- all commands - load hook even if not executable

## Miscelleaneous
- replaced .gitkeep by a .gitgnore file https://adamj.eu/tech/2023/09/18/git-dont-create-gitkeep/

diff --git a/installScripts/BashTools b/installScripts/BashTools
--- a/installScripts/BashTools
+++ b/installScripts/BashTools
@@ -572,9 +572,12 @@ InstallScripts::command() {
     local hookName="$1"
     # shellcheck disable=SC2154
     hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
-    if [[ -x "${hook}" ]]; then
+    if [[ -n "${hook}" && -f "${hook}" && -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/hooks/preInstall.sh
-      source "${hook}" || exit 1
+      source "${hook}" || {
+        Log::displayError "${scriptName} - unable to load hook '${hook}'"
+        exit 1
+      }
     fi
   }
   local globalStatsFile="${logsDir}/${scriptName}-global.stat"
@@ -1351,7 +1354,7 @@ Log::rotate() {
   local maxLogFilesCount="${2:-5}"
 
   if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    Log::displayDebug "Log file ${file} doesn't exist yet"
     return 0
   fi
   local i
@@ -1817,16 +1820,6 @@ Linux::Wsl::cachedWslvar2() {
     Linux::Wsl::originalWslvar "${args[@]}"
 }
 
-# @description Display message using skip color (yellow)
-# @arg $1 message:String the message to display
-Log::displaySkipped() {
-  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    Log::computeDuration
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
-  fi
-  Log::logSkipped "$1"
-}
-
 # @description Display given text and complete the rest of the line with given character
 # @arg $1 text:String text to display
 # @arg $2 character:String (default:#) character to use to complete the line
@@ -2194,14 +2187,6 @@ Linux::Wsl::originalWslvar() {
   wslvar "$@" | sed -z '$ s/[\r\n]$//'
 }
 
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
-  fi
-}
-
 # @description install callback
 #   set file with root ownership and execution bit
 # @arg $1 fromFile:String
@@ -2415,7 +2400,7 @@ Retry::parameterized() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+1c+3PiRhL2z/wVHexb28kCEhLiihRbwcBmqbOND/DupVIpSkgDKCskooe9juP//bpHEi8bY69BcZL5traMNDM9j57u+ealfGFv55AQ5VKJ/srlkrT4N8GerGpSsVjSSmV6X1ZlbQ9Kuy/a3l7oB7oHsHft24/G2xT+F0W+kB/o/jgXuK7t76gvPFX/UkmTZVnZk2S5pJSE/tPAsv7NQX3MjM/dwAuNYGvd4fn6V1UMFvpPAY/qPz+ygs+MTV+YBylYU9Vn6F+TtPIeSFup4QYI/S/p/78h8yy23ZHg+fav4JOw/zSwTv9bMn2O59t/SSoL+08F6/Rv6oGOAaxr/c7y/m8vqvsm/StqKeH/sqao5P81WRL6TwPdZg9+MAdQhaNu87RZ70Gj1qud1LrNo+Pj7zOZ+CVFqXUh24i7RfZtBqDerp02u/XmUad9ed446l6eHVG36dvMGQVj+A4sx2Rf4sdjKIAsFdX4z1soHr8F6ZhLpU4GR2cnx7HYy/Pe0bfHoPuQ7ekDm/lQd0MnyGbed9pnKHXoehM9sFyn7xtjNtHzWGIsSebTh2anCQEliUOqWPDvM392I79irLP/qedOmX1mjT4yz8eWfokP2Oj/y8qK/8fQkrD/NBDb9wPG/xauItUDt7qoQ/Qn1sjjpies6m+BVftvTaauF1x47tCytzUNeA7/LxVVzv+KZcH/08AG/buOfdN2kAGOX5DHRv0rEf+TiwpywCLxv3JZFf4/Dex/UxhYToH6QIYZYxeyrsP6nEJlhYf/+2OD/eu2/TLbJ2y2f3l1/U9GNyDsPwWg/Ye+x30Ac66A+4GMoQfC9v8Z2GD/JhvqoR3sdvxXlPn8Ty0R/ytL6AaE/aeAB+1/H9ADgMemHvOZE/gQjBlcj12bgW35AbjDaJHFJ08Bf2QARhgZcldw2MfmDPzDlZe2O1p9NUZBrncTvd4H3b7Wb3wYWo7lj2FwAzovQ+DCgIEfeoyXwXAnE90xwXSZD45LZQxCzwH2xQow0GTwTRUkFCg82BOxwf4d96Xkf2+z/cuassr/FVmM/6lgjf2HPhuGNlhDuHFDuNYdbopmOJkCTQm5MZoD8PlGMVrnc3zGn11lgQUs279hW9td+uF4zvqPKpfo/Icki/M/qWC9/ic3/m923mMTN9jx+o+mlWP/rylIBjn/K4r9v1Swxv/7Y2bbBp0FAtPyyW9Xu/WipKhrw+SSmkH2ptt11wl0y2FezRtVs7wXZV8o8tKPpR3chtHPSo4Lvnup5HpEKEn4EUo3Zo932eNMBoe/n3+G3O+wEgS//PI9jW8OMk3b1c2G70A2mSpFFpPFoHs5FGZrbZAzIGobyI0Pbj+0u73z2lnzDnLhwe1lt9nBX9OD24tat/up3Wng0wU+tTs9KtfQ2t4Yusn+X7z4s/cU+1dn/l+heHKppAj+lwqE/SfWuWLjX2n9tmvo9l/F+Pces/+tLP1wbLL/spSM/6qkyBrZf1mc/0oHa+x/GvWCZFmGujkzaVkm7hUYJZ4bjvUrBhM3muHp9hQtH4zEBbyln75lMg+Mse6MLGfEsyBJs4yuMDyRO08KloMzSp+B4y6+9JMU5ja91MHtvZeVnOOa7MUOZua6SNpW2crcn6BX+Gr9r7d/j2ERUhn/VbU8n/9J/Pynqon931Sw6/Gf96JdjP9c8O74f5xBDi3i7iX29drxCP93nZGbiv2XlPn6j5LYvzj/lwp2zv+pF+3E/l032Kr585Ii1bBtZtABR2TjtAzuyUjGox9T3fchl9NDIv+BZfBzkMmJaKDXycNfx2Gst38iLFsx/832r2pz+0fij/avyML+U8Gu7X8btPch85+T82s0PY+hhdLkolCgfSq6uER7xVO00IFlW8ENXFvBGLLXlmO61z6MrIBXNbsz9jBn56+bPqzs//rODu6AP2f/p8zn/0WF1v/E/s/ucV//fAUrj85ga3nwNd5H7n/IWnn1/resyML/p4Fk8bEqF8t5Cf/JmWTdsUoUK0PrjlVFkf6doZXJ6B15xikzrKFlgDslFuSDGXrkgC1+fiTTOOm3zihpv33Ra7XPu9VcDh2i7t3kJui5X7FD/Idh9fxP1/Cs6fY+/cDxHP9f0sj/KyVJfP8lFazTP/sSeLoR0IRm1+e/ioq2ev9PUyTh/1PBuvNfDjJtE0xm2ESuG91zZN9y9n7Ix2bnpN1tYmgxm0leumEwDYOG5eFr5YFESDBsHCyiCOo83Umt+6H/voPDEY4//+l/bJ432p3+Ra33AeOV5vHMAT5rq9MK3w09g1ULJrsqOKFtZ6IXtH23XvBdoZ90+rbDkvl7nqYGj/L/xc1Bnye/0D19wgLm+T9LvyzvEp66o0pliLJtyP4WMu+GDs7RaOl6wLdZ6Chrsq+RpS0+zJtbIExnUoGWH7ARg7HnhqMxJMWu2XZSbH/WQjyX6rqyLUc7x6Bq1kBDcCd0/fdmJfw9lpBE8QdMvPjy6H3o8NUSv1IZsaA28F07DBjOAYcUA7KzG8VZSERQALZPljaGofhupi/44w+IriBlj7NJAzuryRaadaH0B0dUfwd/L8X/V/7bOxIGswY5olOKyyKPkxY3PKYHDGx3xLUyawV8EVU3KRWmP23/2H/f7pzVelimKmQxzlLZ7qU9uJ1ZxV3h4NYc3PXjUlAN7vIkANOxL8wA7d0bGeR3mCZOjnnsAy1Ie8wIsPOYKIsmunEwL3/SCSoV/7M1raMeJg6JRmo2aDno5Ry0BWkhWtQTFwLnOqafWMIsqSTwQvY04XLm6e1D1aED4CyuTVJ1+d0bjeqf43V6VBa8eRNZFprm1NZvWs4Q+w6KpX1E/Uq3bDJY2kc8nDfkobjVtoSHz383wsl0exzwOfwvnv8pRcH/UsFj+t/WN4A2zf/v679UVsX6bypY1v9Wl31m2MT/S2pxRf9FRRH7/6lg8f73o2vh+/v0H3AshlN2xWz+NLEcaxJOwKY3/IrHmAGyAl8fMboBglzr2kJmN+BEaITs1XKQtvABvXXanEmVKnDeptf8Sa5As9Npd/hDsQKfap3z1nkUplSgdf6+zX+rFWg0Ty55QGaF4lMWp82PzdOqlJll02h1L05rP31dBWKWgXVwHUBazZDH7K78cVHjOijzOiDjIebHCWryDqdTnLXOCp6UOaGMNG1wZ8Q2WbyjM1SYOhhbPvhEnad6MJ6l5TM2i5/eArpzhySN/44baXYma13rk4KrdLrxrHm35GSwGD7vcMR5iXfr8awBosK6yEpj6TRHMgfxoiLQgUm6guQvLC82Ls8usLE6D+a0NJxRTiPdG2ADJbu8vOH4bicMcSp2PbaMMUxckxY2+eYunTcb8VmBR53BATaqgCKBSYfijr5TpGOaqOmYKrAm1Ex0E9EPqNi8oTE5b8YB59m8LLNC8S9bZfZ5Y/LISxlzeaQXxom+414vVPrHWuek9mOzX2+f0ld7+o3aT90qluYpjRkv8CyU64FpZLfeaV30usi6TxvNh9sWhQ7n60Vrcqbrm7MkNMP9FQOiztJrt0/vZRDHiLpHlIok574GmK72qQvzqe9XC+oqffomUv+yc1r1lUqhYHzO4aQ1N/R8nX5gvyywL6RTv5DpNbFDxtUqBJPpK59uJOM/1QcH/518Afqp/L8sqXJZ499/LpdUwf/TwKr+ddsiD5A3/4T7fzLvAhKt/2uSuP+XCtbrf+6CKfAlmwCb9K8l3/9UtaJWkqPvP4j7f6lgif9vFzjeNtrIi3vQbLR6b6H3odUFYoVQr53DSRMuLxq1XrMBn1q9D+3LHkVt1ZtbL0aG92kkIoFfPbxijul6BXqIKx74hwsxLh6OArlfkfctRvxf9TAK+IKsYurhvCYXLfDmXCc31C079NhS/KckwBDHzQVsMkUOlTNspjvh9PCVUwgBAQEBAQEBAQEBAQEBAQEBAQGBV4r/A+pl674AeAAA"
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+1d+3Paxhb2z/wVp9g3ttMAEnpwhw6ZYlAa5trGF3ByO50OI6QF1AiJ6mHHdf2/33NWEq8YY8egJI2+TMdI+358Z885u6sWS3s7h4CoKAr9FSuKsPg3wZ4oq0K5rKhKhd5XZFHdA2X3VdvbC/1A9wD2rn37wXibwr9RFEvFge6PC4Hr2v6O5sJjx19QVFEUpT1BFBVJycY/DSyPvzlojJnxoRt4oRFsbTo8cvxFQVHKFYXGX5ZVKRv/NPDg+BdHVmCNHNdjzyqDBliV5fXjj8Kexl8sl3ESYDxRlYn/wpba+CC+8/F/mfthPsq5L12bDGljlf//DZlnse1qAk+S/2UR+S/Jaqb/pYJ1478l0c/xdPmvyHIm/1NBJv+/b6zjv6kHOgawrvUXK/p/Pmvub+K/hGSP7X9Rlbj+h3Ig438a6Go9+NkcQA2Outqp1uhBs96rn9S72tHx8U+5XPySotS7kG/G0yL/KgfQaNdPtW5DO+q0L8+bR93LsyOaNn2bOaNgDD+C5ZjsY/x4DCUQhbIc/3kF5eNXIBzzXGmSwdHZyXGc7eV57+jlMeg+5Hv6wGY+NNzQCfK5N532GeY6dL2JHliu0/eNMZvoRawx1iT3/q3W0SCgJHFIDSv+UybW1mMd/6eeO2X2mTV6xzwfe/o5MmDj+l+RVvw/GJqt/6kg5vc95H8FV9HQA2ddNCH6E2vkceplrPpHYJX/rcnU9YILzx1a9rbMwKf4f5Uy1/+FciWz/9LAhvF3Hfum7aAGOH5GGRvHX4r0P7EsoQ5YJv2vUpEz+Z8G9n8oDSynRHMgx4yxC3nXYX2uQuUzCf/Pxwb+67b9PO4TNvNfXNH/VBHFQMb/FID8D32PywDmXAGXAzlDDzLufx/YwH+TDfXQDna7/kvS3P6TFdL/KgKKgYz/KeBe/u8DSgDw2NRjPnMCH4Ixg+uxazOwLT8Adxg5WXySFPB3DmCEkaFwBYd97M7AP1x5abuj1VdjzMj1bqLX+6Db1/qND0PLsfwxDG5A53UIXBgw8EOP8ToY7mSiOyaYLvPBcamOQeg5wD5aAQaaDH6ogYAZZhLskdjAf8d9rvK/t5n/oiqt6v+SmK3/qWAN/0OfDUMbrCHcuCFc6w6nohlOpkAmISejOQCfHxRBdj5FZnzpJmdYwDL/DdvaruuH4yn+H1lU6PyXIGbn/1LB+vGf3Ph/2kWPTdxgx/4fVa3E8l+VUBnk+l852/9LBWvkvz9mtm3QWUAwLZ/kdq3bKAuSvDZMVOQcam+63XCdQLcc5tW9US3PZ1H+mVle+nFuB7dh9LNa4BnfPTfnRqRQUuZHmLsxe7zLH+dyuPz99hsU/oKVIPj9959ofXNQ07Rd3Wz6DuQTUyliTB6DPimhNPO1QcGAqG+gMD64fdvu9s7rZ9odFMKD28uu1sFf04Pbi3q3+77daeLTBT61Oz2q19Da3hq6if/Pdv7sPYb/8kz+SxRPVBQp0/9SQcb/hJ0rHP9M9tuuodvfCvn3HuL/Vlw/HJv4XxGS9V8WJFEl/lcqlYz/aWAN/6fRLEjcMjTNmUlumXhWYJTYNhzrVwwmbmTh6fYUmQ9GIgJe0U/fMpkHxlh3RpYz4kVQTrOCrjA8yXeeFCwHLUqfgeMuvvSTFOY2pdTB7ScvqwXHNdmzBcxMdFFuW9VW5vIEpcJnj/96/nsMq5DK+i/Llbn9J0j8/K+a7f+mgl2v/3wW7WL95xnvTv+PCyggI+6ew6+vHQ/o/64zclPhvyLN/T9Swv/s/F8q2Ln+T7NoJ/x33WCr9Oc1RVXDtplBBxxRGyc3uCeiMh79mOq+D4WCHpLyH1gGPweZnIgGep08fDsCYz3/SWHZCv03819W5/xHxR/5L4kZ/1PBrvm/DbX3PvrPlfNrpJ7HkKFkXJRKtE/1gbEp7RVPkaEDy7aCG7i2gjHkry3HdK99GFkBb2p+Z9rDXDv/utWHlf1f39nBNyCesv9T4fZ/WSL/X7b/s3t8Ov7cg1VEYbC1MriP94H7H6JaWTn/J4uSmMn/NJA4H2tiuVIU8J+YS/yONVKxcuR3rEmS8O8ceSajdyQZp8ywhpYB7pS0IB/M0CMBbPHzI7nmSb91Rkn77Yteq33erRUKKBB176YwQcn9FQvE7wyr53+6hmdNt/fpF46nyH9FJfkvKUJ2/z8VrBt/9jHwdCMgg2bX57/Kkrp6/0+VhEz+p4J1578c1LRNMJlhk3Ld7J6j9i3mPw15p3VO2l0NQ8v5XPLSDYNpGDQtD19L9yRCBcPGxSKKIM/TndS7b/tvOrgc4frzn/477bzZ7vQv6r23GE+ZxzMH+KyumhW+G3oGq5VMdlVyQtvORS9o+259xnelfjLp2w5L7PcimQYP6v+Lm4M+T36he/qEBczzfxN+X94lPHVH1eoQ87Yh/2fIvBs6OEerpesB32aho6zJvkaetviwbM5AmM5yBXI/YCcGY88NR2NIql237aTa/qyHeCm1dXVbjnaOQbW8gURwJ3T992Yl/A3WkLLiD5h48eXRm9Dh3hK/Wh2xoD7wXTsMGNqAQ4oB+dmN4jwkWVAA9k+eNoah/Ho2XvD33xBdQcof55MOdlaTLXTrQu0Pjqj9Dv5eiv+v4ss7ygxmHXJEpxSXszxOetzwmB4wsN0RH5VZL+CLqLlJrTD9afuX/pt256zewzrVII9xlur2SdqD2xkr7koHt+bgrh/XglpwV6QMMB37yAxQX78QQXyNaeLkWMY+kEPaY0aAk8fEvMjQjYN5/ZNJUK36H6xpA8dh4lDWqJoNWg5KOQe5ICxEi2biQuB8jOkn1jBPQxJ4IXtc5mLu8f1DzaED4CxuTdJ08fULldpf4G16MC948SJiFlJzaus3LWeIcwezpX1E/Uq3bCIs7SMezjvyMLvVtoT7z383w8l0ezrgI/W/6PtPMj//KcmZ/Z8KHhr/bX0DapP9f8/3/6Ts/k86yL7/9H1jmf9bdfvNsMn+U1DYL9t/ZUnKzn+kgsX7/w/uhezv03+Auhicsitm86eJ5ViTcAI2veFXfMYMUCv09RGjG0Coa19bqNkPuCI8QuvFclBt5Qpd61Sb5SpU4bxNr/mTWAWt02l3+EO5Cu/rnfPWeRQmVaF1/qbNf8tVaGonlzwgt2LiURGn2jvttCbkZsU0W92L0/qvn9eAWMvENrgOoFnFUI/dXf3jqsZtkOZtQI2XNH9uoCTv0JzmVsus4kmdE5OBzEZ3Ztgkzls6Q4epg7Hlg0+m01QPxrO03GK3+Ok9oDuXqKTz33Enzc7kret9GuAanW490+6WhAxWw+cTjmwesrv02GqEqLIuWiVx7mQjm4PYqQx0YJauoPkL7uXm5dkFdlbn3pKW1BkqaaR7A+ygZJefdxzf7YYhmuLXY8sYw8Q1ybHNN/fpvOGIW4UeTQYH2KgKkgAmHYo8+lESjslQ1zFVYE2om+gmqh9QtXlHY3LejQNuZ/G6zCrFv2yW2+edySMvFczzo3Fh3NBz3OuFRv9S75zUf9H6jfYpfbWp36z/2q1hbR7TmbGDb6Fe97gRuo1O66LXRavrtKnd37eY6XDuL1xTMl3fnSUhD8cfGBBNll67ffpJAXGMaHpEqSjnwucA09Xfd2Hu+vjsjLpSn76J1b/snNZ8qVoqGR8KJrsqDD1fpx84L0vsI42pX8r1NJyQcbNKwWT6letUyfpP7cHFfyf/B4DH+v8rgixWVP79/4oiZ/ZfGlgdf922SAIUzS9w/1PkU0Cg/R9VyO5/poL14z8XwRT4nE2gTeOvJt9/ldWyqojR9z+y+5+pYEn/3y5wvW22US/ugdZs9V5B722rC6QVQqN+DicaXF406z2tCe9bvbftyx5FbTW0rVcjx+c0KiKBXzu8Yo7peiV6iBse+IcLMS7ujwKFP1DvW4z4v9phFPARtYqph3ZNIXLwF1ynMNQtO/TYUvzHJMAQxy0EbDJFHapg2Ex3wunhV65CZMiQIUOGDBkyZMiQIUOGbwD/B7+tw7MAeAAA"
 
 declare -gx embed_dir_conf_dir="${TMPDIR:-/tmp}/conf_dir"
 
diff --git a/installScripts/CodeCheckers b/installScripts/CodeCheckers
--- a/installScripts/CodeCheckers
+++ b/installScripts/CodeCheckers
@@ -549,9 +549,12 @@ InstallScripts::command() {
     local hookName="$1"
     # shellcheck disable=SC2154
     hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
-    if [[ -x "${hook}" ]]; then
+    if [[ -n "${hook}" && -f "${hook}" && -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/hooks/preInstall.sh
-      source "${hook}" || exit 1
+      source "${hook}" || {
+        Log::displayError "${scriptName} - unable to load hook '${hook}'"
+        exit 1
+      }
     fi
   }
   local globalStatsFile="${logsDir}/${scriptName}-global.stat"
@@ -1319,7 +1322,7 @@ Log::rotate() {
   local maxLogFilesCount="${2:-5}"
 
   if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    Log::displayDebug "Log file ${file} doesn't exist yet"
     return 0
   fi
   local i
diff --git a/installScripts/Fortune b/installScripts/Fortune
--- a/installScripts/Fortune
+++ b/installScripts/Fortune
@@ -572,9 +572,12 @@ InstallScripts::command() {
     local hookName="$1"
     # shellcheck disable=SC2154
     hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
-    if [[ -x "${hook}" ]]; then
+    if [[ -n "${hook}" && -f "${hook}" && -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/hooks/preInstall.sh
-      source "${hook}" || exit 1
+      source "${hook}" || {
+        Log::displayError "${scriptName} - unable to load hook '${hook}'"
+        exit 1
+      }
     fi
   }
   local globalStatsFile="${logsDir}/${scriptName}-global.stat"
@@ -1436,7 +1439,7 @@ Log::rotate() {
   local maxLogFilesCount="${2:-5}"
 
   if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    Log::displayDebug "Log file ${file} doesn't exist yet"
     return 0
   fi
   local i
@@ -1866,16 +1869,6 @@ Linux::Wsl::cachedWslvar2() {
     Linux::Wsl::originalWslvar "${args[@]}"
 }
 
-# @description Display message using skip color (yellow)
-# @arg $1 message:String the message to display
-Log::displaySkipped() {
-  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    Log::computeDuration
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
-  fi
-  Log::logSkipped "$1"
-}
-
 # @description Display given text and complete the rest of the line with given character
 # @arg $1 text:String text to display
 # @arg $2 character:String (default:#) character to use to complete the line
@@ -2180,14 +2173,6 @@ Linux::Wsl::originalWslvar() {
   wslvar "$@" | sed -z '$ s/[\r\n]$//'
 }
 
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
-  fi
-}
-
 # @description Retry a command several times depending on parameters
 # @arg $1 maxRetries:int    $1 max retries
 # @arg $2 delay:int between attempt
@@ -2367,7 +2352,7 @@ File::garbageCollect() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2W32/aMBDH88xfcQuIQivHdnDih4lJe2i1p1VaV+2B0ikFR4kUAooTKlr6v88EonaoglIVqnX3ebFkfy/n8/0Ah1p7hxmk5y1WLj32dK2wuPCZYLLDWMfsS8GEBd7+r2ZZhc6DDMC61clG3bbzfxSHOjeBjshQTYlKp3uphpfm35e+6/rCYpxLn2P+D8F6/uM0V1kwyOOpcoZvVA0vzb/scCmF6X8uPC4x/4dgc/6HsZ4kwexsnOVFqrSjo9f42JJ/zpi/yr/LXWl0LnOF6X/21sE+x3+e//onehOndFEDtdpaulttuK8BxCH0ekBCoCof0HB5SCKVTMhgPBoF6VBDs2mEsFnkDIO8EtqN+4tv579+n53/+Hn5/fTiwYYu2NyuzhsEul04jo+h36/2Vt8BMoXV96H5hZrCpWmRJM+oBuNbHcy2iJJxMljc61H0GfJIpaUuM6Lx6Gsaj4KkazdaYWyMaKEzqqMgU3TpoVyA5LOJghDmpSWAjooQSAoc5qCV8XUKRMGRrl87J7TVu6ZO/6R95RjbRv2K14/admlYhbbhsSsPq/jMo5vnfHpV85rzKjCiwWestChSrfK/YjLbYVx7qL13FSLvxW7zfyHd3cfW3/+Ot5z/zPOEJxbz3zPHOP8PwKb5j2Ph47Nb/9+96g/g9v4X6/0vOj72/yFY9f8dtj+CIAiCIAiCIAiCIAiCIMjH4g9E5sThACgAAA=="
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2XQW/aMBTHc+ZTvAVEoZVjOzjxYWLSDq12WqV10w6UTik4SqQQUJxQ0dLvPicQrasqKFWhWvd+F0v233m2/34P41Br7zCD9Lyy5dJjD9saiwufCSZ7jPVMvxRMWODtf2mWVeg8yACsG51s1G0b/0dxqHMd6IiM1ZyodL6X2/Bc/33pu64vLMa59Dn6fwge+x+nucqCUR7PlTN+pdvwXP9lj0spTP5z4XGJ/h+Czf6PYz1LgsXZNMuLVGlHRy+JscV/zpi/9t/lrjQ6l7nC5D977c0+xX/uf/MDvY5TWt6BRuOR3Z0u3DUA4hAGAyAhUJWPaLgaJJFKZmQ0nUyCdKyh3TZC2CxyxkFeC+3W3cWX85+/zs6/ff/x9fTi3oY+2Nyux1sE+n04jo9hOKz71t8BMof196H9iZqLS9MiSZ5QjaY3OlhsESXTZFSu64/oI+SRSitdZkTTyec0ngRJ3251wthMooXOqI6CTNFVhKoBki9mCkJYVjMBdFSEQFLgsAStTKxTIAqOdPPKOaGdwRV1hifdS8fMbTUvefOoa1cT661tOOw6wnp/5tDNcT5cqjnNZb0xosFnrJpRpFrlf+3JdIdx477x1rcQeSt2q/+ldPcYW3//e96q/jPPE54o679nhrH+H4BN9R/Lwvtnt/y/fdEDcGv+C1HmP2eedOXq/SfM3wDM/wNg8r98zpQ1wNgPt1gGEARBEARBEARBEARBEARB3ge/AfZKJf0AKAAA"
 
 declare -gx embed_dir_conf_dir="${TMPDIR:-/tmp}/conf_dir"
 
diff --git a/installScripts/Fzf b/installScripts/Fzf
--- a/installScripts/Fzf
+++ b/installScripts/Fzf
@@ -572,9 +572,12 @@ InstallScripts::command() {
     local hookName="$1"
     # shellcheck disable=SC2154
     hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
-    if [[ -x "${hook}" ]]; then
+    if [[ -n "${hook}" && -f "${hook}" && -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/hooks/preInstall.sh
-      source "${hook}" || exit 1
+      source "${hook}" || {
+        Log::displayError "${scriptName} - unable to load hook '${hook}'"
+        exit 1
+      }
     fi
   }
   local globalStatsFile="${logsDir}/${scriptName}-global.stat"
@@ -1431,7 +1434,7 @@ Log::rotate() {
   local maxLogFilesCount="${2:-5}"
 
   if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    Log::displayDebug "Log file ${file} doesn't exist yet"
     return 0
   fi
   local i
@@ -1982,16 +1985,6 @@ Linux::Wsl::cachedWslvar2() {
     Linux::Wsl::originalWslvar "${args[@]}"
 }
 
-# @description Display message using skip color (yellow)
-# @arg $1 message:String the message to display
-Log::displaySkipped() {
-  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
-    Log::computeDuration
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
-  fi
-  Log::logSkipped "$1"
-}
-
 # @description Display given text and complete the rest of the line with given character
 # @arg $1 text:String text to display
 # @arg $2 character:String (default:#) character to use to complete the line
@@ -2303,14 +2296,6 @@ Linux::Wsl::originalWslvar() {
   wslvar "$@" | sed -z '$ s/[\r\n]$//'
 }
 
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
-  fi
-}
-
 # @description Retry a command several times depending on parameters
 # @arg $1 maxRetries:int    $1 max retries
 # @arg $2 delay:int between attempt
@@ -2490,7 +2475,7 @@ File::garbageCollect() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2WzW7TQBCAc/ZTTF1QpLZO7MY/UlAOIUnVSGldta6QKKhy7HW8imtba7shKTnDmQOPAu/TJ2Fs9ydARYqaFgH7XfZvdnZ2Z2d2a/XKoyMjhqblpWJo8mJ5TUVRdXl7W9MNNe83VEWrgPb4plUqWZLaDKAySYJfyi0b/0up1WtDO/Ell5xLJDx/lNtwX/9rstEwjEZFVhRDl7n/n4If/U/DlDDbSek5qbkrug339b8uq6qqb6P/VU1RuP+fgl/735t5tcR/6BpL/K+g42/8rzV09L+mN9QKyKvY4DL+c/+vr9WHNKznd0AQyLs4YinsvN457fZ22scD67Rj7u2197utKhuBJHk0IAmWPnVdEmJlFERDENdqI5qK1cX5HetwcHo7XXx2cYfWuSgIhbA5MA+PWuJwtNmUlK03gjdqjpg9LWqbzYlPU4L1YcRcwprDwHbG2ExiGobYlrHuB80pCYJokteJXYpl+SQaehEqIyTERhwV97vJiIutM5uNbwVjFp3F6fW6frCZS4l3Hop5YKG1eAyEjvwUdPk5vBEkqbQPEt9mcdER2NMoS4GRc8ISUnQ5URAxqJbHUe57Xi1GyvWhevnxK1z1lNbC5ecvRbu0Fy4/fBIXrWrnB3pjU4yrUTKBaop7BqkDF3N4D/mZgBSCIle/m4uOOBj0rL65f9rtH177BRU5LsRZ4rvAzlzKoFAWJKLwp+8rZ7Usz//58MPWWPb+G9tl/jdkTVM1FfO/rqgNnv+fgsX8v75ahHXomrBvWtDr9q0tsHb7R7DTH/Sg096Hlz04Pui2rV4XXvWtXfPYykX7nd7KzUA7jkgKWQx4nWFMpoA7dmk4SsAOXfCy2WwKDibfgKQ0CgXqwckJrAG+WQdta3cuQqsFG88uds293rxeQyX5kW3A27cvIPVJKADkcq1r+eaPoqLgUeFKreTlem/Hi/ASF3Wt4wOCT5njE2cMSZQxh7TqGJ71MAsCHC+77tKSL/O7/l8e/7MHfwCX/v9kvYx//PY1tPz/p8sNjcf/U4DxnyWsyAEzngJ+TgF5RD9uApitIv5nV+EvzGhIU6AoMLHxT66IEGQOda/6g+K/OomisT1Fj+NMybMTl//qOBwOh8PhcDgcDofD4XA4nH+Sb4hDbIQAKAAA"
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2XX2/iRhDAefanmDhXIV3OYIP/SFRUokAUJBJHiaNKvZwiY6/xCse21nYopDy3z324j3L9PvkknbXzh16j49oQqqr7e2H/zM7M7uyMl0az9uqoiGUY/FezDHX994Gapptqq2WYls7HLV0zamC8vmu1WpHlLgOozbPoi3Kb5v+jNJqNiZuFik9uFBLfvMpt+Nr4G6rVtqx2TdU0y1RF/HfB5/GncU6Y6+X0hjT8Ld2Gr42/qeq6brYw/rqhaSL+u+DL8Q+WQSMLX2pjQ/w1DPxj/I22ifE3zLZeA3UbG9zE/zz++3vNCY2b/A5IEvkpTVgOhz8eXg2Gh72LsXPVt4+PeyeDbp1NQVECGpEMf0Pq+yTGxjRKJiDvNaY0l+vr6/vO2fjqabn85vYZrStZkkphe2yfnXflyfSgo2jvLqVg2pkyd1G2DjrzkOYE25OE+YR1JpHrzbCbpTSOsa9iO4w6CxJFyZy3iVuJFXwRjYMElRESYydNyvvdYcTH3rXLZk+CKUuu0/zBbhgdcCn52UOxTx30Fo+B0GmYg6l+A5eSolT+QRa6LC0HIneRFDkwckNYRsohL4kSBvXqOKp9r+rlTGUf6ne//g73I5W3cPfxU9mv/IW7X36T173q8QN99ClFa5TMoZ7jnkHpw+0KfgZ+JqDEoKn1P63FQJyOh87IPrkajM4e4oKKPB/SIgt9YNc+ZVAqizJZ+rfvq2C7bK7/fPplNjZ9/61WVf8t1TB0Q8f6b2p6W9T/XbBe//e3i7QPAxtObAeGg5HzDpyj0TkcjsZD6PdO4PshXJwOes5wAD+MnCP7wuGio/5w626gH+ckhyIFvM4wIwvAHfs0nmbgxj4ExXK5AA+Lb0RymsQSDeD9e9gD/Gad9pyjlQzdLrx9c3tkHw9XzQYq4Uf2Fj58+BbykMQSAJfrPsh3PheVpYBK92qVgOt9mi/TS17XtY8fEPyUeSHxZpAlBfNIt4np2YyLKML5aug5LdzM343/5vxfvvgBuOn9p6ktnv8a/u03rJbF819tqyL/dwHmf5GxsgYsRQn4awngGf26BWC5jfxf3qc/N5IvUpLhbtHSksY0h+8elz8aqSbmLj7bNRmiwqM++CTNw64GUYJvxYi/bJXrxCcQ4IP1EtcAzJNk5i7wqqBJJXAz/59UHIFAIBAIBAKBQCAQCAQCgUCwK/4AKrJI5gAoAAA="
 
 declare -gx embed_dir_conf_dir="${TMPDIR:-/tmp}/conf_dir"
 
diff --git a/installScripts/KubeDefaultConfig b/installScripts/KubeDefaultConfig
--- a/installScripts/KubeDefaultConfig
+++ b/installScripts/KubeDefaultConfig
@@ -572,9 +572,12 @@ InstallScripts::command() {
     local hookName="$1"
     # shellcheck disable=SC2154
     hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
-    if [[ -x "${hook}" ]]; then
+    if [[ -n "${hook}" && -f "${hook}" && -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/hooks/preInstall.sh
-      source "${hook}" || exit 1
+      source "${hook}" || {
+        Log::displayError "${scriptName} - unable to load hook '${hook}'"
+        exit 1
+      }
     fi
   }
   local globalStatsFile="${logsDir}/${scriptName}-global.stat"
@@ -906,60 +909,41 @@ Log::displaySkipped() {
 
 # @description upgrade given binary to latest github release using retry
 #
-# releaseUrl argument : the placeholder @latestVersion@ will be replaced by the latest release version
+# downloadReleaseUrl argument : the placeholder @latestVersion@ will be replaced by the latest release version
 # @arg $1 targetFile:String target binary file (eg: /usr/local/bin/kind)
-# @arg $2 releaseUrl:String github release url (eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64)
+# @arg $2 downloadReleaseUrl:String github release url (eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64)
 # @arg $3 softVersionArg:String parameter to add to existing command to compute current version
 # @arg $4 softVersionCallback:Function function called to get software version (default: Version::getCommandVersionFromPlainText will call software with argument --version)
 # @arg $5 installCallback:Function function called to install the file retrieved on github (default copy as is and set execution bit)
-# @arg $6 parseGithubVersionCallback:Function function to call to filter the version retrieved from github (Default: Version::parse)
+# @arg $6 softVersionCallback:Function function to call to filter the version retrieved from github (Default: Version::parse)
 # @stdout log messages about retry, install, upgrade
 # @env SOFT_VERSION_CALLBACK pass softVersionCallback by env variable instead of passing it by arg
-# @env PARSE_VERSION_CALLBACK pass parseGithubVersionCallback by env variable instead of passing it by arg
 # @env INSTALL_CALLBACK pass installCallback by env variable instead of passing it by arg
+# @env CURL_CONNECT_TIMEOUT number of seconds before giving up host connection
 Github::upgradeRelease() {
   local targetFile="$1"
-  local releaseUrl="$2"
+  local downloadReleaseUrl="$2"
   local softVersionArg="${3:---version}"
   local softVersionCallback="${4:-${SOFT_VERSION_CALLBACK:-Version::getCommandVersionFromPlainText}}"
   # shellcheck disable=SC2034
   local installCallback="${5:-${INSTALL_CALLBACK:-}}"
   local parseGithubVersionCallback="${6:-${PARSE_VERSION_CALLBACK:-Version::parse}}"
-  local latestVersion
+
   local repo
+  repo="$(Github::extractRepoFromGithubUrl "${downloadReleaseUrl}")"
+  local releasesUrl="https://api.github.com/repos/${repo}/releases/latest"
 
-  repo="$(Github::extractRepoFromGithubUrl "${releaseUrl}")"
-  Github::getLatestRelease "${repo}" latestVersion ||
-    Log::fatal "Repo ${repo} latest version not found"
-  if [[ "$(type -t "${parseGithubVersionCallback}")" = "function" ]]; then
-    latestVersion="$(${parseGithubVersionCallback} <<<"${latestVersion}")"
-  fi
-  Log::displayInfo "Repo ${repo} latest version found is ${latestVersion}"
-
-  local currentVersion="not existing"
-  if [[ -f "${targetFile}" ]]; then
-    currentVersion="$(${softVersionCallback} "${targetFile}" "${softVersionArg}" 2>&1 || true)"
-  fi
-  if [[ "${currentVersion}" = "${latestVersion}" ]]; then
-    Log::displayInfo "${targetFile} version ${latestVersion} already installed"
-  else
-    if [[ -z "${currentVersion}" ]]; then
-      Log::displayInfo "Installing ${targetFile} with version ${latestVersion}"
-    else
-      Log::displayInfo "Upgrading ${targetFile} from version ${currentVersion} to ${latestVersion}"
-    fi
-    local url
-    url="$(echo "${releaseUrl}" | sed -E "s/@latestVersion@/${latestVersion}/g")"
-    Log::displayInfo "Using url ${url}"
-    newSoftware=$(mktemp -p "${TMPDIR:-/tmp}" -t github.newSoftware.XXXX)
-    Retry::default curl \
-      -L \
-      -o "${newSoftware}" \
-      --fail \
-      "${url}"
-
-    Github::defaultInstall "${newSoftware}" "${targetFile}" "${latestVersion}" "${installCallback}"
-  fi
+  # shellcheck disable=SC2317
+  extractVersion() {
+    Version::githubApiExtractVersion | "${parseGithubVersionCallback}"
+  }
+  FILTER_LAST_VERSION_CALLBACK=${FILTER_LAST_VERSION_CALLBACK:-extractVersion} \
+    SOFT_VERSION_CALLBACK="${softVersionCallback}" \
+    Web::upgradeRelease \
+    "${targetFile}" \
+    "${releasesUrl}" \
+    "${downloadReleaseUrl}" \
+    "${softVersionArg}"
 }
 
 # @description clone the repository if not done yet, else pull it if no change in it
@@ -1580,7 +1564,7 @@ Log::rotate() {
   local maxLogFilesCount="${2:-5}"
 
   if [[ ! -f "${file}" ]]; then
-    Log::displaySkipped "Log file ${file} doesn't exist yet"
+    Log::displayDebug "Log file ${file} doesn't exist yet"
     return 0
   fi
   local i
@@ -1776,69 +1760,69 @@ Github::extractRepoFromGithubUrl() {
   echo "${result}"
 }
 
-# @description Retrieve the latest version number of a github release using Github API using retry
-# repo arg with fchastanet/bash-tools value would match https://github.com/fchastanet/bash-tools
-# @arg $1 repo:String repository in the format fchastanet/bash-tools
-# @arg $2 resultRef:&String reference to a variable that will contain the result of the command
-# @stdout log messages about retry
-Github::getLatestRelease() {
-  local repo="$1"
-  # we need to pass the result through a reference instead of output directly
-  # because retry can output too
-  local -n resultRef=$2
-  resultRef=""
-  local resultFile
-  resultFile="$(mktemp -p "${TMPDIR:-/tmp}" -t githubLatestRelease.XXXX)"
-  # Get latest release from GitHub api
-  if Retry::default curl \
-    -L \
-    -o "${resultFile}" \
-    --fail \
-    --silent \
-    "https://api.github.com/repos/${repo}/releases/latest"; then
-    # shellcheck disable=SC2034
-    resultRef="$(Version::githubApiExtractVersion <"${resultFile}")"
-    return 0
-  fi
-  # display curl result in case of failure
-  cat >&2 "${resultFile}"
-  rm -f "${resultFile}"
+# @description extract version number from github api
+# @noargs
+# @stdin json result of github API
+# @exitcode 1 if jq or Version::parse fails
+# @stdout the version parsed
+# @require Linux::requireJqCommand
+Version::githubApiExtractVersion() {
+  jq -r ".tag_name"
 }
 
-# @description intermediate callback that is used by Github::upgradeRelease
-# or Github::installRelease
-# if installCallback is not set, it allows to:
-#   - copy the downloaded file to the right target file
-#   - and set the execution bit
-# else
-#   installCallback is called with newSoftware, targetFile, version arguments
-# fi
-# @warning do not use this function as callback for Github::upgradeRelease or Github::installRelease, as it would result to an infinite loop
-# @arg $1 newSoftware:String the downloaded software file
-# @arg $2 targetFile:String where we want to copy the file
-# @arg $3 version:String the version that has been downloaded
-# @arg $4 installCallback:Function (optional) the callback to call with 3 first arguments
-# @env SUDO String allows to use custom sudo prefix command
-# @exitcode * on failure
-# @see Github::upgradeRelease
-# @see Github::installRelease
-# @internal
-Github::defaultInstall() {
-  local newSoftware="$1"
-  local targetFile="$2"
-  local version="$3"
-  local installCallback=$4
-  # shellcheck disable=SC2086
-  if ! ${SUDO:-} test -d "${targetFile%/*}"; then
-    ${SUDO:-} mkdir -p "${targetFile%/*}"
+# @description upgrade given binary to latest release using retry
+#
+# releasesUrl argument : the placeholder @latestVersion@ will be replaced by the latest release version
+# @arg $1 targetFile:String target binary file (eg: /usr/local/bin/kind)
+# @arg $2 releasesUrl:String url on which we can query all available versions (eg: "https://go.dev/dl/?mode=json")
+# @arg $3 downloadReleaseUrl:String url from which the software will be downloaded (eg: https://storage.googleapis.com/golang/go@latestVersion@.linux-amd64.tar.gz)
+# @arg $4 softVersionArg:String parameter to add to existing command to compute current version
+# @stdout log messages about retry, install, upgrade
+# @env FILTER_LAST_VERSION_CALLBACK a callback to filter the latest version from releasesUrl
+# @env SOFT_VERSION_CALLBACK a callback to execute command version
+# @env PARSE_VERSION_CALLBACK a callback to parse the version of the existing command
+# @env INSTALL_CALLBACK a callback to install the software downloaded
+# @env CURL_CONNECT_TIMEOUT number of seconds before giving up host connection
+Web::upgradeRelease() {
+  local targetFile="$1"
+  local releasesUrl="$2"
+  local downloadReleaseUrl="$3"
+  local softVersionArg="${4:---version}"
+  # options from env variables
+  local filterLastVersionCallback="${FILTER_LAST_VERSION_CALLBACK:-Version::parse}"
+  local softVersionCallback="${SOFT_VERSION_CALLBACK:-Version::getCommandVersionFromPlainText}"
+  local installCallback="${INSTALL_CALLBACK:-}"
+  local latestVersion
+  latestVersion="$(Web::getReleases "${releasesUrl}" | ${filterLastVersionCallback})" || {
+    Log::displayError "latest version not found on ${releasesUrl}"
+    return 1
+  }
+  Log::displayInfo "Latest version found is ${latestVersion}"
+
+  local currentVersion="not existing"
+  if [[ -f "${targetFile}" ]]; then
+    currentVersion="$(${softVersionCallback} "${targetFile}" "${softVersionArg}" 2>&1 || true)"
   fi
-  if [[ "$(type -t "${installCallback}")" = "function" ]]; then
-    ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
+  if [[ "${currentVersion}" = "${latestVersion}" ]]; then
+    Log::displayInfo "${targetFile} version ${latestVersion} already installed"
   else
-    ${SUDO:-} mv "${newSoftware}" "${targetFile}"
-    ${SUDO:-} chmod +x "${targetFile}"
-    hash -r
-    ${SUDO:-} rm -f "${newSoftware}" || true
+    if [[ -z "${currentVersion}" ]]; then
+      Log::displayInfo "Installing ${targetFile} with version ${latestVersion}"
+    else
+      Log::displayInfo "Upgrading ${targetFile} from version ${currentVersion} to ${latestVersion}"
+    fi
+    local url
+    url="$(echo "${downloadReleaseUrl}" | sed -E "s/@latestVersion@/${latestVersion}/g")"
+    Log::displayInfo "Using url ${url}"
+    newSoftware=$(mktemp -p "${TMPDIR:-/tmp}" -t web.newSoftware.XXXX)
+    Retry::default curl \
+      -L \
+      --connect-timeout "${CURL_CONNECT_TIMEOUT:-5}" \
+      -o "${newSoftware}" \
+      --fail \
+      "${url}"
+
+    Github::defaultInstall "${newSoftware}" "${targetFile}" "${latestVersion}" "${installCallback}"
   fi
 }
 
@@ -2300,14 +2284,56 @@ EOF
   fi
 }
 
-# @description extract version number from github api
-# @noargs
-# @stdin json result of github API
-# @exitcode 1 if jq or Version::parse fails
-# @stdout the version parsed
-# @require Linux::requireJqCommand
-Version::githubApiExtractVersion() {
-  jq -r ".tag_name"
+# @description Retrieve the latest version number of a web release
+# @arg $1 releaseListUrl:String the url from which version list can be retrieved
+# @stdout log messages about retry
+# @env CURL_CONNECT_TIMEOUT number of seconds before giving up host connection
+Web::getReleases() {
+  local releaseListUrl="$1"
+  # Get latest release from GitHub api
+  Retry::default curl \
+    -L \
+    --connect-timeout "${CURL_CONNECT_TIMEOUT:-5}" \
+    --fail \
+    --silent \
+    "${releaseListUrl}"
+}
+
+# @description intermediate callback that is used by Github::upgradeRelease
+# or Github::installRelease
+# if installCallback is not set, it allows to:
+#   - copy the downloaded file to the right target file
+#   - and set the execution bit
+# else
+#   installCallback is called with newSoftware, targetFile, version arguments
+# fi
+# @warning do not use this function as callback for Github::upgradeRelease or Github::installRelease, as it would result to an infinite loop
+# @arg $1 newSoftware:String the downloaded software file
+# @arg $2 targetFile:String where we want to copy the file
+# @arg $3 version:String the version that has been downloaded
+# @arg $4 installCallback:Function (optional) the callback to call with 3 first arguments
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode * on failure
+# @see Github::upgradeRelease
+# @see Github::installRelease
+# @internal
+Github::defaultInstall() {
+  local newSoftware="$1"
+  local targetFile="$2"
+  local version="$3"
+  local installCallback=$4
+  # shellcheck disable=SC2086
+  if ! ${SUDO:-} test -d "${targetFile%/*}"; then
+    ${SUDO:-} mkdir -p "${targetFile%/*}"
+  fi
+  if [[ "$(type -t "${installCallback}")" = "function" ]]; then
+    ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
+  else
+    ${SUDO:-} mv "${newSoftware}" "${targetFile}"
+    ${SUDO:-} chmod +x "${targetFile}"
+    hash -r
+    ${SUDO:-} rm -f "${newSoftware}" || true
+  fi
 }
 
 # @description installs file to given directory
@@ -2410,6 +2436,15 @@ Linux::getDistributorId() {
     source /etc/os-release
     echo "${ID}"
   )
+}
+
+# @description ensure command jq is available
+# @exitcode 1 if jq command not available
+# @stderr diagnostics information is displayed
+Linux::requireJqCommand() {
+  if [[ "${SKIP_REQUIRE_JQ:-0}" = "0" && "${SKIP_REQUIRES:-0}" = "0" ]]; then
+    Assert::commandExists jq
+  fi
 }
 
 # @description ensure command git is available
@@ -2638,15 +2673,6 @@ Linux::Wsl::requireWsl() {
   fi
 }
 
-# @description ensure command jq is available
-# @exitcode 1 if jq command not available
-# @stderr diagnostics information is displayed
-Linux::requireJqCommand() {
-  if [[ "${SKIP_REQUIRE_JQ:-0}" = "0" && "${SKIP_REQUIRES:-0}" = "0" ]]; then
-    Assert::commandExists jq
-  fi
-}
-
 # @description call simply original wslpath command
 # @arg $@ args:String[] args to pass to wslpath
 # @exitcode * wslpath exit code
@@ -2693,7 +2719,7 @@ File::garbageCollect() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2X/WvaQBjH83P+imdVUMc0uZgXaCesq44KXS3UUphKOJNzCV4T8RI7Wvq/75KlVBxTWa3t2PP5IS93z72E7/NyaWjKi6NLHMvK7sSx9OX7Iwoxbb1JdEL0rN1pOkQB6+W3piipSOgcQLkVfK3dpv5/lIbWGFMR1H22qLNo8SLesK3+tuEYumMr0gscy0b998Gq/l58M+MsCeNINPwdecP2+tuEGETqb1oGxv9eWK//NB0zL+GNOxE8Y41N+hPDzPV3dMsyLVPqbzukqYC+s69cw3+uf+mdNg4jTQqsquEEBgMoSxe4oZEvBoX6IxiNjiAJWKQCiDideww+VotOeHIYkJPU1EmovvY3IduzGv9hlLA59ZJwwV4h/2f138jzP8H8vxfW658FeX0mSG7z12ts0t+yrVx/w3SMpnyWvTrm//1Q5P9MX7W0W9QStHtw3utDp93tf4D+afcSvnTPOnByfA6fO3B10T7ud9pw3e2f9q76mWn3pLPzbRR1rT4BLZ4luU9Ll37ybREsF7iSCBjnXsC8aVHsWpoMDi1KOX+qf3+aSVpcXJJWZTBMPw0DGF5DOa+UruyujYZlqLyxArk5/p95+FM2x78p//ny81/TIE07O//bxDEx/vfB8vmvBH4MUZyAYAlQHlLBhCrogrnFS6tczZ+gflZTXfcujMLE/eXePP0eRi6Pqc9816Ocj6k3rdbgXkZEGhWjbqDyvnIEbEE5lO+XZ344klbZssuN2xw3H9R8F3BL5YWnXujDJJ7DUI7tff12cXj4ODBroUm2wYMtdn7w2ww/VlqygH9LgYwgCIIgCIIgCIIgCIIgCLLCT6ikOH4AKAAA"
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+2W8WvaUBDH83P+irMWXGGavJi8QDfHuuqosFWhKYWpjJg8l2BMxPfitv71ey+ztSvUlFVtx+7zQwJ5xyXhe9+7axjazjElruOoO3Ed8+79Bo3Y1GwSkxBTPXebLtHA2f2naVrOhb8A0L7zZGNc2fk/SsNojH0e1UO2rLN0uZNqeKz+1HIt06WarALXoaj/Privf5DN5gkTcZbyRrilani8/pQQi0j9bcdC/++FzfpP8zELRNK45tET3lGmP2naSn9iOq7lujKOUNkINDC39pcb+M/1r1aMnC+McZwaUn6QQut6PIHBAA5lKcz8NOSDVRWMYDR6AyJiqQ7As3wRMHj7anUI68JRSY70Saw/978h5dz3f5wKtvADES/ZM/R/Nf+tov8T7P97YbP+ytz1OSdFzF+/o0x/hzqF/pbtWk2q+r8rZwL2/30g+7/q/Upfvbpd9Cq0e3De86DT7nqvwTvrXsDH7qcOnJ6cw4cOXPbbJ16nDVdd76x36anQ7mln65+xmmf1CRjZXBQ1LUt6Xds8ujvYqjxiSRJELJiuhlzLkOYw0jxJ1nPvoUwyon9BWrXBMH8/jGB4BYfFhPwqj49Gw0OovbDBWO7/Jy5/Wrn/m5QW+x+xLJvYqv9TQm30/z54YP8TP+eMM6FMcx2nsYB3tya4dcrvgyQP4hBCNhdRi0CS+SEk8bdI1GdZyGCSLWAoYwFm/pTVKhU/iX0OxbVVg97nL/3j45sVckOgL1Tmg7Kt8+CPjD9WGdfPlEtfmAERBEEQBEEQBEEQBEEQBEF2xC/BWaLWACgAAA=="
 
 declare -gx embed_dir_conf_dir="${TMPDIR:-/tmp}/conf_dir"
 
@@ -2705,9 +2731,9 @@ Env::requireLoad
 UI::requireTheme
 Linux::requireUbuntu
 Log::requireLoad
+Linux::requireJqCommand
 Git::requireGitCommand
 Linux::Wsl::requireWsl
-Linux::requireJqCommand
 Compiler::Facade::requireCommandBinDir
 
 if Assert::functionExists initFacade; then
@@ -3602,7 +3628,10 @@ installLazydocker() {
     # shellcheck source=/dev/null
     source "${HOME}/.bash-dev-env/profile.d/golang.sh" || exit 1
     go install github.com/jesseduffield/lazydocker@latest || exit 1
-  ) || return 1
+  ) || {
+    Log::displayError "Failure during lazydocker installation"
+    return 1
+  }
 }
 
 installK9s() {
