stats + wslu
- added Engine::Config::requireWslu
- fixed install stats
- README.md added instruction to test on separated wsl disto

diff --git a/installScripts/Clean b/installScripts/Clean
--- a/installScripts/Clean
+++ b/installScripts/Clean
@@ -396,7 +396,9 @@ Engine::Config::loadConfig() {
   Engine::Config::loadUserVariables
   Engine::Config::loadHostIp
 
-  # TODO is it needed ? Linux::Wsl::initEnv
+  Engine::Config::requireWslu
+
+  Linux::Wsl::initEnv
   Engine::Config::loadWslVariables
 
   Engine::Config::createSudoerFile
@@ -1058,6 +1060,15 @@ Engine::Config::loadWslVariables() {
   return "${errorCount}"
 }
 
+# @description install apt wslu if necessary providing wslvar, wslpath
+Engine::Config::requireWslu() {
+  if ! command -v wslvar &>/dev/null; then
+    Log::displayInfo "Installing pre-requisite Wslu : wslvar, wslpath, ... commands"
+    Linux::Apt::update
+    Linux::Apt::install --no-install-recommends wslu
+  fi
+}
+
 # @description prepend directories to the PATH environment variable
 # @arg $@ args:String[] list of directories to prepend
 # @set PATH update PATH with the directories prepended
@@ -1068,6 +1079,51 @@ Env::pathPrepend() {
       PATH="$(realpath "${arg}"):${PATH}"
     fi
   done
+}
+
+# @description initialize some important variables for scripts to run correctly
+# when wsl installation is run under wsl is in progress
+# @warning initialization skipped if script not run under wsl
+# @noargs
+# @set PATH String populated with WINDOW_PATH paths
+# @set WSL_INTEROP String with current used process
+# @set WSL_DISTRO_NAME String initialized using wslpath -m /
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::initEnv() {
+  if ! Assert::wsl; then
+    return 0
+  fi
+  # Here we are parsing WINDOW_PATH env variable
+  # for each path we remove potential control character
+  # that could break PATH variable
+  # using "${dir}" we ensure path with spaces will be
+  # correctly handled
+  local dir windowsDirs
+  WINDOWS_PATH="$(wslvar PATH)"
+  # shellcheck disable=SC2207,SC2116
+  IFS=';' windowsDirs=($(echo "${WINDOWS_PATH}"))
+  for dir in "${windowsDirs[@]}"; do
+    dir="$(echo "${dir}" | tr -d '[:cntrl:]')"
+    Env::pathPrepend "${dir}"
+  done
+  export PATH
+
+  local p
+  while IFS="" read -r p || [[ -n "${p}" ]]; do
+    if [[ -e "/run/WSL/${p}_interop" ]]; then
+      export WSL_INTEROP=/run/WSL/${p}_interop
+      break
+    fi
+  done < <(
+    pstree --numeric-sort --show-pids --show-parents $$ |
+      head -1 |
+      grep -o -E '[0-9]+' |
+      tac
+  )
+  WSL_DISTRO_NAME="$(Linux::Wsl::cachedWslpath -m / | sed -E 's#.*\$/([^/]+)/$#\1#')"
+  export WSL_DISTRO_NAME
 }
 
 # @description Display given text on full line with TEST_COLOR style
@@ -1156,7 +1212,7 @@ Log::rotate() {
     return 0
   fi
   local i
-  for (( i = 1; i <= maxLogFilesCount; i++ )); do
+  for ((i = maxLogFilesCount - 1; i > 0; i--)); do
     Log::displayInfo "Log rotation ${file}.${i} to ${file}.$((i + 1))"
     mv "${file}."{"${i}","$((i + 1))"} &>/dev/null || true
   done
@@ -1282,6 +1338,39 @@ Install::setUserRootCallback() {
   local fromFile="$1"
   local targetFile="$2"
   chown root:root "${targetFile}"
+}
+
+# @description apt-get install
+# @arg $@ softwares:String[] list of softwares to install
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::install() {
+  Retry::default sudo apt-get install -y -q "$@"
+}
+
+# @description update apt packages list
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::update() {
+  Retry::default sudo apt-get update -y --fix-missing -o Acquire::ForceIPv4=true
+}
+
+# @description retrieve wslpath using cache (cache is refreshed every day)
+# @arg $@ args:String[] arguments to pass to wslpath
+# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
+# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::cachedWslpath() {
+  local -a args=("$@")
+  local tempEnvFile key
+  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+
+  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
+  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
 }
 
 # @description retrieve path from wslvar and then use wslpath to resolve it
@@ -1427,6 +1516,17 @@ UI::textLine() {
   printf '%*s\n' "${remainingWidth}" '' | tr ' ' "${character}"
 }
 
+# @description ensure linux runs under wsl
+# @exitcode 1 if linux does not run under wsl
+Linux::Wsl::requireWsl() {
+  Assert::wsl || return 1
+  local tempEnvDir
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslpath_$(id -un)" "1"
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslvar_$(id -un)" "1"
+}
+
 # @description check if argument respects this framework variable naming convention
 # - if variable begins with an uppercase or underscore, following letters have to be uppercase or underscore
 # - variable name can includes ':' or '_' or digits but not as first letter
@@ -1472,43 +1572,31 @@ Cache::getPropertyValue() {
   return 1
 }
 
-# @description retrieve wslpath using cache (cache is refreshed every day)
-# @arg $@ args:String[] arguments to pass to wslpath
-# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
-# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
-# @stderr diagnostics information is displayed
-# @require Linux::Wsl::requireWsl
-# @feature cache
-Linux::Wsl::cachedWslpath() {
-  local -a args=("$@")
-  local tempEnvFile key
-  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+# @description delete files older than n days in given path
+# @warning use this function with caution as it will delete all files in given path without any prompt
+# @arg $1 path:String the directory in which files will be deleted or the file to delete
+# @arg $2 mtime:String expiration time in days (eg: 1 means 1 day) (default value: 1). Eg: +1 match files that have been accessed at least two days ago (rounding effect)
+# @arg $3 maxdepth:int Descend at most levels (a non-negative integer) levels of directories below the starting-points. (default value: 1)
+# @exitcode 1 if path not provided or empty
+# @exitcode * find command failure code
+# @stderr find output on error or diagnostics logs
+# @see man find atime
+File::garbageCollect() {
+  local path="$1"
+  local mtime="$2"
+  local maxdepth="${3:-1}"
 
-  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
-  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
-}
-
-# @description call simply original wslvar command
-# @arg $@ args:String[] args to pass to wslvar
-# @exitcode * wslvar exit code
-# @stdout wslvar stdout
-# @require Linux::Wsl::requireWsl
-Linux::Wsl::originalWslvar() {
-  wslvar "$@" | sed -z '$ s/[\r\n]$//'
-}
-
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
+  if [[ -z "${path}" ]]; then
+    return 1
   fi
-}
 
-# @description ensure linux runs under wsl
-# @exitcode 1 if linux does not run under wsl
-Linux::Wsl::requireWsl() {
-  Assert::wsl
+  if [[ ! -e "${path}" ]]; then
+    # path already removed
+    return 0
+  fi
+
+  Log::displayInfo "Garbage collect files older than ${mtime} days in path ${path} with max depth ${maxdepth}"
+  find "${path}" -depth -maxdepth "${maxdepth}" -type f -mtime "${mtime}" -print -delete
 }
 
 # @description Compute a cache from wslpath options
@@ -1554,14 +1642,91 @@ Linux::Wsl::originalWslpath() {
   wslpath "$@"
 }
 
+# @description call simply original wslvar command
+# @arg $@ args:String[] args to pass to wslvar
+# @exitcode * wslvar exit code
+# @stdout wslvar stdout
+# @require Linux::Wsl::requireWsl
+Linux::Wsl::originalWslvar() {
+  wslvar "$@" | sed -z '$ s/[\r\n]$//'
+}
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logSkipped() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
+    Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
+}
+
+# @description Retry a command 5 times with a delay of 15 seconds between each attempt
+# @arg $@ command:String[] the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+Retry::default() {
+  Retry::parameterized 5 15 "" "$@"
+}
+
+# @description ensure linux distribution is ubuntu
+# @exitcode 1 if linux distribution is not ubuntu
+Linux::requireUbuntu() {
+  [[ "$(Linux::getDistributorId)" = "Ubuntu" ]]
+}
+
+# @description retrieve linux distributor id
+# @noargs
+# @exitcode 1 if lsb_release fails or not found
+# @stdout the linux distributor id
+Linux::getDistributorId() {
+  lsb_release -a 2>/dev/null | sed -En 's/Distributor ID:[ \t]+(.+)/\1/p'
+}
+
+# @description Retry a command several times depending on parameters
+# @arg $1 maxRetries:int    $1 max retries
+# @arg $2 delay:int between attempt
+# @arg $3 message:String to display to describe the attempt
+# @arg $@ rest of parameters, the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+# @exitcode 2 if maxRetries invalid value
+Retry::parameterized() {
+  local maxRetries=$1
+  shift || true
+  local delayBetweenTries=$1
+  shift || true
+  local message="$1"
+  shift || true
+  local retriesCount=1
+  if [[ "${maxRetries}" -lt 1 ]]; then
+    Log::displayError "invalid maxRetry value"
+    return 2
+  fi
+
+  while true; do
+    Log::displayInfo "Attempt ${retriesCount}/${maxRetries}: ${message}"
+    if "$@"; then
+      break
+    elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
+      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      ((retriesCount++))
+      sleep "${delayBetweenTries}"
+    else
+      Log::displayError "The command has failed after ${retriesCount} attempts."
+      return 1
+    fi
+  done
+  return 0
+}
+
 # FUNCTIONS
 
 facade_main_Cleansh() {
 # REQUIRES
 Env::requireLoad
 UI::requireTheme
-Log::requireLoad
 Linux::Wsl::requireWsl
+Log::requireLoad
+Linux::requireUbuntu
 Compiler::Facade::requireCommandBinDir
 
 # @require Compiler::Facade::requireCommandBinDir
diff --git a/installScripts/Docker b/installScripts/Docker
--- a/installScripts/Docker
+++ b/installScripts/Docker
@@ -396,7 +396,9 @@ Engine::Config::loadConfig() {
   Engine::Config::loadUserVariables
   Engine::Config::loadHostIp
 
-  # TODO is it needed ? Linux::Wsl::initEnv
+  Engine::Config::requireWslu
+
+  Linux::Wsl::initEnv
   Engine::Config::loadWslVariables
 
   Engine::Config::createSudoerFile
@@ -1124,6 +1126,15 @@ Engine::Config::loadWslVariables() {
   return "${errorCount}"
 }
 
+# @description install apt wslu if necessary providing wslvar, wslpath
+Engine::Config::requireWslu() {
+  if ! command -v wslvar &>/dev/null; then
+    Log::displayInfo "Installing pre-requisite Wslu : wslvar, wslpath, ... commands"
+    Linux::Apt::update
+    Linux::Apt::install --no-install-recommends wslu
+  fi
+}
+
 # @description prepend directories to the PATH environment variable
 # @arg $@ args:String[] list of directories to prepend
 # @set PATH update PATH with the directories prepended
@@ -1211,6 +1222,51 @@ Github::getLatestRelease() {
   # display curl result in case of failure
   cat >&2 "${resultFile}"
   rm -f "${resultFile}"
+}
+
+# @description initialize some important variables for scripts to run correctly
+# when wsl installation is run under wsl is in progress
+# @warning initialization skipped if script not run under wsl
+# @noargs
+# @set PATH String populated with WINDOW_PATH paths
+# @set WSL_INTEROP String with current used process
+# @set WSL_DISTRO_NAME String initialized using wslpath -m /
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::initEnv() {
+  if ! Assert::wsl; then
+    return 0
+  fi
+  # Here we are parsing WINDOW_PATH env variable
+  # for each path we remove potential control character
+  # that could break PATH variable
+  # using "${dir}" we ensure path with spaces will be
+  # correctly handled
+  local dir windowsDirs
+  WINDOWS_PATH="$(wslvar PATH)"
+  # shellcheck disable=SC2207,SC2116
+  IFS=';' windowsDirs=($(echo "${WINDOWS_PATH}"))
+  for dir in "${windowsDirs[@]}"; do
+    dir="$(echo "${dir}" | tr -d '[:cntrl:]')"
+    Env::pathPrepend "${dir}"
+  done
+  export PATH
+
+  local p
+  while IFS="" read -r p || [[ -n "${p}" ]]; do
+    if [[ -e "/run/WSL/${p}_interop" ]]; then
+      export WSL_INTEROP=/run/WSL/${p}_interop
+      break
+    fi
+  done < <(
+    pstree --numeric-sort --show-pids --show-parents $$ |
+      head -1 |
+      grep -o -E '[0-9]+' |
+      tac
+  )
+  WSL_DISTRO_NAME="$(Linux::Wsl::cachedWslpath -m / | sed -E 's#.*\$/([^/]+)/$#\1#')"
+  export WSL_DISTRO_NAME
 }
 
 # @description Display given text on full line with TEST_COLOR style
@@ -1307,7 +1363,7 @@ Log::rotate() {
     return 0
   fi
   local i
-  for (( i = 1; i <= maxLogFilesCount; i++ )); do
+  for ((i = maxLogFilesCount - 1; i > 0; i--)); do
     Log::displayInfo "Log rotation ${file}.${i} to ${file}.$((i + 1))"
     mv "${file}."{"${i}","$((i + 1))"} &>/dev/null || true
   done
@@ -1482,6 +1538,39 @@ Install::setUserRootCallback() {
   chown root:root "${targetFile}"
 }
 
+# @description apt-get install
+# @arg $@ softwares:String[] list of softwares to install
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::install() {
+  Retry::default sudo apt-get install -y -q "$@"
+}
+
+# @description update apt packages list
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::update() {
+  Retry::default sudo apt-get update -y --fix-missing -o Acquire::ForceIPv4=true
+}
+
+# @description retrieve wslpath using cache (cache is refreshed every day)
+# @arg $@ args:String[] arguments to pass to wslpath
+# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
+# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::cachedWslpath() {
+  local -a args=("$@")
+  local tempEnvFile key
+  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+
+  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
+  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
+}
+
 # @description retrieve path from wslvar and then use wslpath to resolve it
 # using cache (cache is refreshed every day)
 # @arg $1 var:String the var to retrieve using wslvar
@@ -1645,6 +1734,17 @@ Version::parse() {
   sed -En 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' "$@" | head -n1
 }
 
+# @description ensure linux runs under wsl
+# @exitcode 1 if linux does not run under wsl
+Linux::Wsl::requireWsl() {
+  Assert::wsl || return 1
+  local tempEnvDir
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslpath_$(id -un)" "1"
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslvar_$(id -un)" "1"
+}
+
 # @description check if argument respects this framework variable naming convention
 # - if variable begins with an uppercase or underscore, following letters have to be uppercase or underscore
 # - variable name can includes ':' or '_' or digits but not as first letter
@@ -1690,72 +1790,31 @@ Cache::getPropertyValue() {
   return 1
 }
 
-# @description retrieve wslpath using cache (cache is refreshed every day)
-# @arg $@ args:String[] arguments to pass to wslpath
-# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
-# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
-# @stderr diagnostics information is displayed
-# @require Linux::Wsl::requireWsl
-# @feature cache
-Linux::Wsl::cachedWslpath() {
-  local -a args=("$@")
-  local tempEnvFile key
-  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+# @description delete files older than n days in given path
+# @warning use this function with caution as it will delete all files in given path without any prompt
+# @arg $1 path:String the directory in which files will be deleted or the file to delete
+# @arg $2 mtime:String expiration time in days (eg: 1 means 1 day) (default value: 1). Eg: +1 match files that have been accessed at least two days ago (rounding effect)
+# @arg $3 maxdepth:int Descend at most levels (a non-negative integer) levels of directories below the starting-points. (default value: 1)
+# @exitcode 1 if path not provided or empty
+# @exitcode * find command failure code
+# @stderr find output on error or diagnostics logs
+# @see man find atime
+File::garbageCollect() {
+  local path="$1"
+  local mtime="$2"
+  local maxdepth="${3:-1}"
 
-  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
-  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
-}
-
-# @description call simply original wslvar command
-# @arg $@ args:String[] args to pass to wslvar
-# @exitcode * wslvar exit code
-# @stdout wslvar stdout
-# @require Linux::Wsl::requireWsl
-Linux::Wsl::originalWslvar() {
-  wslvar "$@" | sed -z '$ s/[\r\n]$//'
-}
-
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
-  fi
-}
-
-# @description ensure linux runs under wsl
-# @exitcode 1 if linux does not run under wsl
-Linux::Wsl::requireWsl() {
-  Assert::wsl
-}
-
-# @description ensure command jq is available
-# @exitcode 1 if jq command not available
-# @stderr diagnostics information is displayed
-Linux::requireJqCommand() {
-  Assert::commandExists jq
-}
-
-# @description check if command specified exists or return 1
-# with error and message if not
-#
-# @arg $1 commandName:String on which existence must be checked
-# @arg $2 helpIfNotExists:String a help command to display if the command does not exist
-#
-# @exitcode 1 if the command specified does not exist
-# @stderr diagnostic information + help if second argument is provided
-Assert::commandExists() {
-  local commandName="$1"
-  local helpIfNotExists="$2"
-
-  "${BASH_FRAMEWORK_COMMAND:-command}" -v "${commandName}" >/dev/null 2>/dev/null || {
-    Log::displayError "${commandName} is not installed, please install it"
-    if [[ -n "${helpIfNotExists}" ]]; then
-      Log::displayInfo "${helpIfNotExists}"
-    fi
+  if [[ -z "${path}" ]]; then
     return 1
-  }
-  return 0
+  fi
+
+  if [[ ! -e "${path}" ]]; then
+    # path already removed
+    return 0
+  fi
+
+  Log::displayInfo "Garbage collect files older than ${mtime} days in path ${path} with max depth ${maxdepth}"
+  find "${path}" -depth -maxdepth "${maxdepth}" -type f -mtime "${mtime}" -print -delete
 }
 
 # @description Compute a cache from wslpath options
@@ -1801,14 +1860,75 @@ Linux::Wsl::originalWslpath() {
   wslpath "$@"
 }
 
+# @description call simply original wslvar command
+# @arg $@ args:String[] args to pass to wslvar
+# @exitcode * wslvar exit code
+# @stdout wslvar stdout
+# @require Linux::Wsl::requireWsl
+Linux::Wsl::originalWslvar() {
+  wslvar "$@" | sed -z '$ s/[\r\n]$//'
+}
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logSkipped() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
+    Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
+}
+
+# @description ensure linux distribution is ubuntu
+# @exitcode 1 if linux distribution is not ubuntu
+Linux::requireUbuntu() {
+  [[ "$(Linux::getDistributorId)" = "Ubuntu" ]]
+}
+
+# @description ensure command jq is available
+# @exitcode 1 if jq command not available
+# @stderr diagnostics information is displayed
+Linux::requireJqCommand() {
+  Assert::commandExists jq
+}
+
+# @description check if command specified exists or return 1
+# with error and message if not
+#
+# @arg $1 commandName:String on which existence must be checked
+# @arg $2 helpIfNotExists:String a help command to display if the command does not exist
+#
+# @exitcode 1 if the command specified does not exist
+# @stderr diagnostic information + help if second argument is provided
+Assert::commandExists() {
+  local commandName="$1"
+  local helpIfNotExists="$2"
+
+  "${BASH_FRAMEWORK_COMMAND:-command}" -v "${commandName}" >/dev/null 2>/dev/null || {
+    Log::displayError "${commandName} is not installed, please install it"
+    if [[ -n "${helpIfNotExists}" ]]; then
+      Log::displayInfo "${helpIfNotExists}"
+    fi
+    return 1
+  }
+  return 0
+}
+
+# @description retrieve linux distributor id
+# @noargs
+# @exitcode 1 if lsb_release fails or not found
+# @stdout the linux distributor id
+Linux::getDistributorId() {
+  lsb_release -a 2>/dev/null | sed -En 's/Distributor ID:[ \t]+(.+)/\1/p'
+}
+
 # FUNCTIONS
 
 facade_main_Dockersh() {
 # REQUIRES
 Env::requireLoad
 UI::requireTheme
-Log::requireLoad
 Linux::Wsl::requireWsl
+Log::requireLoad
+Linux::requireUbuntu
 Linux::requireJqCommand
 Compiler::Facade::requireCommandBinDir
 
diff --git a/installScripts/Upgrade b/installScripts/Upgrade
--- a/installScripts/Upgrade
+++ b/installScripts/Upgrade
@@ -434,7 +434,9 @@ Engine::Config::loadConfig() {
   Engine::Config::loadUserVariables
   Engine::Config::loadHostIp
 
-  # TODO is it needed ? Linux::Wsl::initEnv
+  Engine::Config::requireWslu
+
+  Linux::Wsl::initEnv
   Engine::Config::loadWslVariables
 
   Engine::Config::createSudoerFile
@@ -1152,6 +1154,15 @@ Engine::Config::loadWslVariables() {
   return "${errorCount}"
 }
 
+# @description install apt wslu if necessary providing wslvar, wslpath
+Engine::Config::requireWslu() {
+  if ! command -v wslvar &>/dev/null; then
+    Log::displayInfo "Installing pre-requisite Wslu : wslvar, wslpath, ... commands"
+    Linux::Apt::update
+    Linux::Apt::install --no-install-recommends wslu
+  fi
+}
+
 # @description prepend directories to the PATH environment variable
 # @arg $@ args:String[] list of directories to prepend
 # @set PATH update PATH with the directories prepended
@@ -1162,6 +1173,51 @@ Env::pathPrepend() {
       PATH="$(realpath "${arg}"):${PATH}"
     fi
   done
+}
+
+# @description initialize some important variables for scripts to run correctly
+# when wsl installation is run under wsl is in progress
+# @warning initialization skipped if script not run under wsl
+# @noargs
+# @set PATH String populated with WINDOW_PATH paths
+# @set WSL_INTEROP String with current used process
+# @set WSL_DISTRO_NAME String initialized using wslpath -m /
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::initEnv() {
+  if ! Assert::wsl; then
+    return 0
+  fi
+  # Here we are parsing WINDOW_PATH env variable
+  # for each path we remove potential control character
+  # that could break PATH variable
+  # using "${dir}" we ensure path with spaces will be
+  # correctly handled
+  local dir windowsDirs
+  WINDOWS_PATH="$(wslvar PATH)"
+  # shellcheck disable=SC2207,SC2116
+  IFS=';' windowsDirs=($(echo "${WINDOWS_PATH}"))
+  for dir in "${windowsDirs[@]}"; do
+    dir="$(echo "${dir}" | tr -d '[:cntrl:]')"
+    Env::pathPrepend "${dir}"
+  done
+  export PATH
+
+  local p
+  while IFS="" read -r p || [[ -n "${p}" ]]; do
+    if [[ -e "/run/WSL/${p}_interop" ]]; then
+      export WSL_INTEROP=/run/WSL/${p}_interop
+      break
+    fi
+  done < <(
+    pstree --numeric-sort --show-pids --show-parents $$ |
+      head -1 |
+      grep -o -E '[0-9]+' |
+      tac
+  )
+  WSL_DISTRO_NAME="$(Linux::Wsl::cachedWslpath -m / | sed -E 's#.*\$/([^/]+)/$#\1#')"
+  export WSL_DISTRO_NAME
 }
 
 # @description Display given text on full line with TEST_COLOR style
@@ -1258,7 +1314,7 @@ Log::rotate() {
     return 0
   fi
   local i
-  for (( i = 1; i <= maxLogFilesCount; i++ )); do
+  for ((i = maxLogFilesCount - 1; i > 0; i--)); do
     Log::displayInfo "Log rotation ${file}.${i} to ${file}.$((i + 1))"
     mv "${file}."{"${i}","$((i + 1))"} &>/dev/null || true
   done
@@ -1389,6 +1445,22 @@ Install::setUserRootCallback() {
   local fromFile="$1"
   local targetFile="$2"
   chown root:root "${targetFile}"
+}
+
+# @description retrieve wslpath using cache (cache is refreshed every day)
+# @arg $@ args:String[] arguments to pass to wslpath
+# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
+# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
+# @stderr diagnostics information is displayed
+# @require Linux::Wsl::requireWsl
+# @feature cache
+Linux::Wsl::cachedWslpath() {
+  local -a args=("$@")
+  local tempEnvFile key
+  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+
+  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
+  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
 }
 
 # @description retrieve path from wslvar and then use wslpath to resolve it
@@ -1542,6 +1614,17 @@ UI::textLine() {
   printf '%*s\n' "${remainingWidth}" '' | tr ' ' "${character}"
 }
 
+# @description ensure linux runs under wsl
+# @exitcode 1 if linux does not run under wsl
+Linux::Wsl::requireWsl() {
+  Assert::wsl || return 1
+  local tempEnvDir
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslpath_$(id -un)" "1"
+  tempEnvDir="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}"
+  File::garbageCollect "${tempEnvDir}/bash_tools_wslvar_$(id -un)" "1"
+}
+
 # @description get property value from file
 # if not present compute it using propertyNotFoundCallback (if provided) and store it in property file
 # @arg $1 propertyFile:String the file in which the property will be searched
@@ -1575,43 +1658,31 @@ Cache::getPropertyValue() {
   return 1
 }
 
-# @description retrieve wslpath using cache (cache is refreshed every day)
-# @arg $@ args:String[] arguments to pass to wslpath
-# @env WSL_TMPDIR String temp directory to store the wslpath cache (default value: TMPDIR), you can use PERSISTENT_TMPDIR instead
-# @exitcode * if Linux::Wsl::originalWslpath cannot find the path
-# @stderr diagnostics information is displayed
-# @require Linux::Wsl::requireWsl
-# @feature cache
-Linux::Wsl::cachedWslpath() {
-  local -a args=("$@")
-  local tempEnvFile key
-  tempEnvFile="${WSL_TMPDIR:-${PERSISTENT_TMPDIR:-/tmp}}/bash_tools_wslpath_$(id -un)"
+# @description delete files older than n days in given path
+# @warning use this function with caution as it will delete all files in given path without any prompt
+# @arg $1 path:String the directory in which files will be deleted or the file to delete
+# @arg $2 mtime:String expiration time in days (eg: 1 means 1 day) (default value: 1). Eg: +1 match files that have been accessed at least two days ago (rounding effect)
+# @arg $3 maxdepth:int Descend at most levels (a non-negative integer) levels of directories below the starting-points. (default value: 1)
+# @exitcode 1 if path not provided or empty
+# @exitcode * find command failure code
+# @stderr find output on error or diagnostics logs
+# @see man find atime
+File::garbageCollect() {
+  local path="$1"
+  local mtime="$2"
+  local maxdepth="${3:-1}"
 
-  key="$(Linux::Wsl::getKeyFromWslpathOptions "$@")"
-  Cache::getPropertyValue "${tempEnvFile}" "${key}" Linux::Wsl::originalWslpath "${args[@]}"
-}
-
-# @description call simply original wslvar command
-# @arg $@ args:String[] args to pass to wslvar
-# @exitcode * wslvar exit code
-# @stdout wslvar stdout
-# @require Linux::Wsl::requireWsl
-Linux::Wsl::originalWslvar() {
-  wslvar "$@" | sed -z '$ s/[\r\n]$//'
-}
-
-# @description log message to file
-# @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
+  if [[ -z "${path}" ]]; then
+    return 1
   fi
-}
 
-# @description ensure linux runs under wsl
-# @exitcode 1 if linux does not run under wsl
-Linux::Wsl::requireWsl() {
-  Assert::wsl
+  if [[ ! -e "${path}" ]]; then
+    # path already removed
+    return 0
+  fi
+
+  Log::displayInfo "Garbage collect files older than ${mtime} days in path ${path} with max depth ${maxdepth}"
+  find "${path}" -depth -maxdepth "${maxdepth}" -type f -mtime "${mtime}" -print -delete
 }
 
 # @description Compute a cache from wslpath options
@@ -1657,6 +1728,23 @@ Linux::Wsl::originalWslpath() {
   wslpath "$@"
 }
 
+# @description call simply original wslvar command
+# @arg $@ args:String[] args to pass to wslvar
+# @exitcode * wslvar exit code
+# @stdout wslvar stdout
+# @require Linux::Wsl::requireWsl
+Linux::Wsl::originalWslvar() {
+  wslvar "$@" | sed -z '$ s/[\r\n]$//'
+}
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logSkipped() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
+    Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
+}
+
 # FUNCTIONS
 
 facade_main_Upgradesh() {
@@ -1664,8 +1752,8 @@ facade_main_Upgradesh() {
 Linux::requireUbuntu
 Env::requireLoad
 UI::requireTheme
-Log::requireLoad
 Linux::Wsl::requireWsl
+Log::requireLoad
 Compiler::Facade::requireCommandBinDir
 
 # @require Compiler::Facade::requireCommandBinDir
