renmaed USER_HOME env variable to HOME

diff --git a/installScripts/CodeCheckers b/installScripts/CodeCheckers
--- a/installScripts/CodeCheckers
+++ b/installScripts/CodeCheckers
@@ -165,7 +165,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -198,7 +198,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -311,7 +311,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -991,12 +991,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1005,17 +1005,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1112,7 +1112,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -2822,9 +2822,9 @@ install() {
     shellcheck
 
   Log::displayInfo "Installing python dependencies shfmt-py"
-  if [[ -f "${USER_HOME}/.virtualenvs/python3.9/bin/activate" ]]; then
+  if [[ -f "${HOME}/.virtualenvs/python3.9/bin/activate" ]]; then
     # shellcheck source=/dev/null
-    source "${USER_HOME}/.virtualenvs/python3.9/bin/activate"
+    source "${HOME}/.virtualenvs/python3.9/bin/activate"
     pip install --user shfmt-py
   else
     Log::displaySkipped "VirtualEnv has not been installed correctly"
@@ -2848,8 +2848,8 @@ testInstall() {
 
   # composer dependencies
   # shellcheck source=src/_binaries/Composer/conf/.bash-dev-env/profile.d/composer_path.sh
-  source "${USER_HOME}/.bash-dev-env/profile.d/composer_path.sh" || {
-    Log::displayError "Composer script failed to install '${USER_HOME}/.bash-dev-env/profile.d/composer_path.sh'"
+  source "${HOME}/.bash-dev-env/profile.d/composer_path.sh" || {
+    Log::displayError "Composer script failed to install '${HOME}/.bash-dev-env/profile.d/composer_path.sh'"
     ((++failures))
   }
   Version::checkMinimal "phpcs" --version "3.9.0" || ((++failures))
diff --git a/installScripts/Export b/installScripts/Export
--- a/installScripts/Export
+++ b/installScripts/Export
@@ -165,7 +165,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -198,7 +198,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -311,7 +311,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -979,12 +979,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -993,17 +993,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1100,7 +1100,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -2754,13 +2754,13 @@ configure() {
       git config --global --unset user.name || true
       git config --global --unset user.email || true
       rm -Rf "${BACKUP_DIR:?}/"* || true
-      rm -Rf "${USER_HOME}/.vscode-server" || true
-      rm -f "${USER_HOME}/.ssh/id_rsa" || true
-      rm -f "${USER_HOME}/.ssh/config" || true
-      rm -f "${USER_HOME}/.ssh/known_hosts.old" || true
-      rm -f "${USER_HOME}/.saml2aws" || true
-      rm -f "${USER_HOME}/.aws/credentials" || true
-      rm -f "${USER_HOME}/.aws/config" || true
+      rm -Rf "${HOME}/.vscode-server" || true
+      rm -f "${HOME}/.ssh/id_rsa" || true
+      rm -f "${HOME}/.ssh/config" || true
+      rm -f "${HOME}/.ssh/known_hosts.old" || true
+      rm -f "${HOME}/.saml2aws" || true
+      rm -f "${HOME}/.aws/credentials" || true
+      rm -f "${HOME}/.aws/config" || true
 
       deleteFolderExcept() {
         local folder="$1"
@@ -2800,7 +2800,7 @@ configure() {
 testConfigure() {
   local -i failures=0
   if [[ "${PREPARE_EXPORT}" = "1" ]]; then
-    if [[ -f "${USER_HOME}/.gitconfig" ]]; then
+    if [[ -f "${HOME}/.gitconfig" ]]; then
       if git config --global --get user.name &>/dev/null; then
         Log::displayError "Export - .gitconfig user.name has not been removed"
         ((++failures))
@@ -2810,13 +2810,13 @@ testConfigure() {
         ((++failures))
       fi
     fi
-    Assert::fileNotExists "${USER_HOME}/.vscode-server" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.ssh/id_rsa" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.ssh/config" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.ssh/known_hosts.old" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.saml2aws" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.aws/credentials" || ((++failures))
-    Assert::fileNotExists "${USER_HOME}/.aws/config" || ((++failures))
+    Assert::fileNotExists "${HOME}/.vscode-server" || ((++failures))
+    Assert::fileNotExists "${HOME}/.ssh/id_rsa" || ((++failures))
+    Assert::fileNotExists "${HOME}/.ssh/config" || ((++failures))
+    Assert::fileNotExists "${HOME}/.ssh/known_hosts.old" || ((++failures))
+    Assert::fileNotExists "${HOME}/.saml2aws" || ((++failures))
+    Assert::fileNotExists "${HOME}/.aws/credentials" || ((++failures))
+    Assert::fileNotExists "${HOME}/.aws/config" || ((++failures))
 
     SUDO=sudo Assert::dirEmpty \
       "${BASH_DEV_ENV_ROOT_DIR}/megalinter-reports/" \
diff --git a/installScripts/Go b/installScripts/Go
--- a/installScripts/Go
+++ b/installScripts/Go
@@ -165,7 +165,7 @@ envFileTemplate="$(
 # wsl username
 USERNAME="wsl"
 USERGROUP="wsl"
-USER_HOME="/home/wsl"
+HOME="/home/wsl"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -198,7 +198,7 @@ CONF_OVERRIDE_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf.override"
 
 # where to install bash-tools, ...
 # shellcheck disable=SC2153
-PROJECTS_DIR="${USER_HOME}/projects"
+PROJECTS_DIR="${HOME}/projects"
 
 # where overridden config files will be backed up
 BACKUP_DIR="${BASH_DEV_ENV_ROOT_DIR}/backup"
@@ -311,7 +311,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${USER_HOME}/.local/bin"
+  export PATH="${PATH}:${HOME}/.local/bin"
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -1025,12 +1025,12 @@ Engine::Config::loadOsRelease() {
   set +o allexport
 }
 
-# @description deduce USER_HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
+# @description deduce HOME, USER_ID, USERGROUP_ID and USERGROUP from USERNAME
 # @env USERNAME String the name of the user
 # @set USER_ID String
 # @set USERGROUP String
 # @set USERGROUP_ID String
-# @set USER_HOME String
+# @set HOME String
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
@@ -1039,17 +1039,17 @@ Engine::Config::loadUserVariables() {
   split=($(getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
-  USER_HOME="${split[5]}"
+  HOME="${split[5]}"
   # shellcheck disable=SC2207
   split=($(getent group "${USERNAME}"))
   USERGROUP="${split[0]}"
 
-  if [[ -z "${USERGROUP}" || -z "${USER_HOME}" ]]; then
-    Log::displayError "USERNAME - unable to deduce USERGROUP, USER_HOME from USERNAME"
+  if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
+    Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
     return 1
   fi
 
-  export USER_HOME
+  export HOME
   export USER_ID
   export USERGROUP_ID
   export USERGROUP
@@ -1146,7 +1146,7 @@ Engine::Config::checkEnv() {
   checkVarAndDir BACKUP_DIR rw || true
   checkVarAndDir LOGS_DIR rw || true
   checkVarAndDir INSTALL_SCRIPTS_DIR r || true
-  checkVarAndDir USER_HOME rw || true
+  checkVarAndDir HOME rw || true
 
   checkValidValues UPGRADE_UBUNTU_VERSION 0 lts dev
   checkValidValues PREFERRED_SHELL ShellBash ShellZsh
@@ -2931,10 +2931,10 @@ install() {
         Log::displayError "update-golang sha checksum doesn't match"
       }
       sudo rm -f hash.txt
-      mkdir -p "${USER_HOME}/golang"
+      mkdir -p "${HOME}/golang"
       Log::displayInfo "Install/update go ..."
-      DESTINATION="${USER_HOME}/golang" \
-        PROFILED="${USER_HOME}/.bash-dev-env/profile.d/golang.sh" ./update-golang.sh
+      DESTINATION="${HOME}/golang" \
+        PROFILED="${HOME}/.bash-dev-env/profile.d/golang.sh" ./update-golang.sh
     )
   }
   SUDO=sudo Git::cloneOrPullIfNoChanges \
@@ -2945,9 +2945,9 @@ install() {
 }
 
 testInstall() {
-  Assert::fileExists "${USER_HOME}/.bash-dev-env/profile.d/golang.sh"
+  Assert::fileExists "${HOME}/.bash-dev-env/profile.d/golang.sh"
   # shellcheck source=/dev/null
-  source "${USER_HOME}/.bash-dev-env/profile.d/golang.sh" || return 1
+  source "${HOME}/.bash-dev-env/profile.d/golang.sh" || return 1
   Version::checkMinimal "go" "version" "1.22.1" || return 1
 }
 
