Upgrade to Ubuntu 24.04
All following changes are due to ubuntu24.04 migration
- splitted .ev.distro.template to 2 distro templates for respectively for
  ubuntu 20.04 and 24.04
- .env.template
  - removed USERGROUP that is implied by host group id
  - added WINDOWS_USERNAME
- renamed virtualenv from python3.9 to python3 as python 3.12 is the default
  now on ubuntu24.04
- added in loadConfig, call to Engine::Config::loadLocaleConfig responsible
  to configure LANG to en_US.UTF-8 to avoid some annoying messages
- distro
  - make distro url works with these 2 formats
    - <https://cloud-images.ubuntu.com/wsl/noble/current/ubuntu-noble-wsl-amd64-wsl.rootfs.tar.gz>
    - <https://aka.ms/wslubuntu2004>
  - added VAR_LOAD_LOCALE_CONFIG=0 to avoid loading locale config
  - changed the way the user is created to get right uid/gid aligned with
    host so project copy works across distros
  - Engine::Config::loadUserVariables is done when distro and user is created and using remote
    distro
- changes on installScripts
  - Docker - specific way to install docker on ubuntu24
  - Fasd - ubuntu24 does not need for ppa repository to be added
  - Font - surprisingly windows owner is not aligned with wsl user. So I make Assert::fileExists
    ignore ownership of the files
  - KubeDefaultConfig - use gpg --dearmor instead of apt-key
  - Python - changed the way python is installed avoiding some deprecated usages
  - ShellBash - added .bash-dev-env/profile.d/locale.sh

Bug fixes:
- fixed bug WINDOWS_PROFILE_DIR was incorrectly deduced from USERNAME that
  could be different than new WINDOWS_USERNAME
- SdkManager - no more rely on sdk exit code
- Go
  - remove verbose on tar extract
  - profile - added ~/golang/go/bin to PATH

diff --git a/installScripts/Docker b/installScripts/Docker
--- a/installScripts/Docker
+++ b/installScripts/Docker
@@ -187,8 +187,8 @@ envFileTemplate="$(
 # shellcheck disable=SC2034
 # wsl username
 USERNAME="wsl"
-USERGROUP="wsl"
 HOME="/home/wsl"
+WINDOWS_USERNAME="fchastanet"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -338,7 +338,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${HOME}/.local/bin"
+  Engine::Config::loadLocaleConfig
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -836,6 +836,38 @@ InstallScripts::scriptFunctionEmpty() {
   [[ "$(declare -f "$1" | sed '3q;d')" =~ ${pattern} && "$(declare -f "$1" | sed '4q;d')" = "}" ]]
 }
 
+# @description compare 2 version numbers
+# @arg $1 version1:String version 1
+# @arg $2 version2:String version 2
+# @exitcode 0 if equal
+# @exitcode 1 if version1 > version2
+# @exitcode 2 else
+Version::compare() {
+  if [[ "$1" = "$2" ]]; then
+    return 0
+  fi
+  local IFS=.
+  # shellcheck disable=2206
+  local i ver1=($1) ver2=($2)
+  # fill empty fields in ver1 with zeros
+  for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do
+    ver1[i]=0
+  done
+  for ((i = 0; i < ${#ver1[@]}; i++)); do
+    if [[ -z "${ver2[i]+unset}" ]] || [[ -z ${ver2[i]} ]]; then
+      # fill empty fields in ver2 with zeros
+      ver2[i]=0
+    fi
+    if ((10#${ver1[i]} > 10#${ver2[i]})); then
+      return 1
+    fi
+    if ((10#${ver1[i]} < 10#${ver2[i]})); then
+      return 2
+    fi
+  done
+  return 0
+}
+
 # @description apt-get install if package is not installed yet
 # @arg $@ packages:String[] list of packages to install
 # @feature Retry::default
@@ -997,16 +1029,20 @@ Assert::fileExists() {
   local file="$1"
   local user="${2:-${USERNAME}}"
   local group="${3:-${USERGROUP}}"
-  Log::displayInfo "Check ${file} exists with user ${user}:${group}"
+  if [[ -n "${user}" ]]; then
+    Log::displayInfo "Check ${file} exists with user ${user}:${group}"
+  else
+    Log::displayInfo "Check ${file} exists"
+  fi
   if ! ${SUDO:-} test -f "${file}" &>/dev/null; then
     Log::displayError "missing file ${file}"
     return 1
   fi
-  if [[ "${user}" != "$(${SUDO:-} stat -c '%U' "${file}")" ]]; then
+  if [[ -n "${user}" && "${user}" != "$(${SUDO:-} stat -c '%U' "${file}")" ]]; then
     Log::displayError "incorrect user ownership on file ${file}"
     return 2
   fi
-  if [[ "${group}" != "$(${SUDO:-} stat -c '%G' "${file}")" ]]; then
+  if [[ -n "${group}" && "${group}" != "$(${SUDO:-} stat -c '%G' "${file}")" ]]; then
     Log::displayError "incorrect group ownership on file ${file}"
     return 3
   fi
@@ -1114,19 +1150,18 @@ Engine::Config::loadOsRelease() {
 # @set USERGROUP_ID String
 # @set USER_SHELL String current user shell
 # @set HOME String
+# @env REMOTE String prefix command to run commands remotely
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
   local IFS=':'
   # shellcheck disable=SC2207
-  split=($(getent passwd "${USERNAME}"))
+  split=($(${REMOTE:-} getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
   HOME="${split[5]}"
   USER_SHELL="${split[6]}"
-  # shellcheck disable=SC2207
-  split=($(getent group "${USERNAME}"))
-  USERGROUP="${split[0]}"
+  USERGROUP="$(${REMOTE:-} id -gn "${USERNAME}")"
 
   if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
     Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
@@ -1307,7 +1342,7 @@ Engine::Config::loadWslVariables() {
   export WINDOWS_DIR
 
   Linux::Wsl::cachedWslpathFromWslVar2 WINDOWS_PROFILE_DIR USERPROFILE
-  WINDOWS_PROFILE_DIR="${WINDOWS_PROFILE_DIR:-${BASE_MNT_C:-/mnt/c}/Users/${USERNAME}}"
+  WINDOWS_PROFILE_DIR="${WINDOWS_PROFILE_DIR:-${BASE_MNT_C:-/mnt/c}/Users/${WINDOWS_USERNAME}}"
   export WINDOWS_PROFILE_DIR
 
   Linux::Wsl::cachedWslpathFromWslVar2 LOCAL_APP_DATA LOCALAPPDATA
@@ -1356,6 +1391,26 @@ Engine::Config::loadWslVariables() {
   checkBinary POWERSHELL_BIN
 
   return "${errorCount}"
+}
+
+# @description load locale configuration
+Engine::Config::loadLocaleConfig() {
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
+    return 0
+  fi
+  if [[ "${LOAD_LOCALE_CONFIG:-1}" = "1" && ! -f "${PERSISTENT_TMPDIR}/localeConfig.initialized" ]]; then
+    Log::displayInfo "Initializing locale en_US.UTF-8"
+    export PATH="${PATH}:${HOME}/.local/bin"
+    sudo sed -E -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
+    echo 'LANG="en_US.UTF-8"' | sudo tee /etc/default/locale >/dev/null
+    echo "LANG=en_US.UTF-8" | sudo tee /etc/locale.conf >/dev/null
+    sudo locale-gen en_US.UTF-8
+    sudo dpkg-reconfigure --frontend=noninteractive locales
+    export LC_ALL=C
+    export LANG=en_US.UTF-8
+    export LC_MESSAGES=en_US.UTF-8
+    touch "${PERSISTENT_TMPDIR}/localeConfig.initialized"
+  fi
 }
 
 # @description log message to file
@@ -1652,38 +1707,6 @@ Bash::handlePipelineFailure() {
     fi
   done
   return "${handlePipelineFailure_resultingStatusCode}"
-}
-
-# @description compare 2 version numbers
-# @arg $1 version1:String version 1
-# @arg $2 version2:String version 2
-# @exitcode 0 if equal
-# @exitcode 1 if version1 > version2
-# @exitcode 2 else
-Version::compare() {
-  if [[ "$1" = "$2" ]]; then
-    return 0
-  fi
-  local IFS=.
-  # shellcheck disable=2206
-  local i ver1=($1) ver2=($2)
-  # fill empty fields in ver1 with zeros
-  for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do
-    ver1[i]=0
-  done
-  for ((i = 0; i < ${#ver1[@]}; i++)); do
-    if [[ -z "${ver2[i]+unset}" ]] || [[ -z ${ver2[i]} ]]; then
-      # fill empty fields in ver2 with zeros
-      ver2[i]=0
-    fi
-    if ((10#${ver1[i]} > 10#${ver2[i]})); then
-      return 1
-    fi
-    if ((10#${ver1[i]} < 10#${ver2[i]})); then
-      return 2
-    fi
-  done
-  return 0
 }
 
 # @description log message to file
@@ -2427,13 +2450,14 @@ Compiler::Facade::requireCommandBinDir
 if Assert::functionExists initFacade; then
   initFacade
 fi
+LOAD_LOCALE_CONFIG="1"
 Engine::Config::loadConfig
 # @description create sudoer file and add traps to remove it at the end
 # @arg $1 sudoerFile:String the file path to create
 # @env USERNAME
 # shellcheck disable=SC2317
 local sudoerFile="${SUDOER_FILE_PREFIX}/etc/sudoers.d/bash-dev-env-no-password"
-if [[ -f "${sudoerFile}" ]]; then
+if [[ -f "${sudoerFile}" ]] || sudo test -f "${sudoerFile}"; then
   # sudoerFile probably already managed by parent script
   true
 else
@@ -3236,6 +3260,44 @@ breakOnTestFailure() { :; }
 # REQUIRE Linux::requireUbuntu
 # REQUIRE Linux::requireExecutedAsUser
 install() {
+  if isUbuntuMinimum24; then
+    installFromUbuntu24
+  else
+    installFromUbuntu20
+  fi
+}
+
+isUbuntuMinimum24() {
+  Version::compare "${VERSION_ID}" "24.04"
+}
+
+installFromUbuntu24() {
+  Log::displayInfo "install docker required packages"
+  Linux::Apt::installIfNecessary --no-install-recommends \
+    ca-certificates \
+    curl
+
+  sudo sh -c 'install -m 0755 -d /etc/apt/keyrings'
+  Retry::default sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+  sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+  Log::displayInfo "install docker apt source list"
+  echo \
+    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
+    https://download.docker.com/linux/ubuntu \
+    ${VERSION_CODENAME} stable" |
+    sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
+
+  Log::displayInfo "install docker"
+  Linux::Apt::installIfNecessary --no-install-recommends \
+    containerd.io \
+    docker-buildx-plugin \
+    docker-ce \
+    docker-ce-cli \
+    docker-compose-plugin
+}
+
+installFromUbuntu20() {
   Log::displayInfo "install docker required packages"
   Linux::Apt::installIfNecessary --no-install-recommends \
     apt-transport-https \
@@ -3296,17 +3358,26 @@ testInstall() {
   return "${failures}"
 }
 
-configure() {
-  Log::displayInfo "allowing user '${USERNAME}' to use docker"
-  sudo getent group docker >/dev/null || sudo groupadd docker || true
-  sudo usermod -aG docker "${USERNAME}" || true
-
+configureDockerPlugin() {
   Log::displayInfo "Configuring docker-compose as docker plugin"
   # create the docker plugins directory if it doesn't exist yet
   # shellcheck disable=SC2153
   mkdir -p "${HOME}/.docker/cli-plugins"
   rm -f "${HOME}/.docker/cli-plugins/docker-compose" || true
   sudo ln -sf /usr/local/bin/docker-compose "${HOME}/.docker/cli-plugins/docker-compose"
+}
+
+configure() {
+  Log::displayInfo "allowing user '${USERNAME}' to use docker"
+  sudo getent group docker >/dev/null || sudo groupadd docker || true
+  sudo usermod -aG docker "${USERNAME}" || true
+
+  if ! isUbuntuMinimum24; then
+    configureDockerPlugin
+  fi
+
+  sudo systemctl enable docker.service
+  sudo systemctl enable containerd.service
 
   # shellcheck disable=SC2154
   Conf::copyStructure \
@@ -3322,12 +3393,6 @@ testConfigure() {
   Log::displayInfo "check if docker-compose binary is working"
   if ! docker-compose version &>/dev/null; then
     Log::displayError "docker-compose failure"
-    ((++failures))
-  fi
-
-  Log::displayInfo "check if docker compose plugin is installed"
-  if [[ ! -f "${HOME}/.docker/cli-plugins/docker-compose" ]]; then
-    Log::displayError "docker compose plugin not installed in folder ${HOME}/.docker/cli-plugins/"
     ((++failures))
   fi
 
diff --git a/installScripts/Python b/installScripts/Python
--- a/installScripts/Python
+++ b/installScripts/Python
@@ -187,8 +187,8 @@ envFileTemplate="$(
 # shellcheck disable=SC2034
 # wsl username
 USERNAME="wsl"
-USERGROUP="wsl"
 HOME="/home/wsl"
+WINDOWS_USERNAME="fchastanet"
 
 # your login to connect to ssh servers if any
 SSH_LOGIN=""
@@ -338,7 +338,7 @@ Engine::Config::loadConfig() {
 
   Log::requireLoad
 
-  export PATH="${PATH}:${HOME}/.local/bin"
+  Engine::Config::loadLocaleConfig
 
   export BASH_DEV_ENV_CONFIG_LOADED=1
 }
@@ -836,23 +836,36 @@ InstallScripts::scriptFunctionEmpty() {
   [[ "$(declare -f "$1" | sed '3q;d')" =~ ${pattern} && "$(declare -f "$1" | sed '4q;d')" = "}" ]]
 }
 
-# @description add apt repository followed by an apt-get update
-# @feature Retry::default
-# Linux::requireSudoCommand
-# @require Linux::requireUbuntu
-# @env SKIP_APT_GET_UPDATE
-# @stdout diagnostics logs
-Linux::Apt::addRepository() {
-  if ! Linux::Apt::repositoryExists "$1"; then
-    Log::displayInfo "Apt add repository $1"
-    if [[ "${SKIP_APT_GET_UPDATE:-0}" = "0" ]]; then
-      Retry::default sudo add-apt-repository -y --update "$1"
-    else
-      Retry::default sudo add-apt-repository -y "$1"
-    fi
-  else
-    Log::displayInfo "Repository $1 is already installed"
+# @description compare 2 version numbers
+# @arg $1 version1:String version 1
+# @arg $2 version2:String version 2
+# @exitcode 0 if equal
+# @exitcode 1 if version1 > version2
+# @exitcode 2 else
+Version::compare() {
+  if [[ "$1" = "$2" ]]; then
+    return 0
   fi
+  local IFS=.
+  # shellcheck disable=2206
+  local i ver1=($1) ver2=($2)
+  # fill empty fields in ver1 with zeros
+  for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do
+    ver1[i]=0
+  done
+  for ((i = 0; i < ${#ver1[@]}; i++)); do
+    if [[ -z "${ver2[i]+unset}" ]] || [[ -z ${ver2[i]} ]]; then
+      # fill empty fields in ver2 with zeros
+      ver2[i]=0
+    fi
+    if ((10#${ver1[i]} > 10#${ver2[i]})); then
+      return 1
+    fi
+    if ((10#${ver1[i]} < 10#${ver2[i]})); then
+      return 2
+    fi
+  done
+  return 0
 }
 
 # @description apt-get install if package is not installed yet
@@ -918,6 +931,25 @@ Conf::copyStructure() {
     Install::structure "${configDir}/${subDir}" "${targetDir}"
 }
 
+# @description add apt repository followed by an apt-get update
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+# @env SKIP_APT_GET_UPDATE
+# @stdout diagnostics logs
+Linux::Apt::addRepository() {
+  if ! Linux::Apt::repositoryExists "$1"; then
+    Log::displayInfo "Apt add repository $1"
+    if [[ "${SKIP_APT_GET_UPDATE:-0}" = "0" ]]; then
+      Retry::default sudo add-apt-repository -y --update "$1"
+    else
+      Retry::default sudo add-apt-repository -y "$1"
+    fi
+  else
+    Log::displayInfo "Repository $1 is already installed"
+  fi
+}
+
 # @description Check that command version is greater than expected minimal version
 # display warning if command version greater than expected minimal version
 # display error if command version less than expected minimal version and exit 1
@@ -975,16 +1007,20 @@ Assert::fileExists() {
   local file="$1"
   local user="${2:-${USERNAME}}"
   local group="${3:-${USERGROUP}}"
-  Log::displayInfo "Check ${file} exists with user ${user}:${group}"
+  if [[ -n "${user}" ]]; then
+    Log::displayInfo "Check ${file} exists with user ${user}:${group}"
+  else
+    Log::displayInfo "Check ${file} exists"
+  fi
   if ! ${SUDO:-} test -f "${file}" &>/dev/null; then
     Log::displayError "missing file ${file}"
     return 1
   fi
-  if [[ "${user}" != "$(${SUDO:-} stat -c '%U' "${file}")" ]]; then
+  if [[ -n "${user}" && "${user}" != "$(${SUDO:-} stat -c '%U' "${file}")" ]]; then
     Log::displayError "incorrect user ownership on file ${file}"
     return 2
   fi
-  if [[ "${group}" != "$(${SUDO:-} stat -c '%G' "${file}")" ]]; then
+  if [[ -n "${group}" && "${group}" != "$(${SUDO:-} stat -c '%G' "${file}")" ]]; then
     Log::displayError "incorrect group ownership on file ${file}"
     return 3
   fi
@@ -1092,19 +1128,18 @@ Engine::Config::loadOsRelease() {
 # @set USERGROUP_ID String
 # @set USER_SHELL String current user shell
 # @set HOME String
+# @env REMOTE String prefix command to run commands remotely
 Engine::Config::loadUserVariables() {
   # deduce user home and group
   local -a split
   local IFS=':'
   # shellcheck disable=SC2207
-  split=($(getent passwd "${USERNAME}"))
+  split=($(${REMOTE:-} getent passwd "${USERNAME}"))
   USER_ID="${split[2]}"
   USERGROUP_ID="${split[3]}"
   HOME="${split[5]}"
   USER_SHELL="${split[6]}"
-  # shellcheck disable=SC2207
-  split=($(getent group "${USERNAME}"))
-  USERGROUP="${split[0]}"
+  USERGROUP="$(${REMOTE:-} id -gn "${USERNAME}")"
 
   if [[ -z "${USERGROUP}" || -z "${HOME}" ]]; then
     Log::displayError "USERNAME - unable to deduce USERGROUP, HOME from USERNAME"
@@ -1285,7 +1320,7 @@ Engine::Config::loadWslVariables() {
   export WINDOWS_DIR
 
   Linux::Wsl::cachedWslpathFromWslVar2 WINDOWS_PROFILE_DIR USERPROFILE
-  WINDOWS_PROFILE_DIR="${WINDOWS_PROFILE_DIR:-${BASE_MNT_C:-/mnt/c}/Users/${USERNAME}}"
+  WINDOWS_PROFILE_DIR="${WINDOWS_PROFILE_DIR:-${BASE_MNT_C:-/mnt/c}/Users/${WINDOWS_USERNAME}}"
   export WINDOWS_PROFILE_DIR
 
   Linux::Wsl::cachedWslpathFromWslVar2 LOCAL_APP_DATA LOCALAPPDATA
@@ -1334,6 +1369,26 @@ Engine::Config::loadWslVariables() {
   checkBinary POWERSHELL_BIN
 
   return "${errorCount}"
+}
+
+# @description load locale configuration
+Engine::Config::loadLocaleConfig() {
+  if [[ "${BASH_DEV_ENV_CONFIG_LOADED:-0}" = "1" ]]; then
+    return 0
+  fi
+  if [[ "${LOAD_LOCALE_CONFIG:-1}" = "1" && ! -f "${PERSISTENT_TMPDIR}/localeConfig.initialized" ]]; then
+    Log::displayInfo "Initializing locale en_US.UTF-8"
+    export PATH="${PATH}:${HOME}/.local/bin"
+    sudo sed -E -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
+    echo 'LANG="en_US.UTF-8"' | sudo tee /etc/default/locale >/dev/null
+    echo "LANG=en_US.UTF-8" | sudo tee /etc/locale.conf >/dev/null
+    sudo locale-gen en_US.UTF-8
+    sudo dpkg-reconfigure --frontend=noninteractive locales
+    export LC_ALL=C
+    export LANG=en_US.UTF-8
+    export LC_MESSAGES=en_US.UTF-8
+    touch "${PERSISTENT_TMPDIR}/localeConfig.initialized"
+  fi
 }
 
 # @description log message to file
@@ -1508,30 +1563,6 @@ Stats::statusLine() {
   )
 }
 
-# @description check if apt repository is added to apt sources
-# Linux::requireSudoCommand
-# @require Linux::requireUbuntu
-# @stdout diagnostics logs
-Linux::Apt::repositoryExists() {
-  local aptRepoName="$1"
-  local regexp
-  if [[ "${aptRepoName}" =~ https?:// ]]; then
-    regexp="^[[:space:]]*deb ${aptRepoName}"
-  else
-    regexp="^[[:space:]]*deb .*${aptRepoName}"
-  fi
-  [[ -n "$(find /etc/apt/ -name '*.list' -print0 |
-    xargs -0 -P 10 -L 1 grep "${regexp}" || true)" ]]
-}
-
-# @description Retry a command 5 times with a delay of 15 seconds between each attempt
-# @arg $@ command:String[] the command to run
-# @exitcode 0 on success
-# @exitcode 1 if max retries count reached
-Retry::default() {
-  Retry::parameterized 5 15 "" "$@"
-}
-
 # @description check if apt package is installed
 # @arg $1 package:String the package name to check
 # @require Linux::requireUbuntu
@@ -1697,6 +1728,30 @@ Install::structure() {
   Log::displaySuccess "Installed directory '${toDir#${PRETTY_ROOT_DIR}/}' from '${fromDir#${PRETTY_ROOT_DIR}/}'"
 }
 
+# @description check if apt repository is added to apt sources
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+# @stdout diagnostics logs
+Linux::Apt::repositoryExists() {
+  local aptRepoName="$1"
+  local regexp
+  if [[ "${aptRepoName}" =~ https?:// ]]; then
+    regexp="^[[:space:]]*deb ${aptRepoName}"
+  else
+    regexp="^[[:space:]]*deb .*${aptRepoName}"
+  fi
+  [[ -n "$(find /etc/apt/ -name '*.list' -print0 |
+    xargs -0 -P 10 -L 1 grep "${regexp}" || true)" ]]
+}
+
+# @description Retry a command 5 times with a delay of 15 seconds between each attempt
+# @arg $@ command:String[] the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+Retry::default() {
+  Retry::parameterized 5 15 "" "$@"
+}
+
 # @description filter to keep only version number from a string
 # @arg $@ files:String[] the files to filter
 # @exitcode * if one of the filter command fails
@@ -1762,38 +1817,6 @@ Bash::handlePipelineFailure() {
     fi
   done
   return "${handlePipelineFailure_resultingStatusCode}"
-}
-
-# @description compare 2 version numbers
-# @arg $1 version1:String version 1
-# @arg $2 version2:String version 2
-# @exitcode 0 if equal
-# @exitcode 1 if version1 > version2
-# @exitcode 2 else
-Version::compare() {
-  if [[ "$1" = "$2" ]]; then
-    return 0
-  fi
-  local IFS=.
-  # shellcheck disable=2206
-  local i ver1=($1) ver2=($2)
-  # fill empty fields in ver1 with zeros
-  for ((i = ${#ver1[@]}; i < ${#ver2[@]}; i++)); do
-    ver1[i]=0
-  done
-  for ((i = 0; i < ${#ver1[@]}; i++)); do
-    if [[ -z "${ver2[i]+unset}" ]] || [[ -z ${ver2[i]} ]]; then
-      # fill empty fields in ver2 with zeros
-      ver2[i]=0
-    fi
-    if ((10#${ver1[i]} > 10#${ver2[i]})); then
-      return 1
-    fi
-    if ((10#${ver1[i]} < 10#${ver2[i]})); then
-      return 2
-    fi
-  done
-  return 0
 }
 
 # @description prepend directories to the PATH environment variable
@@ -2027,43 +2050,6 @@ EOF
   fi
 }
 
-# @description Retry a command several times depending on parameters
-# @arg $1 maxRetries:int    $1 max retries
-# @arg $2 delay:int between attempt
-# @arg $3 message:String to display to describe the attempt
-# @arg $@ rest of parameters, the command to run
-# @exitcode 0 on success
-# @exitcode 1 if max retries count reached
-# @exitcode 2 if maxRetries invalid value
-Retry::parameterized() {
-  local maxRetries=$1
-  shift || true
-  local delayBetweenTries=$1
-  shift || true
-  local message="$1"
-  shift || true
-  local retriesCount=1
-  if [[ "${maxRetries}" -lt 1 ]]; then
-    Log::displayError "invalid maxRetry value"
-    return 2
-  fi
-
-  while true; do
-    Log::displayInfo "Attempt ${retriesCount}/${maxRetries}: ${message}"
-    if "$@"; then
-      break
-    elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
-      ((retriesCount++))
-      sleep "${delayBetweenTries}"
-    else
-      Log::displayError "The command has failed after ${retriesCount} attempts."
-      return 1
-    fi
-  done
-  return 0
-}
-
 # @description installs file to given directory
 #
 # callbacks parameters `${fromFile} ${targetFile} $@`
@@ -2153,6 +2139,43 @@ Log::displaySuccess() {
     echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSuccess "$1"
+}
+
+# @description Retry a command several times depending on parameters
+# @arg $1 maxRetries:int    $1 max retries
+# @arg $2 delay:int between attempt
+# @arg $3 message:String to display to describe the attempt
+# @arg $@ rest of parameters, the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+# @exitcode 2 if maxRetries invalid value
+Retry::parameterized() {
+  local maxRetries=$1
+  shift || true
+  local delayBetweenTries=$1
+  shift || true
+  local message="$1"
+  shift || true
+  local retriesCount=1
+  if [[ "${maxRetries}" -lt 1 ]]; then
+    Log::displayError "invalid maxRetry value"
+    return 2
+  fi
+
+  while true; do
+    Log::displayInfo "Attempt ${retriesCount}/${maxRetries}: ${message}"
+    if "$@"; then
+      break
+    elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
+      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      ((retriesCount++))
+      sleep "${delayBetweenTries}"
+    else
+      Log::displayError "The command has failed after ${retriesCount} attempts."
+      return 1
+    fi
+  done
+  return 0
 }
 
 # @description retrieve linux distributor id
@@ -2431,7 +2454,7 @@ File::garbageCollect() {
 
 # FUNCTIONS
 
-Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+3TTU+DMBgHcM79FI/Mk3FAYYU4w2E6zEjULZHFg/GArARiAwuwqXF+d8vUzBh1M24a4/O7ENonffu3mq5snCE5jNVf6jDj9feFQlu2YZrModSS7U6LGgqwzS9NUSZlFRYAyk0pPq1b1v9Habp2FZZJc8SnTZ5NN3IbVs6fUtO0TMWg1LEY5v8T3uY/LvI4FVwbrfEmrJq/bTBT9sj8Ldt0MP+f8HH+47sqyTOtTL49x7L8Hdua5+8YjLVYS+bPmGkrYKxhf0v98/wbW/pVmun1HSCN9SIN6PbhtB+A1/WDXQh6/hkc+cceHHZO4cCD4aDbCbwunPtBrz8M6lL/0Fv7MsjFBbS37wedoPfQBteFHVX+9von3oOuiTwKRX0EbXUHLi9hNoO60FXfqXgeQyX8dpwX1byQyF2KPBxBlaQlTNOimoRCPiSSxiDnbcawGGnRWz6/Lkvbmx9/GFXpNKy4KpewL4fiGQFoQJlwIaKER9dQ5pMi4q4u36meTYSQ/U9NXxufxCn57SuHEEIIIYQQQgghhBBCCCGEEEJoAx4Br0hwxwAoAAA="
+Compiler::Embed::extractDirFromBase64 "${TMPDIR:-/tmp}/conf_dir" "H4sIAAAAAAAAA+3TTU/CMBgH8J37KR6HJyPb2lGWYDigzLBEhcQRD4bDHCVbbDayDdSI391OMRijonFgjM/vsqx90rd/a5jaxlmKw3n5pQ63Xn9faLTRtBjjDqW2anca1NKAb35pmjbLiyAD0G5y+Wnduv4/yjCNqyCP6mMxr4tkvpHb8OX8KWXMZppFqWNzzH8b3uY/zdJJLIUxrvAmfDX/psWZ6lH5203mYP7b8HH+07siShMjj348x7r8He6U+VObWU1uN1T+nDNbA6uC/a31z/Ov7ZhXcWKWd4DUqkVq0O3DWd8Ht+v5++D3vHM49k5cOOqcwaELw0G347tduPD8Xn/ol6XekVv5MsjlJbR27wcdv/fQgnYb9nT12+ufug+mIdMwkOURtPQ9GI1gsYCysK2/U7EcQyfidppmxVMhUbuUaTCGIopzmMdZMQukekgknoCatz6B1Uir3nz5uuynww/CIp4HhdDVAg7UQCIhADXIIyFlGInwGvJ0loWibapXaiYzKVX/c9N3RieTmPz2dUMIIYQQQgghhBBCCCGEEEIIIbQhj0sk7yEAKAAA"
 
 declare -gx embed_dir_conf_dir="${TMPDIR:-/tmp}/conf_dir"
 
@@ -2449,13 +2472,14 @@ Compiler::Facade::requireCommandBinDir
 if Assert::functionExists initFacade; then
   initFacade
 fi
+LOAD_LOCALE_CONFIG="1"
 Engine::Config::loadConfig
 # @description create sudoer file and add traps to remove it at the end
 # @arg $1 sudoerFile:String the file path to create
 # @env USERNAME
 # shellcheck disable=SC2317
 local sudoerFile="${SUDOER_FILE_PREFIX}/etc/sudoers.d/bash-dev-env-no-password"
-if [[ -f "${sudoerFile}" ]]; then
+if [[ -f "${sudoerFile}" ]] || sudo test -f "${sudoerFile}"; then
   # sudoerFile probably already managed by parent script
   true
 else
@@ -3253,7 +3277,43 @@ breakOnConfigFailure() { :; }
 breakOnTestFailure() { :; }
 # jscpd:ignore-end
 
+isUbuntuMinimum24() {
+  Version::compare "${VERSION_ID}" "24.04"
+}
+
 install() {
+  if isUbuntuMinimum24; then
+    installFromUbuntu24
+  else
+    installFromUbuntu20
+  fi
+}
+
+installFromUbuntu24() {
+  local -a packages=(
+    build-essential
+    python3
+    python-is-python3
+    python3-pip
+    python3-virtualenv
+  )
+  Linux::Apt::installIfNecessary --no-install-recommends "${packages[@]}"
+
+  mkdir -p \
+    "${HOME}/.local/bin" \
+    "${HOME}/.local/lib"
+
+  # shellcheck disable=SC2154
+  Conf::copyStructure \
+    "${embed_dir_conf_dir}" \
+    "${CONF_OVERRIDE_DIR}/$(scriptName)" \
+    ".bash-dev-env"
+
+  # Upgrade of pip packages will be done on subsequent calls during upgrade cron
+  upgradePipPackages
+}
+
+installFromUbuntu20() {
   SKIP_APT_GET_UPDATE=1 Linux::Apt::addRepository ppa:deadsnakes/ppa
   local -a packages=(
     build-essential
@@ -3300,9 +3360,13 @@ removeDuplicatePipPackages() {
 
 testInstall() {
   local -i failures=0
-  # since virtualenv is not loaded python 3.9 is not yet available
-  Version::checkMinimal "python" "--version" "3.8.10" || ((++failures))
-  Version::checkMinimal "virtualenv" "--version" "20.25.1" || ((++failures))
+  if isUbuntuMinimum24; then
+    Version::checkMinimal "python" "--version" "3.12.3" || ((++failures))
+  else
+    # since virtualenv is not loaded python 3.9 is not yet available
+    Version::checkMinimal "python" "--version" "3.8.10" || ((++failures))
+  fi
+  Version::checkMinimal "virtualenv" "--version" "20.25.0" || ((++failures))
   Assert::fileExists "${HOME}/.bash-dev-env/profile.d/python.sh" || ((++failures))
   return "${failures}"
 }
@@ -3312,11 +3376,11 @@ configure() {
   mkdir -p "${HOME}/.virtualenvs" || true
   mkdir -p "${HOME}/.pip/cache" || true
 
-  # create python3.9 virtual env
+  # create python3 virtual env
   # virtualenv (for Python 3) and venv (for Python 2)
   # allows you to manage separate package installations
   # for different projects.
-  virtualenv --system-site-packages --python=/usr/bin/python3.9 "${HOME}/.virtualenvs/python3.9"
+  virtualenv --system-site-packages --python=/usr/bin/python3 "${HOME}/.virtualenvs/python3"
   upgradePipPackages
 }
 
@@ -3324,10 +3388,12 @@ upgradePipPackages() {
   if [[ "${PIP_PACKAGES_UPGRADED:-0}" = "1" ]]; then
     return 0
   fi
-  if [[ -f "${HOME}/.virtualenvs/python3.9/bin/activate" ]]; then
+  if [[ -f "${HOME}/.virtualenvs/python3/bin/activate" ]]; then
     # load this virtualenv
     # shellcheck source=/dev/null
-    source "${HOME}/.virtualenvs/python3.9/bin/activate"
+    source "${HOME}/.virtualenvs/python3/bin/activate"
+
+    Log::displayInfo "Upgrading virtualenv pip packages"
 
     # remove duplicate pip packages with ~ prefix that breaks pip packages upgrade otherwise
     find "${VIRTUAL_ENV}/lib/python3.9/site-packages" -name '~*' -exec rm -Rf {} ';' || true
@@ -3341,10 +3407,14 @@ upgradePipPackages() {
 testConfigure() {
   local -i failures=0
   # shellcheck source=/dev/null
-  source "${HOME}/.virtualenvs/python3.9/bin/activate" || ((++failures))
-  Version::checkMinimal "python" "--version" "3.9.18" || ((++failures))
+  source "${HOME}/.virtualenvs/python3/bin/activate" || ((++failures))
+  if isUbuntuMinimum24; then
+    Version::checkMinimal "python" "--version" "3.12.3" || ((++failures))
+  else
+    Version::checkMinimal "python" "--version" "3.9.18" || ((++failures))
+  fi
   Version::checkMinimal "pip" "--version" "24.0" || ((++failures))
-  [[ "${VIRTUAL_ENV}" = "${HOME}/.virtualenvs/python3.9" ]] || {
+  [[ "${VIRTUAL_ENV}" = "${HOME}/.virtualenvs/python3" ]] || {
     Log::displayError "Virtualenv has not been loaded correctly"
     ((++failures))
   }
