Export script with test

diff --git a/installScripts/Export b/installScripts/Export
--- a/installScripts/Export
+++ b/installScripts/Export
@@ -87,12 +87,14 @@ export TMPDIR
 # temp dir cleaning
 # shellcheck disable=SC2317
 cleanOnExit() {
+  local rc=$?
   if [[ "${KEEP_TEMP_FILES:-0}" = "1" ]]; then
     Log::displayInfo "KEEP_TEMP_FILES=1 temp files kept here '${TMPDIR}'"
   elif [[ -n "${TMPDIR+xxx}" ]]; then
     Log::displayDebug "KEEP_TEMP_FILES=0 removing temp files '${TMPDIR}'"
     rm -Rf "${TMPDIR:-/tmp/fake}" >/dev/null 2>&1
   fi
+  exit "${rc}"
 }
 trap cleanOnExit EXIT HUP QUIT ABRT TERM
 
@@ -222,6 +224,74 @@ Array::wrap2() {
       printCurrentLine
     fi
   ) | sed -E -e 's/[[:blank:]]+$//'
+}
+
+# @description asserts that directory does not exist
+# check if directory empty using ls -A
+# if pattern provided, apply grep -v with this pattern on ls -A result
+# @arg $1 directory:String
+# @arg $2 pattern:String list of files considered to be present in the directory
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode 1 directory does not exists
+# @exitcode 2 directory arg is actually a file
+# @exitcode 3 directory not empty
+# @env SUDO String allows to use custom sudo prefix command
+# @stderr diagnostics information is displayed
+# @example pattern can be .gitkeep
+Assert::dirEmpty() {
+  local directory="$1"
+  local pattern="${2:-}"
+  local -a filter=(cat)
+  if [[ -n "${pattern}" ]]; then
+    filter=(grep -v "${pattern}")
+  fi
+  Log::displayInfo "Checking directory ${directory} is empty"
+  if ${SUDO:-} test -f "${directory}"; then
+    Log::displayError "${directory} is actually a file"
+    return 2
+  fi
+  if ! ${SUDO:-} test -d "${directory}"; then
+    Log::displayError "Directory ${directory} does not exist"
+    return 1
+  fi
+  if [[ "$(${SUDO:-} ls -A "${directory}" | "${filter[@]}")" != "" ]]; then
+    if [[ -z "${pattern}" ]]; then
+      Log::displayError "Directory ${directory} is not considered as empty"
+    else
+      Log::displayError "Directory ${directory} is not considered as empty using pattern '${pattern}'"
+    fi
+    return 3
+  fi
+}
+
+# @description asserts that directory does not exist
+# @arg $1 dir:String
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode 1 existing dir
+# @env SUDO String allows to use custom sudo prefix command
+# @stderr diagnostics information is displayed
+Assert::dirNotExists() {
+  local dir="$1"
+  Log::displayInfo "Checking directory ${dir} does not exist"
+  if ${SUDO:-} test -d "${dir}" &>/dev/null; then
+    Log::displayError "Directory ${dir} still exists"
+    return 1
+  fi
+}
+
+# @description asserts that file does not exist
+# @arg $1 file:String
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode 1 existing file
+# @env SUDO String allows to use custom sudo prefix command
+# @stderr diagnostics information is displayed
+Assert::fileNotExists() {
+  local file="$1"
+  Log::displayInfo "Checking file ${file} does not exist"
+  if ${SUDO:-} test -f "${file}" &>/dev/null; then
+    Log::displayError "file ${file} still exists"
+    return 1
+  fi
 }
 
 # @description checks if function name provided exists
@@ -1770,9 +1840,11 @@ if [[ -f "${sudoerFile}" ]]; then
   true
 else
   cleanSudoer() {
+    local rc=$?
     if [[ -f "${sudoerFile}" ]]; then
       ${SUDO:-sudo} rm -f "${sudoerFile}" || true
     fi
+    exit "${rc}"
   }
   trap cleanSudoer EXIT HUP QUIT ABRT TERM
 
@@ -2567,7 +2639,6 @@ configure() {
       Log::displayInfo "==> Clean up before export"
       set -x
       rm -Rf "${BACKUP_DIR:?}/"* || true
-      rm -Rf "/tmp/"* || true
       rm -Rf "${USER_HOME}/.vscode-server" || true
       rm -f "${USER_HOME}/.gitconfig" || true
       rm -f "${USER_HOME}/.ssh/id_rsa" || true
@@ -2576,18 +2647,17 @@ configure() {
       rm -f "${USER_HOME}/.saml2aws" || true
       rm -f "${USER_HOME}/.aws/credentials" || true
       rm -f "${USER_HOME}/.aws/config" || true
-      rmFolderExceptGitkeep() {
+
+      deleteFolderExcept() {
         local folder="$1"
-        (
-          shopt -s extglob
-          cd "${folder}"
-          rm -Rvf !(.gitkeep)
-        ) || true
+        ${SUDO:-} find "${folder}" \
+          -mindepth 1 -maxdepth 1 -not -name '.gitkeep' -exec rm -R {} ';' || true
       }
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/conf.override/" || true
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/logs/" || true
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/megalinter-reports/" || true
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/backup/" || true
+
+      SUDO=sudo deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/megalinter-reports/"
+      deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/conf.override/"
+      deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/logs/"
+      deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/backup/"
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/.history" || true
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/pages/docs" || true
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/vendor/vendor" || true
@@ -2596,8 +2666,8 @@ configure() {
       rm -f "${BASH_DEV_ENV_ROOT_DIR}/.env" || true
       rm -f "${BASH_DEV_ENV_ROOT_DIR}/.env.distro" || true
 
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/megalinter-reports/" || true
-      rmFolderExceptGitkeep "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/logs/" || true
+      SUDO=sudo deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/megalinter-reports/"
+      deleteFolderExcept "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/logs/"
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/.history"
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/vendor"
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/pages/doc"
@@ -2606,12 +2676,55 @@ configure() {
       rm -Rf "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/node_modules"
       rm -f "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/commit-msg.md"
     )
+    if command -v docker; then
+      Log::displayInfo "Cleaning docker system"
+      docker system prune -a --volumes --force || true
+    fi
   else
     Log::displaySkipped "--export option has not been selected"
   fi
 }
 
-testConfigure() { :; }
+testConfigure() {
+  local -i failures
+  if [[ "${PREPARE_EXPORT}" = "1" ]]; then
+    Assert::fileNotExists "${USER_HOME}/.vscode-server" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.gitconfig" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.ssh/id_rsa" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.ssh/config" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.ssh/known_hosts.old" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.saml2aws" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.aws/credentials" || ((++failures))
+    Assert::fileNotExists "${USER_HOME}/.aws/config" || ((++failures))
+
+    SUDO=sudo Assert::dirEmpty \
+      "${BASH_DEV_ENV_ROOT_DIR}/megalinter-reports/" \
+      ".gitkeep" || ((++failures))
+    Assert::dirEmpty "${BASH_DEV_ENV_ROOT_DIR}/conf.override/" ".gitkeep" || ((++failures))
+    Assert::dirEmpty "${BASH_DEV_ENV_ROOT_DIR}/logs/" ".gitkeep" || ((++failures))
+    Assert::dirEmpty "${BASH_DEV_ENV_ROOT_DIR}/backup/" ".gitkeep" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/.history" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/pages/docs" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/vendor" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/node_modules" || ((++failures))
+    Assert::fileNotExists "${BASH_DEV_ENV_ROOT_DIR}/TODO.local.md" || ((++failures))
+    Assert::fileNotExists "${BASH_DEV_ENV_ROOT_DIR}/.env" || ((++failures))
+    Assert::fileNotExists "${BASH_DEV_ENV_ROOT_DIR}/.env.distro" || ((++failures))
+
+    SUDO=sudo Assert::dirEmpty \
+      "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/megalinter-reports/" \
+      ".gitkeep" || ((++failures))
+    Assert::dirEmpty "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/logs/" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/.history" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/vendor" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/pages/doc" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/pages/bashDoc" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/pages/tests" || ((++failures))
+    Assert::dirNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/node_modules" || ((++failures))
+    Assert::fileNotExists "${BASH_DEV_ENV_ROOT_DIR}/vendor/bash-tools-framework/commit-msg.md" || ((++failures))
+  fi
+  return "${failures}"
+}
 
 local action=$1
 shift || true
