Engine::Config::requireWslu fixed wsl interoperability issue due to wsl bug

diff --git a/installScripts/Export b/installScripts/Export
--- a/installScripts/Export
+++ b/installScripts/Export
@@ -282,6 +282,9 @@ GIT_USERNAME=""
 # email used for git 'ldap@domain.com'
 GIT_USER_MAIL=""
 
+# hostname of the distro
+DISTRO_HOSTNAME="wslHost"
+
 # conf files that will be used to configure the different tools
 CONF_DIR="${BASH_DEV_ENV_ROOT_DIR}/conf"
 
@@ -397,7 +400,7 @@ Engine::Config::loadConfig() {
   Engine::Config::loadUserVariables
   Engine::Config::loadHostIp
 
-  #Engine::Config::requireWslu
+  Engine::Config::requireWslu
 
   #Linux::Wsl::initEnv
   Engine::Config::loadWslVariables
@@ -1065,6 +1068,26 @@ Engine::Config::loadWslVariables() {
   return "${errorCount}"
 }
 
+# @description install apt wslu if necessary providing wslvar, wslpath
+Engine::Config::requireWslu() {
+  if ! command -v wslvar &>/dev/null; then
+    Log::displayInfo "Installing pre-requisite Wslu : wslvar, wslpath, ... commands"
+    Linux::Apt::update
+    Linux::Apt::install --no-install-recommends wslu
+
+    # @see https://github.com/microsoft/WSL/issues/8843#issuecomment-1792256894
+    Log::displayInfo "Fix wsl interoperability due to wsl bug"
+    if [[
+      ! -f /usr/lib/binfmt.d/WSLInterop.conf &&
+      ! -f /etc/systemd/system/wsl-binfmt.service &&
+      -f /run/systemd/generator.early/wsl-binfmt.service
+    ]]; then
+      sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
+      sudo ln -s /run/systemd/generator.early/wsl-binfmt.service /etc/systemd/system/wsl-binfmt.service
+    fi
+  fi
+}
+
 # @description prepend directories to the PATH environment variable
 # @arg $@ args:String[] list of directories to prepend
 # @set PATH update PATH with the directories prepended
@@ -1301,7 +1324,7 @@ Assert::wsl() {
 # @env USERGROUP (default: root) the group name that will be used to set target files ownership
 # @env BASE_MNT_C String windows C drive base PATH
 # @env FRAMEWORK_ROOT_DIR used to make paths relative to this directory to reduce length of messages
-# @env SUDO_USER String the user to use as sudoer
+# @env SUDO String allows to use custom sudo prefix command
 Install::file() {
   local fromFile="$1"
   local targetFile="$2"
@@ -1331,8 +1354,8 @@ Install::file() {
   local targetDir
   targetDir="$(dirname "${targetFile}")"
   if [[ ! -d "${targetDir}" ]]; then
-    ${SUDO} mkdir -p "${targetDir}"
-    ${SUDO} chown "${userName}":"${userGroup}" "${targetDir}"
+    ${SUDO:-} mkdir -p "${targetDir}"
+    ${SUDO:-} chown "${userName}":"${userGroup}" "${targetDir}"
   fi
   local fromDir
   fromDir="$(dirname "${fromFile}")"
@@ -1341,7 +1364,7 @@ Install::file() {
 
   Backup::file "${targetFile}" || return 2
 
-  if ${SUDO} cp "${fromFile}" "${targetFile}"; then
+  if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
     ${successCallback} "${fromFile}" "${targetFile}" "$@"
     Log::displaySuccess "Installed file '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
   else
@@ -1354,12 +1377,30 @@ Install::file() {
 # @arg $1 fromFile:String
 # @arg $2 targetFile:String
 # @exitcode 1 on any failure
+# @env SUDO String allows to use custom sudo prefix command
 # @see Install::file
 Install::setUserRootCallback() {
   # shellcheck disable=SC2034 # $1 not used
   local fromFile="$1"
   local targetFile="$2"
-  chown root:root "${targetFile}"
+  ${SUDO:-} chown root:root "${targetFile}"
+}
+
+# @description apt-get install
+# @arg $@ softwares:String[] list of softwares to install
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::install() {
+  Retry::default sudo apt-get install -y -q "$@"
+}
+
+# @description update apt packages list
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::update() {
+  Retry::default sudo apt-get update -y --fix-missing -o Acquire::ForceIPv4=true
 }
 
 # @description retrieve path from wslvar and then use wslpath to resolve it
@@ -1520,6 +1561,7 @@ Assert::validVariableName() {
 # @description Backup given file in the same directory appending _ followed by the current date
 # @arg $1 file:String the file to backup
 # @stderr messages about backup file location
+# @env SUDO String allows to use custom sudo prefix command
 # @exitcode 1 on copy failure
 Backup::file() {
   local file="$1"
@@ -1527,7 +1569,7 @@ Backup::file() {
   if [[ -f "${file}" ]]; then
     backupFile="${file}_$(date +"%Y-%m-%d_%H:%M:%S")"
     Log::displayInfo "Backup file '${file}' to ${backupFile}"
-    cp "${file}" "${backupFile}"
+    ${SUDO:-} cp "${file}" "${backupFile}"
   fi
 }
 
@@ -1572,6 +1614,7 @@ Cache::getPropertyValue() {
 # @arg $4 userGroup:String (optional) (default: ${USERNAME}) the group name that will be used to set target files ownership
 # @env USERNAME (default: root) the user name that will be used to set target files ownership
 # @env USERGROUP (default: root) the group name that will be used to set target files ownership
+# @env SUDO String allows to use custom sudo prefix command
 # @exitcode 1 on any failure
 # @see Install::file
 Install::setUserRightsCallback() {
@@ -1581,7 +1624,7 @@ Install::setUserRightsCallback() {
   local userName="${3:-${USERNAME:-root}}"
   local userGroup="${4:-${USERGROUP:-root}}"
 
-  chown "${userName}":"${userGroup}" "${targetFile}"
+  ${SUDO:-} chown "${userName}":"${userGroup}" "${targetFile}"
 }
 
 # @description install callback
@@ -1638,6 +1681,22 @@ Log::displaySuccess() {
 Log::logSkipped() {
   if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
     Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
+}
+
+# @description Retry a command 5 times with a delay of 15 seconds between each attempt
+# @arg $@ command:String[] the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+Retry::default() {
+  Retry::parameterized 5 15 "" "$@"
+}
+
+# @description ensure linux distribution is ubuntu
+# @exitcode 1 if linux distribution is not ubuntu
+Linux::requireUbuntu() {
+  if ! Array::contains "$(Linux::getDistributorId)" "Ubuntu" "Debian"; then
+    Log::fatal "this script should be executed under Ubuntu or Debian OS"
   fi
 }
 
@@ -1725,12 +1784,57 @@ Linux::Wsl::originalWslpath() {
   wslpath "$@"
 }
 
+# @description retrieve linux distributor id
+# @noargs
+# @exitcode 1 if lsb_release fails or not found
+# @stdout the linux distributor id
+Linux::getDistributorId() {
+  lsb_release -a 2>/dev/null | sed -En 's/Distributor ID:[ \t]+(.+)/\1/p'
+}
+
 # @description log message to file
 # @arg $1 message:String the message to display
 Log::logSuccess() {
   if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
     Log::logMessage "${2:-SUCCESS}" "$1"
   fi
+}
+
+# @description Retry a command several times depending on parameters
+# @arg $1 maxRetries:int    $1 max retries
+# @arg $2 delay:int between attempt
+# @arg $3 message:String to display to describe the attempt
+# @arg $@ rest of parameters, the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+# @exitcode 2 if maxRetries invalid value
+Retry::parameterized() {
+  local maxRetries=$1
+  shift || true
+  local delayBetweenTries=$1
+  shift || true
+  local message="$1"
+  shift || true
+  local retriesCount=1
+  if [[ "${maxRetries}" -lt 1 ]]; then
+    Log::displayError "invalid maxRetry value"
+    return 2
+  fi
+
+  while true; do
+    Log::displayInfo "Attempt ${retriesCount}/${maxRetries}: ${message}"
+    if "$@"; then
+      break
+    elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
+      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      ((retriesCount++))
+      sleep "${delayBetweenTries}"
+    else
+      Log::displayError "The command has failed after ${retriesCount} attempts."
+      return 1
+    fi
+  done
+  return 0
 }
 
 # FUNCTIONS
@@ -1740,6 +1844,7 @@ facade_main_Exportsh() {
 Env::requireLoad
 UI::requireTheme
 Log::requireLoad
+Linux::requireUbuntu
 Linux::Wsl::requireWsl
 Compiler::Facade::requireCommandBinDir
 
