improved Conf::getOverriddenDir
- fixed all file/dir installs to be overridable

diff --git a/installScripts/Font b/installScripts/Font
--- a/installScripts/Font
+++ b/installScripts/Font
@@ -516,6 +516,35 @@ Cache::getPropertyValue2() {
 }
 
 
+# @description convert base64 encoded back to target dir
+# it is advised to include the md5sum of the binFile in the path of the target dir
+#
+# @arg $1 targetDir:string the directory in which tar archive will be untarred
+# @arg $2 base64:string the base64 encoded tar czf archive
+# @stderr diagnostics information is displayed
+Compiler::Embed::extractDirFromBase64() {
+
+  if [[ "${REQUIRE_FUNCTION_LINUX_REQUIRE_TAR_COMMAND_LOADED:-0}" != 1 ]]; then
+    echo >&2 "Requirement Linux::requireTarCommand has not been loaded"
+    exit 1
+  fi
+
+  local targetDir="$1"
+  local base64="$2"
+
+  if [[ ! -d "${targetDir}" ]]; then
+    mkdir -p "${targetDir}"
+    (
+      cd "${targetDir}" || exit 1
+      base64 -d <<<"${base64}" | tar -xzf - 2>/dev/null || {
+        Log::displayError "untar failure, invalid base64 string"
+        exit 1
+      }
+    ) || return 1
+  fi
+}
+
+
 # @description convert base64 encoded back to target file
 # if target file is executable prepend dir of target
 # file to PATH to make binary available everywhere
@@ -546,30 +575,6 @@ Compiler::Embed::extractFileFromBase64() {
 }
 
 
-# @description select right file to load depending if file exists in this order:
-# - from conf.override
-# - from embedded file if provided
-# - from conf dir
-# @arg $1 file:String
-# @arg $2 embedFile:String eventual embedded file
-# @exitcode 1 if file does not exist at all
-Conf::dynamicConfFile() {
-  local file="${1/#\//}" # remove first slash if any
-  local embedFile="${2:-}"
-  if [[ -f "${CONF_OVERRIDE_DIR}/${file}" ]]; then
-    echo "${CONF_OVERRIDE_DIR}/${file}"
-    return 0
-  elif [[ -f "${embedFile}" ]]; then
-    echo "${embedFile}"
-    return 0
-  fi
-  if [[ "${IGNORE_ERROR:-0}" = "0" ]]; then
-    Log::displayWarning "Conf::dynamicConfFile - ${file} does not exist in any config dirs declared"
-    return 1
-  fi
-}
-
-
 # @description generate temp directory where default
 # and overridden directories have been merged
 #   - if overridden dir exists, create a new temp folder
@@ -586,24 +591,25 @@ Conf::dynamicConfFile() {
 # @exitcode 1 if default dir does not exist
 # @exitcode 2 if error during copy
 Conf::getOverriddenDir() {
-  local defaultDir="$1"
-  local overriddenDirPath="$2"
+  local -a overriddenDirPaths=("$@")
+  local overriddenDirPath
 
-  if [[ ! -d "${defaultDir}" ]]; then
-    Log::displayError "Directory ${defaultDir} does not exists"
-    return 1
-  fi
-  if [[ ! -d "${overriddenDirPath}" || -z "$(ls -A "${overriddenDirPath}")" ]]; then
-    Log::displayInfo "Conf::getOverriddenDir - directory ${overriddenDirPath} does not exist, keep default one ${defaultDir}"
-    echo "${defaultDir}"
-    return 0
-  fi
   local tempDir
   tempDir="$(mktemp -d)"
   (
     shopt -s dotglob
-    cp -R "${defaultDir}/." "${tempDir}"
-    cp -R "${overriddenDirPath}/." "${tempDir}"
+    for overriddenDirPath in "${overriddenDirPaths[@]}"; do
+      if [[ -d "${overriddenDirPath}" && -n "$(ls -A "${overriddenDirPath}")" ]]; then
+        Log::displayInfo "Conf::getOverriddenDir - use overridden files from ${overriddenDirPath}"
+        cp -R "${overriddenDirPath}/." "${tempDir}"
+      else
+        if [[ -z "${overriddenDirPath}" ]]; then
+          Log::displayError "Conf::getOverriddenDir - empty overridden directory path"
+        else
+          Log::displayInfo "Conf::getOverriddenDir - directory ${overriddenDirPath} does not exist or is empty"
+        fi
+      fi
+    done
   ) || return 2
   echo "${tempDir}"
 }
@@ -1982,6 +1988,8 @@ Linux::getDistributorId() {
 # @exitcode 1 if tar command not available
 # @stderr diagnostics information is displayed
 Linux::requireTarCommand() {
+  export REQUIRE_FUNCTION_LINUX_REQUIRE_TAR_COMMAND_LOADED=1
+
   Assert::commandExists tar
 }
 
@@ -3225,20 +3233,11 @@ commandOptionParseFinished() {
 
 
 Linux::requireTarCommand
-Compiler::Embed::extractFileFromBase64 \
-  "${PERSISTENT_TMPDIR:-/tmp}/be2391ba4e9ba699f2c44e32c5a7a8f63f0d076ae583018c43343b235159da39/fontScript" \
-  "IzwKIyBSdW4gdGhpcyBhcyBhIENvbXB1dGVyIFN0YXJ0dXAgc2NyaXB0IHRvIGFsbG93IGluc3RhbGxpbmcgZm9udHMgZnJvbSBDOlxJbnN0YWxsRm9udFwKIyBCYXNlZCBvbiBodHRwOi8vd3d3LmVkdWdlZWsubmV0L2ZvcnVtcy93aW5kb3dzLTcvMTIzMTg3LWluc3RhbGxhdGlvbi1mb250cy13aXRob3V0LWFkbWluLXJpZ2h0cy0yLmh0bWwKIyBSdW4gdGhpcyBhcyBhIENvbXB1dGVyIFN0YXJ0dXAgU2NyaXB0IGluIEdyb3VwIFBvbGljeQojIEZ1bGwgZGV0YWlscyBvbiBteSB3ZWJzaXRlIC0gaHR0cHM6Ly9tZWRpYXJlYWxtLmNvbS5hdS9hcnRpY2xlcy93aW5kb3dzLWZvbnQtaW5zdGFsbC1uby1wYXNzd29yZC1wb3dlcnNoZWxsLwojPgoKW0NtZGxldEJpbmRpbmcoU3VwcG9ydHNTaG91bGRQcm9jZXNzKV0KcGFyYW0oCiAgICAjIFNwZWNpZmllcyB0aGUgZm9udCBuYW1lIHRvIGluc3RhbGwuICBEZWZhdWx0IHZhbHVlIHdpbGwgaW5zdGFsbCBhbGwgZm9udHMuCiAgICBbUGFyYW1ldGVyKFBvc2l0aW9uPTApXQogICAgW3N0cmluZ1tdXQogICAgJFNvdXJjZURpciA9ICcnCikKCiREZXN0aW5hdGlvbiA9IChOZXctT2JqZWN0IC1Db21PYmplY3QgU2hlbGwuQXBwbGljYXRpb24pLk5hbWVzcGFjZSgweDE0KQokVGVtcEZvbGRlciAgPSAiJGVudjp0ZW1wXEZvbnRzIgoKIyBDcmVhdGUgdGhlIHNvdXJjZSBkaXJlY3RvcnkgaWYgaXQgZG9lc24ndCBhbHJlYWR5IGV4aXN0Ck5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICRTb3VyY2VEaXIgfCBPdXQtTnVsbAoKTmV3LUl0ZW0gJFRlbXBGb2xkZXIgLVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSB8IE91dC1OdWxsCgpHZXQtQ2hpbGRJdGVtIC1QYXRoICRTb3VyY2UgLUluY2x1ZGUgJyoudHRmJywnKi50dGMnLCcqLm90ZicgLVJlY3Vyc2UgfCBGb3JFYWNoLU9iamVjdCB7CiAgICBJZiAoVGVzdC1QYXRoICIkKCRlbnY6dXNlcnByb2ZpbGUpXEFwcERhdGFcTG9jYWxcTWljcm9zb2Z0XFdpbmRvd3NcRm9udHNcJCgkXy5OYW1lKSIpIHsKICAgICAgICBXcml0ZS1WZXJib3NlICJGb250ICQoJF8uTmFtZSkgYWxyZWFkeSBpbnN0YWxsZWQiCiAgICB9IEVsc2UgewogICAgICAgIFdyaXRlLVZlcmJvc2UgIkluc3RhbGxpbmcgRm9udCAkKCRfLk5hbWUpIC4uLiIKICAgICAgICAkRm9udCA9ICIkVGVtcEZvbGRlclwkKCRfLk5hbWUpIgoKICAgICAgICAjIENvcHkgZm9udCB0byBsb2NhbCB0ZW1wb3JhcnkgZm9sZGVyCiAgICAgICAgQ29weS1JdGVtICQoJF8uRnVsbE5hbWUpIC1EZXN0aW5hdGlvbiAkVGVtcEZvbGRlcgoKICAgICAgICAjIEluc3RhbGwgZm9udAogICAgICAgICREZXN0aW5hdGlvbi5Db3B5SGVyZSgkRm9udCwweDEwKQoKICAgICAgICAjIERlbGV0ZSB0ZW1wb3JhcnkgY29weSBvZiBmb250CiAgICAgICAgUmVtb3ZlLUl0ZW0gJEZvbnQgLUZvcmNlCiAgICAgICAgV3JpdGUtVmVyYm9zZSAiRm9udCAkKCRfLk5hbWUpIEluc3RhbGxlZCBzdWNjZXNzZnVsbHkiCiAgICB9Cn0K" \
-  "644"
+Compiler::Embed::extractDirFromBase64 \
+  "${PERSISTENT_TMPDIR:-/tmp}/d7939bad6b9c0f00af3ffd8a3136c0090ff7b338ce68df82a13ab6196ce1d255/conf_dir" \
+  "H4sIAAAAAAAA/+xWf2/bNhDN3/oUB9uA7aKU5TRZBmMZ0Np1ZqBNgzhYB8TBwEiniBslEuQxirf1uw+kHFsLOnTAlg0D/P4IFfHu3eP9kBn/YNAqZ1K0B8+FJEmSr46OwpokydM1SY5Pds/+/Xj86vjwAJJnU9SCs8TNQfK3Yz093P8ED4SmfJHzFM95iRN4j1aqd2dLOJ9Hu72l+AUnMD6K/mu5e/zDmKuKYm3HzxnjC/N/eHJ0/GT+k+PjZD///wa630RduHQVUCEscAscpqrUjtDAkrghp8GmRmgCUsClVDWIyhKXUlR3kKuKLORGlTCdrBbNhu+pVdSFN9xiBqqCgkhPRqO6rmPM3B3iz3GFNMqVcaUd1aLKVG3ZyWh8+Gr89Qnb8HMSqmIhAqsFFcoR41kpKmbEXUGWHcYFlfLL+peNflHBmVFOw4WSIl1HXZg7KSFD4kJar7NcQ423VhACC6LtZDQqMRPcIJdlnKoy5m7EDYlU4k651/iomlWKaW5trUzGtKrR2AKlHEXdb6PoelpmEumNqDJR3Q2WTmtlyC4L5WR2YVSK1g5vIs0NLwcRAEAXlhpTkQu0QAWGhEPFS/Tl2ISMAWaYcycJ7rl0CLWQ8nHT16wpUxwIry88ORKawYWywuf4NBneNHuWjKjurm+af3vLcDGYCQOn0O9HwyjqzdCSqEJp4BQG51izD7c/YUrApqrcPC79iePXWkuRBtNh7H9drOYpDpKH8dEw6l1hqedKZmgATqHTw+p+Qljqle8e24miLkwNcsJw7OaKApkwmJIyaxA5CIJMoa36BFwa5Nka8EFYiryoBWEJ4e/VWiPMto5srjwTu+BUtE/4G3xwxM6dlNGOoK2SfZ6o7XeGxKaFkFkTvR0C2KJKpcsQ+i9iorz/MqxpWBXlfWCXmDpjPeNcmbc8LR4z+2uoxiKHwRVaamg7vUFImbNotFG5kDhcvdZ6xomv3qmUy9V7kRplVU6rj02fNqld9Qa9H0M9hp3hhtvjoxGE7Hs0t8oidLwt7Ey3Kd60FWad4PkJ3kqLf06z2H0rnjLGcdzZuvXCrm+EXcrbSqOtZRemSq+bQSAF0p8VfOcow41/71231t52U0tP5ie+ic7andwK2g60ER9i7ZS2HGNP/x0aHAT9L5OHcTJsM8xQom/hrbzUa1f5HykvsVT3uJEZEtE011+tzeKxJmBd6r8huZNyvSlQ9Gl/a9tjjz0+h98DAAD//wFSmYMAEAAA"
 
-declare -gx embed_file_fontScript="${PERSISTENT_TMPDIR:-/tmp}/be2391ba4e9ba699f2c44e32c5a7a8f63f0d076ae583018c43343b235159da39/fontScript"
-
-Linux::requireTarCommand
-Compiler::Embed::extractFileFromBase64 \
-  "${PERSISTENT_TMPDIR:-/tmp}/f3bfc0320e9295b3e90b84724fc1359d1a5db56e0722c5ca026496b3d07d37cd/xResources" \
-  "eHRlcm0qZmFjZU5hbWU6IE1lc2xvTEdTIE5GCnh0ZXJtKmZhY2VTaXplOiAxNAo=" \
-  "644"
-
-declare -gx embed_file_xResources="${PERSISTENT_TMPDIR:-/tmp}/f3bfc0320e9295b3e90b84724fc1359d1a5db56e0722c5ca026496b3d07d37cd/xResources"
+declare -gx embed_dir_conf_dir="${PERSISTENT_TMPDIR:-/tmp}/d7939bad6b9c0f00af3ffd8a3136c0090ff7b338ce68df82a13ab6196ce1d255/conf_dir"
 
 
 fontBeforeParseCallback() {
@@ -3293,7 +3292,7 @@ install() {
   Linux::Wsl::cachedWslpath2 windowsTempDir -w "${tempFolder}"
   (
     # shellcheck disable=SC2154
-    cp "${embed_file_fontScript}" "${TMPDIR:-/tmp}/Font.ps1"
+    cp "${embed_dir_conf_dir}/Font.ps1" "${TMPDIR:-/tmp}/Font.ps1"
     local tempFolder
     tempFolder="$(mktemp -p "${TMPDIR:-/tmp}" -d)"
     chmod 777 "${tempFolder}"
@@ -3327,13 +3326,13 @@ testInstall() {
 }
 
 configure() {
-  local fileToInstall
+  local configDir
   # shellcheck disable=SC2154
-  fileToInstall="$(Conf::dynamicConfFile "${scriptName}/.Xresources" "${embed_file_xResources}")" || return 1
+  configDir="$(Conf::getOverriddenDir "${embed_dir_conf_dir}" "$(fullScriptOverrideDir)")"
 
   # shellcheck disable=SC2154
   Install::file \
-    "${fileToInstall}" \
+    "${configDir}/.Xresources" \
     "${HOME}/.Xresources"
 }
 
