Make profiles being able to load any variable
Profiles changes:
- profiles are now able to load any variable like
  CONF_OVERRIDE_DIR, ...
- moved Profiles::loadProfile from bash-tools-framework
- Profiles::loadProfile
  - make it work with full profile path
  - added unit tests
- Profiles::allDepsRecursive
  - make it fails if recursive call is failing
  - fixed unit tests

Other fixes:
  - Fzf - show fortunes only if active shell is zsh
  - Fortune
    - make it fails if fortune generation fails
    - fortune generation displays number of fortunes
      generated by configuration
    - make it compatible with full installScripts path
    - always generate fortune even if SHOW_FORTUNES=0

diff --git a/installScripts/KubeDefaultConfig b/installScripts/KubeDefaultConfig
--- a/installScripts/KubeDefaultConfig
+++ b/installScripts/KubeDefaultConfig
@@ -965,8 +965,14 @@ Git::cloneOrPullIfNoChanges() {
   shift || true
 
   if [[ -d "${dir}/.git" ]]; then
-    if ! Git::pullIfNoChanges "${dir}"; then
-      return 1
+    local exitCode=0
+    Git::pullIfNoChanges "${dir}" || exitCode=$?
+    if Array::contains "${exitCode}" "2" "4"; then
+      # changes detected
+      return 0
+    fi
+    if [[ "${exitCode}" != "0" ]]; then
+      return "${exitCode}"
     fi
     # shellcheck disable=SC2086
     if [[ "$(type -t ${pullCallback})" = "function" ]]; then
@@ -1712,7 +1718,7 @@ Retry::parameterized() {
     if "$@"; then
       break
     elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
-      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      Log::displayDebug "Command failed. Wait for ${delayBetweenTries} seconds"
       ((retriesCount++))
       sleep "${delayBetweenTries}"
     else
@@ -1879,6 +1885,22 @@ Git::pullIfNoChanges() {
     Log::displayInfo "Pull git repository '${dir}' as no changes detected"
     ${SUDO:-} git pull --progress
   )
+}
+
+# @description check if an element is contained in an array
+#
+# @arg $1 needle:String
+# @arg $@ array:String[]
+# @exitcode 0 if found
+# @exitcode 1 otherwise
+# @example
+#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
+Array::contains() {
+  local element
+  for element in "${@:2}"; do
+    [[ "${element}" = "$1" ]] && return 0
+  done
+  return 1
 }
 
 # @description ignore exit code 141 from simple command pipes
@@ -2136,22 +2158,6 @@ Assert::varExistsAndNotEmpty() {
     Log::displayError "${varName} - please provide a value"
     return 2
   fi
-}
-
-# @description check if an element is contained in an array
-#
-# @arg $1 needle:String
-# @arg $@ array:String[]
-# @exitcode 0 if found
-# @exitcode 1 otherwise
-# @example
-#   Array::contains "${libPath}" "${__BASH_FRAMEWORK_IMPORTED_FILES[@]}"
-Array::contains() {
-  local element
-  for element in "${@:2}"; do
-    [[ "${element}" = "$1" ]] && return 0
-  done
-  return 1
 }
 
 # @description check if argument respects ldap login naming convention
