Install::structure usage
- created shortcut Conf::copyStructure
  - applied it on all the configuration
- restored hooks
- added .ignore that allows to be able to select
  specific ignored files in vscode
- removed Conf::installFromEmbedCheck, Conf::installFromEmbed

diff --git a/installScripts/MandatorySoftwares b/installScripts/MandatorySoftwares
--- a/installScripts/MandatorySoftwares
+++ b/installScripts/MandatorySoftwares
@@ -329,6 +329,21 @@ Compiler::Embed::extractDirFromBase64() {
   fi
 }
 
+Conf::copyStructure() {
+  local embedDir="$1"
+  local overrideDir="$2"
+  local subDir="$3"
+  local targetDir="${4:-${USER_HOME}/${subDir}}"
+
+  local configDir
+  # shellcheck disable=SC2154
+  configDir="$(Conf::getOverriddenDir "${embedDir}" "${overrideDir}")"
+  # shellcheck disable=SC2154
+  OVERWRITE_CONFIG_FILES=${OVERWRITE_CONFIG_FILES:-1} \
+  PRETTY_ROOT_DIR="$(dirname "${embedDir}")" \
+  Install::structure "${configDir}/${subDir}" "${targetDir}"
+}
+
 # @description generate temp directory where default
 # and overridden directories have been merged
 #   - if overridden dir exists, create a new temp folder
@@ -576,86 +591,6 @@ Framework::createTempFile() {
   mktemp -p "${TMPDIR:-/tmp}" -t "${1:-}.XXXXXXXXXXXX"
 }
 
-# @description install dir to given directory but backup it before
-# @arg $1 fromDir:String the source base directory
-# @arg $2 toDir:String the target base directory
-# @arg $3 dirName:String the directory relative to fromDir arg that will be copied
-# @arg $4 userName:String (optional) (default: ${USERNAME}) the user name that will be used to set target files ownership
-# @arg $5 userGroup:String (optional) (default: ${USERNAME}) the group name that will be used to set target files ownership
-# @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing directory
-# @env CHANGE_WINDOWS_FILES Boolean (default:0) if 1 and target directory is in windows file system, overwrite it
-# @env USERNAME (default: root) the user name that will be used to set target files ownership
-# @env USERGROUP (default: root) the group name that will be used to set target files ownership
-# @env BASE_MNT_C String windows C drive base PATH
-# @env FRAMEWORK_ROOT_DIR used to make paths relative to this directory to reduce length of messages
-# @env SUDO String allows to use custom sudo prefix command
-# @env BACKUP_BEFORE_INSTALL Boolean (default:1) backup directory before installing the dir
-# @exitcode 1 if source directory is not readable
-# @exitcode 2 if source directory backup failed
-# @exitcode 0 if copy successful or OVERWRITE_CONFIG_FILES=0 or
-# @exitcode 0 with warning message if OVERWRITE_CONFIG_FILES=0 and target directory exists
-# @exitcode 0 with warning message if CHANGE_WINDOWS_FILES=0 and target directory in C drive
-# @stderr diagnostics information is displayed, skipped information if OVERWRITE_CONFIG_FILES or CHANGE_WINDOWS_FILES are set to 1
-Install::dir() {
-  local fromDir="$1"
-  local toDir="$2"
-  local dirName="$3"
-  local userName="${4:-${USERNAME:-root}}"
-  local userGroup="${5:-${USERGROUP:-root}}"
-
-  if [[ ! -d "${fromDir}/${dirName}" || ! -r "${fromDir}/${dirName}" ]]; then
-    Log::displayError "cannot read source directory '${fromDir}/${dirName}'"
-    return 1
-  fi
-
-  # skip if OVERWRITE_CONFIG_FILES=0 and target dir exists
-  if [[ "${OVERWRITE_CONFIG_FILES:-0}" = "0" && -d "${toDir}/${dirName}" ]]; then
-    Log::displayWarning "Directory '${toDir}/${FILENAME}' exists - Skip install "
-    return 0
-  fi
-
-  # skip if CHANGE_WINDOWS_FILES is 0 and target dir is c drive
-  if [[ "${CHANGE_WINDOWS_FILES:-0}" = "0" && "${toDir}" =~ ^${BASE_MNT_C} ]]; then
-    Log::displayWarning "Directory '${fromDir}' - Skip install (because CHANGE_WINDOWS_FILES=0 in .env file)"
-    return 0
-  fi
-
-  if [[ "${BACKUP_BEFORE_INSTALL:-1}" = "1" ]]; then
-    Backup::dir "${toDir}" "${dirName}" || return 2
-  fi
-
-  local destDir="${toDir}/${dirName}"
-  local shortDir="${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${dirName}"
-  Log::displayDebug "Installing directory '${destDir}' from '${shortDir}'"
-  (
-    ${SUDO:-} mkdir -p "${destDir}"
-    cd "${fromDir}/${dirName}" || exit 1
-    shopt -s dotglob # * will match hidden files too
-    if [[ -z "$(ls -A .)" ]]; then
-      Log::displaySkipped "directory '${shortDir}' is empty, no copy needed"
-      return 0
-    fi
-    if ! ${SUDO:-} cp -R -- * "${destDir}"; then
-      Log::displayError "unable to copy directory '${shortDir}' to '${destDir}'"
-      exit 1
-    fi
-    if ! ${SUDO:-} chown -R "${userName}":"${userGroup}" "${destDir}"; then
-      Log::displayError "unable to change directory '${destDir}' owners"
-      exit 1
-    fi
-    # chown all parent directory with same user
-    local fullDir="${fromDir}"
-    for parentFolder in ${dirName////$'\n'}; do
-      fullDir="${fullDir}/${parentFolder}"
-      if ! ${SUDO:-} chown "${userName}":"${userGroup}" "${fullDir}"; then
-        Log::displayError "unable to change parent directory '${fullDir}' owners"
-        exit 1
-      fi
-    done
-  ) || return 1
-  Log::displaySuccess "Installed directory '${destDir}' from '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${dirName}')"
-}
-
 # @description installs file to given directory
 #
 # callbacks parameters `${fromFile} ${targetFile} $@`
@@ -716,16 +651,26 @@ Install::file() {
   local fromFilename
   fromFilename="$(basename "${fromFile}")"
 
-  if [[ "${BACKUP_BEFORE_INSTALL:-1}" = "1" ]]; then
+  local prettyFromDir
+  # shellcheck disable=SC2295
+  prettyFromDir="${fromDir#${PRETTY_ROOT_DIR:-${FRAMEWORK_ROOT_DIR}}/}"
+  if diff -q "${fromFile}" "${targetFile}" &>/dev/null; then
+    Log::displayStatus "No changes detected. No need to update '${targetFile}' from '${prettyFromDir}/${fromFilename}'"
+    return 0
+  fi
+
+  if [[ "${BACKUP_BEFORE_INSTALL:-1}" = "1" ]] ; then
     Backup::file "${targetFile}" || return 2
   fi
 
   if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
-    Log::displaySuccess "Installed file '${targetFile}' from '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}'"
-    ${successCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
+    # shellcheck disable=SC2295
+    Log::displaySuccess "Installed file '${targetFile}' from '${prettyFromDir}/${fromFilename}'"
+    ${successCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${prettyFromDir}" "${fromFilename}"
   else
-    Log::displayError "unable to copy file '${targetFile}' from '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}'"
-    ${failureCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${fromDir#"${FRAMEWORK_ROOT_DIR}/"}" "${fromFilename}"
+    # shellcheck disable=SC2295
+    Log::displayError "unable to copy file '${targetFile}' from '${fromDir#${FRAMEWORK_ROOT_DIR}/}/${fromFilename}'"
+    ${failureCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${prettyFromDir}" "${fromFilename}"
     return 3
   fi
 }
@@ -775,7 +720,8 @@ InstallScripts::command() {
   local installStatus="0"
   sourceHook() {
     local hookName="$1"
-    hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh")"
+    # shellcheck disable=SC2154
+    hook="$(IGNORE_ERROR=1 Conf::dynamicConfFile "${scriptName}/${hookName}.sh" "${embed_dir_hooks_dir}/${hookName}.sh")"
     if [[ -x "${hook}" ]]; then
       # shellcheck source=src/_binaries/SimpleTest/conf/preInstall.sh
       source "${hook}" || exit 1
@@ -1183,48 +1129,6 @@ Assert::tty() {
   [[ -t 1 || -t 2 ]]
 }
 
-# @description Backup given directory in the base directory or in BACKUP_DIR directory
-# backup directory name is composed by following fields separated by _:
-#   - if BACKUP_DIR is not empty then escaped full dirname separated by @
-#   - date with format %Y%m%d_%H:%M:%S (Eg: 20240326_14:45:08)
-#   - .tgz extension
-#
-# @arg $1 string the base directory
-# @arg $2 string the directory to backup from base directory
-#
-# @env BACKUP_DIR String variable referencing backup directory
-# @env FRAMEWORK_ROOT_DIR String  used to remove this project directory from displayed backup path
-# @env SUDO String allows to use custom sudo prefix command
-#
-# @exitcode 1 if directory to backup does not exist, 0 if everything is OK
-# @exitcode 2 on backup failure
-#
-# @stderr message about where the directory is backed up
-# @require Linux::requireTarCommand
-Backup::dir() {
-  local escapedDirname backupFile
-  local fromDir="$1"
-  local dirname="$2"
-
-  if [[ ! -d "${fromDir}/${dirname}" ]]; then
-    Log::displayError "Backup::dir - directory '${fromDir}/${dirname}' doesn't exist"
-    return 1
-  fi
-  if [[ -z "${BACKUP_DIR:-}" ]]; then
-    escapedDirname="$(sed -e 's#^/##; s#/#@#g' <<<"${dirname}")"
-    backupFile="${fromDir}/${escapedDirname}-$(date +"%Y%m%d_%H:%M:%S").tgz"
-  else
-    escapedDirname="$(sed -e 's#^/##; s#/#@#g' <<<"${fromDir}/${dirname}")"
-    backupFile="${BACKUP_DIR}/${escapedDirname}-$(date +"%Y%m%d_%H:%M:%S").tgz"
-  fi
-
-  Log::displayInfo "Backup directory '${fromDir}/${dirname}' to ${backupFile}"
-  if ! ${SUDO:-} tar --same-owner -czf "${backupFile}" "${fromDir}/${dirname}" 2>/dev/null; then
-    Log::displayError "cannot backup '${fromDir}/${dirname}'"
-    return 2
-  fi
-}
-
 # @description Backup given file in the same directory or in BACKUP_DIR directory
 # backup file name is composed by following fields separated by -:
 #   - if BACKUP_DIR is not empty then escaped dirname separated by @
@@ -1553,6 +1457,101 @@ Env::pathPrepend() {
   done
 }
 
+# @description install dir to given directory but backup it before
+# @arg $1 fromDir:String the source base directory
+# @arg $2 toDir:String the target base directory
+# @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing files
+# @env CHANGE_WINDOWS_FILES Boolean (default:0) if 1 and target directory is in windows file system, overwrite it
+# @env USERNAME (default: ${USERNAME} if SUDO empty else root) the user name that will be used to set target files ownership
+# @env USERGROUP (default: ${USERGROUP} if SUDO empty else root) the group name that will be used to set target files ownership
+# @env BASE_MNT_C String windows C drive base PATH
+# @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
+# @env SUDO String allows to use custom sudo prefix command
+# @env BACKUP_BEFORE_INSTALL Boolean (default:1) backup directory before installing the dir
+# @exitcode 1 if source directory is not readable
+# @exitcode 2 if error during structure replication
+# @exitcode 2 if error during file copy
+# @exitcode 0 if copy successful
+# @exitcode 0 with warning message if CHANGE_WINDOWS_FILES=0 and target directory in C drive
+# @stderr diagnostics information is displayed, skipped information if OVERWRITE_CONFIG_FILES or CHANGE_WINDOWS_FILES are set to 1
+Install::structure() {
+  local fromDir="$1"
+  local toDir="$2"
+  local userName="root"
+  local userGroup="root"
+  if [[ -z "${SUDO:-}" ]]; then
+    userName="${USERNAME:-root}"
+    userGroup="${USERGROUP:-root}"
+  fi
+
+  if [[ ! -d "${fromDir}" || ! -r "${fromDir}" ]]; then
+    Log::displayError "Install::structure - cannot read source directory '${fromDir}'"
+    return 1
+  fi
+
+  # skip if CHANGE_WINDOWS_FILES is 0 and target dir is c drive
+  if [[ "${CHANGE_WINDOWS_FILES:-0}" = "0" && "${toDir}" =~ ^${BASE_MNT_C} ]]; then
+    Log::displayWarning "Install::structure - Directory '${fromDir}' - Skip install (because CHANGE_WINDOWS_FILES=0 in .env file)"
+    return 0
+  fi
+
+  # first replicate directory structure
+  # shellcheck disable=SC2317
+  createStructure() {
+    local dir="$1"
+    if ! ${SUDO:-} mkdir -p "${dir}"; then
+      Log::displayError "Install::structure - impossible to create directory '${dir}'"
+      exit 1
+    fi
+
+    if ! ${SUDO:-} chown "${userName}":"${userGroup}" "${dir}"; then
+      Log::displayError "Install::structure - impossible to update directory owner '${dir}' with ${userName}:${userGroup}"
+      exit 1
+    fi
+  }
+  local dir
+
+  (
+    local dir
+    shopt -s lastpipe
+    # -links 2 allows to exclude empty directories
+    # %P get file without initial directory
+    ${SUDO:-} find "${fromDir}" -depth -type d -links 2 -printf "%P\0" |
+      while read -rd '' dir; do
+        if ! createStructure "${toDir}/${dir}"; then
+          # error already reported by createStructure
+          exit 1
+        fi
+      done || {
+        if [[ "${PIPESTATUS[0]}" != "0" ]]; then
+          Log::displayError "Install::structure - replicated directory structure - find directories on '${fromDir}' resulted in an error"
+          exit 2
+        fi
+      }
+  ) || return 2
+
+  # for each file, copy it
+  (
+    local file
+    shopt -s lastpipe
+    ${SUDO:-} find "${fromDir}" -depth -type f -printf "%P\0" |
+      while read -rd '' file; do
+          if ! Install::file "${fromDir}/${file}" "${toDir}/${file}"; then
+            # error already reported by Install::file
+            exit 1
+          fi
+      done || {
+        if [[ "${PIPESTATUS[0]}" != "0" ]]; then
+          Log::displayError "Install::structure - replicated file structure - find files on '${fromDir}' resulted in an error"
+          exit 2
+        fi
+      }
+  ) || return 3
+
+  # shellcheck disable=SC2295
+  Log::displaySuccess "Installed directory '${toDir#${PRETTY_ROOT_DIR}/}' from '${fromDir#${PRETTY_ROOT_DIR}/}'"
+}
+
 # @description install callback
 #   default callback used called when file copy has failed
 # @arg $1 fromFile:String
@@ -1600,14 +1599,15 @@ Log::computeDuration() {
   fi
 }
 
-# @description Display message using skip color (yellow)
+# @description Display message using info color (blue) but warning level
 # @arg $1 message:String the message to display
-Log::displaySkipped() {
-  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
+Log::displayStatus() {
+  local type="${2:-STATUS}"
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
     Log::computeDuration
-    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
+    echo -e "${__INFO_COLOR}${type}  - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
   fi
-  Log::logSkipped "$1"
+  Log::logStatus "$1" "${type}"
 }
 
 # @description Display message using success color (bg green/fg white)
@@ -1929,11 +1929,21 @@ Linux::getDistributorId() {
   lsb_release -a 2>/dev/null | sed -En 's/Distributor ID:[ \t]+(.+)/\1/p'
 }
 
+# @description Display message using skip color (yellow)
+# @arg $1 message:String the message to display
+Log::displaySkipped() {
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
+    Log::computeDuration
+    echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_LAST_DURATION_STR}${1}${__RESET_COLOR}" >&2
+  fi
+  Log::logSkipped "$1"
+}
+
 # @description log message to file
 # @arg $1 message:String the message to display
-Log::logSkipped() {
-  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
-    Log::logMessage "${2:-SKIPPED}" "$1"
+Log::logStatus() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_WARNING)); then
+    Log::logMessage "${2:-STATUS}" "$1"
   fi
 }
 
@@ -2121,6 +2131,14 @@ Linux::Wsl::cachedWslpath() {
 # @require Linux::Wsl::requireWsl
 Linux::Wsl::originalWslvar() {
   wslvar "$@" | sed -z '$ s/[\r\n]$//'
+}
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logSkipped() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
+    Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
 }
 
 # @description ensure linux runs under wsl
@@ -3119,8 +3137,11 @@ configureUpdateCron() {
     sudo chmod +x "/etc/cron.d/bash-dev-env-upgrade"
   fi
 
-  OVERWRITE_CONFIG_FILES=1 Install::dir \
-    "${configDir}/.bash-dev-env" "${USER_HOME}/.bash-dev-env" "aliases.d"
+  # shellcheck disable=SC2154
+  Conf::copyStructure \
+    "${embed_dir_conf_dir}" \
+    "${CONF_OVERRIDE_DIR}/$(scriptName)" \
+    ".bash-dev-env"
 }
 
 configure() {
