Engine::Config::requireWslu fixed wsl interoperability issue due to wsl bug

diff --git a/installScripts/WslConfig b/installScripts/WslConfig
--- a/installScripts/WslConfig
+++ b/installScripts/WslConfig
@@ -313,13 +313,9 @@ Conf::list() {
 # @warning files are backup before being updated
 # @arg $1 hostName:String
 # @arg $2 ip:String optional, default value: 127.0.0.1
-# @set envVar type description
 # @env BASE_MNT_C String
-# @exitcode 1 description
-# @stdin description
-# @stdout description
 # @stderr diagnostics information is displayed
-# @see description
+# @env SUDO String allows to use custom sudo prefix command
 # @require Git::requireGitCommand
 # @require Linux::requireSudoCommand
 # @feature Retry::default
@@ -329,14 +325,14 @@ Dns::addHost() {
   local -a cmd
 
   if ! grep -q -E "[[:space:]]${hostName}([[:space:]]|$)" /etc/hosts; then
-    ${SUDO:-} backupFile /etc/hosts
+    SUDO=${SUDO:-} Backup::file /etc/hosts
     printf '%s\t%s\n' "${ip}" "${hostName}" | ${SUDO:-} tee -a /etc/hosts
     Log::displaySuccess "Host ${hostName} added to /etc/hosts"
   fi
   if Assert::wsl; then
     [[ -f "${BASE_MNT_C}/Windows/System32/drivers/etc/hosts" ]] || return 1
     if ! dos2unix <"${BASE_MNT_C}/Windows/System32/drivers/etc/hosts" | grep -q -E "[[:space:]]${hostName}([[:space:]]|$)"; then
-      backupFile "${BASE_MNT_C}/Windows/System32/drivers/etc/hosts"
+      SUDO=${SUDO:-} Backup::file "${BASE_MNT_C}/Windows/System32/drivers/etc/hosts"
       cmd=(
         -ExecutionPolicy Bypass
         -NoProfile
@@ -533,7 +529,7 @@ Engine::Config::loadConfig() {
   Engine::Config::loadUserVariables
   Engine::Config::loadHostIp
 
-  #Engine::Config::requireWslu
+  Engine::Config::requireWslu
 
   #Linux::Wsl::initEnv
   Engine::Config::loadWslVariables
@@ -604,7 +600,7 @@ Framework::createTempFile() {
 # @env USERGROUP (default: root) the group name that will be used to set target files ownership
 # @env BASE_MNT_C String windows C drive base PATH
 # @env FRAMEWORK_ROOT_DIR used to make paths relative to this directory to reduce length of messages
-# @env SUDO_USER String the user to use as sudoer
+# @env SUDO String allows to use custom sudo prefix command
 Install::file() {
   local fromFile="$1"
   local targetFile="$2"
@@ -634,8 +630,8 @@ Install::file() {
   local targetDir
   targetDir="$(dirname "${targetFile}")"
   if [[ ! -d "${targetDir}" ]]; then
-    ${SUDO} mkdir -p "${targetDir}"
-    ${SUDO} chown "${userName}":"${userGroup}" "${targetDir}"
+    ${SUDO:-} mkdir -p "${targetDir}"
+    ${SUDO:-} chown "${userName}":"${userGroup}" "${targetDir}"
   fi
   local fromDir
   fromDir="$(dirname "${fromFile}")"
@@ -644,7 +640,7 @@ Install::file() {
 
   Backup::file "${targetFile}" || return 2
 
-  if ${SUDO} cp "${fromFile}" "${targetFile}"; then
+  if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
     ${successCallback} "${fromFile}" "${targetFile}" "$@"
     Log::displaySuccess "Installed file '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fromFilename}' to '${targetFile}'"
   else
@@ -657,12 +653,13 @@ Install::file() {
 # @arg $1 fromFile:String
 # @arg $2 targetFile:String
 # @exitcode 1 on any failure
+# @env SUDO String allows to use custom sudo prefix command
 # @see Install::file
 Install::setUserRootCallback() {
   # shellcheck disable=SC2034 # $1 not used
   local fromFile="$1"
   local targetFile="$2"
-  chown root:root "${targetFile}"
+  ${SUDO:-} chown root:root "${targetFile}"
 }
 
 # @description the command launch different actions(install, configure, test)
@@ -1003,6 +1000,7 @@ Assert::windows() {
 # @description Backup given file in the same directory appending _ followed by the current date
 # @arg $1 file:String the file to backup
 # @stderr messages about backup file location
+# @env SUDO String allows to use custom sudo prefix command
 # @exitcode 1 on copy failure
 Backup::file() {
   local file="$1"
@@ -1010,7 +1008,7 @@ Backup::file() {
   if [[ -f "${file}" ]]; then
     backupFile="${file}_$(date +"%Y-%m-%d_%H:%M:%S")"
     Log::displayInfo "Backup file '${file}' to ${backupFile}"
-    cp "${file}" "${backupFile}"
+    ${SUDO:-} cp "${file}" "${backupFile}"
   fi
 }
 
@@ -1327,6 +1325,26 @@ Engine::Config::loadWslVariables() {
   return "${errorCount}"
 }
 
+# @description install apt wslu if necessary providing wslvar, wslpath
+Engine::Config::requireWslu() {
+  if ! command -v wslvar &>/dev/null; then
+    Log::displayInfo "Installing pre-requisite Wslu : wslvar, wslpath, ... commands"
+    Linux::Apt::update
+    Linux::Apt::install --no-install-recommends wslu
+
+    # @see https://github.com/microsoft/WSL/issues/8843#issuecomment-1792256894
+    Log::displayInfo "Fix wsl interoperability due to wsl bug"
+    if [[
+      ! -f /usr/lib/binfmt.d/WSLInterop.conf &&
+      ! -f /etc/systemd/system/wsl-binfmt.service &&
+      -f /run/systemd/generator.early/wsl-binfmt.service
+    ]]; then
+      sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
+      sudo ln -s /run/systemd/generator.early/wsl-binfmt.service /etc/systemd/system/wsl-binfmt.service
+    fi
+  fi
+}
+
 # @description prepend directories to the PATH environment variable
 # @arg $@ args:String[] list of directories to prepend
 # @set PATH update PATH with the directories prepended
@@ -1347,6 +1365,7 @@ Env::pathPrepend() {
 # @arg $4 userGroup:String (optional) (default: ${USERNAME}) the group name that will be used to set target files ownership
 # @env USERNAME (default: root) the user name that will be used to set target files ownership
 # @env USERGROUP (default: root) the group name that will be used to set target files ownership
+# @env SUDO String allows to use custom sudo prefix command
 # @exitcode 1 on any failure
 # @see Install::file
 Install::setUserRightsCallback() {
@@ -1356,7 +1375,7 @@ Install::setUserRightsCallback() {
   local userName="${3:-${USERNAME:-root}}"
   local userGroup="${4:-${USERGROUP:-root}}"
 
-  chown "${userName}":"${userGroup}" "${targetFile}"
+  ${SUDO:-} chown "${userName}":"${userGroup}" "${targetFile}"
 }
 
 # @description install callback
@@ -1610,6 +1629,23 @@ Assert::varExistsAndNotEmpty() {
   fi
 }
 
+# @description apt-get install
+# @arg $@ softwares:String[] list of softwares to install
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::install() {
+  Retry::default sudo apt-get install -y -q "$@"
+}
+
+# @description update apt packages list
+# @feature Retry::default
+# Linux::requireSudoCommand
+# @require Linux::requireUbuntu
+Linux::Apt::update() {
+  Retry::default sudo apt-get update -y --fix-missing -o Acquire::ForceIPv4=true
+}
+
 # @description retrieve path from wslvar and then use wslpath to resolve it
 # using cache (cache is refreshed every day)
 # @arg $1 var:String the var to retrieve using wslvar
@@ -1839,6 +1875,22 @@ Log::logSkipped() {
   fi
 }
 
+# @description Retry a command 5 times with a delay of 15 seconds between each attempt
+# @arg $@ command:String[] the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+Retry::default() {
+  Retry::parameterized 5 15 "" "$@"
+}
+
+# @description ensure linux distribution is ubuntu
+# @exitcode 1 if linux distribution is not ubuntu
+Linux::requireUbuntu() {
+  if ! Array::contains "$(Linux::getDistributorId)" "Ubuntu" "Debian"; then
+    Log::fatal "this script should be executed under Ubuntu or Debian OS"
+  fi
+}
+
 # @description ensure linux runs under wsl
 # @env WSL_GARBAGE_COLLECT int 0 to disable garbage collect of cache files
 # @exitcode 1 if linux does not run under wsl
@@ -1923,6 +1975,51 @@ Linux::Wsl::originalWslpath() {
   wslpath "$@"
 }
 
+# @description retrieve linux distributor id
+# @noargs
+# @exitcode 1 if lsb_release fails or not found
+# @stdout the linux distributor id
+Linux::getDistributorId() {
+  lsb_release -a 2>/dev/null | sed -En 's/Distributor ID:[ \t]+(.+)/\1/p'
+}
+
+# @description Retry a command several times depending on parameters
+# @arg $1 maxRetries:int    $1 max retries
+# @arg $2 delay:int between attempt
+# @arg $3 message:String to display to describe the attempt
+# @arg $@ rest of parameters, the command to run
+# @exitcode 0 on success
+# @exitcode 1 if max retries count reached
+# @exitcode 2 if maxRetries invalid value
+Retry::parameterized() {
+  local maxRetries=$1
+  shift || true
+  local delayBetweenTries=$1
+  shift || true
+  local message="$1"
+  shift || true
+  local retriesCount=1
+  if [[ "${maxRetries}" -lt 1 ]]; then
+    Log::displayError "invalid maxRetry value"
+    return 2
+  fi
+
+  while true; do
+    Log::displayInfo "Attempt ${retriesCount}/${maxRetries}: ${message}"
+    if "$@"; then
+      break
+    elif [[ "${retriesCount}" -lt "${maxRetries}" ]]; then
+      Log::displayWarning "Command failed. Wait for ${delayBetweenTries} seconds"
+      ((retriesCount++))
+      sleep "${delayBetweenTries}"
+    else
+      Log::displayError "The command has failed after ${retriesCount} attempts."
+      return 1
+    fi
+  done
+  return 0
+}
+
 # FUNCTIONS
 
 facade_main_WslConfigsh() {
@@ -1932,6 +2029,7 @@ Linux::requireSudoCommand
 Env::requireLoad
 UI::requireTheme
 Log::requireLoad
+Linux::requireUbuntu
 Linux::Wsl::requireWsl
 Compiler::Facade::requireCommandBinDir
 
